### ISSUE TITLE
How to Build a Docker Image for Stirling-PDF Repository

### ISSUE THREAD

**Issue by mkamranmazhar** [Stirling-Tools/Stirling-PDF#1005]
Hello,

I've done some changes in frontend layout according to my needs. now I want to build a Docker image for the updated code so that I can easily deploy and run the application in a containerized environment.

Please guide me on how to re-build Docker image.
Thank you.

**Comment by sbplat** [comment]
```sh
docker build .
```
in the root dir.

**Comment by Frooodle** [comment]
``./gradlew build``

followed by

``docker build . ``

**Comment by mkamranmazhar** [comment]
Please check 

`[root@vmi Stirling-PDF]# docker build .
[+] Building 0.5s (10/11)                                                                                                                                                                                                     docker:default
 => [internal] load build definition from Dockerfile                                                                                                                                                                                    0.0s
 => => transferring dockerfile: 2.26kB                                                                                                                                                                                                  0.0s
 => [internal] load metadata for docker.io/library/alpine:3.19.1                                                                                                                                                                        0.2s
 => [internal] load .dockerignore                                                                                                                                                                                                       0.0s
 => => transferring context: 2B                                                                                                                                                                                                         0.0s
 => [1/7] FROM docker.io/library/alpine:3.19.1@sha256:c5b1261d6d3e43071626931fc004f70149baeba2c8ec672bd4f27761f8e1ad6b                                                                                                                  0.0s
 => [internal] load build context                                                                                                                                                                                                       0.2s
 => => transferring context: 28.34MB                                                                                                                                                                                                    0.2s
 => CACHED [2/7] COPY scripts /scripts                                                                                                                                                                                                  0.0s
 => CACHED [3/7] COPY pipeline /pipeline                                                                                                                                                                                                0.0s
 => CACHED [4/7] COPY src/main/resources/static/fonts/*.ttf /usr/share/fonts/opentype/noto                                                                                                                                              0.0s
 => CACHED [5/7] COPY src/main/resources/static/fonts/*.otf /usr/share/fonts/opentype/noto                                                                                                                                              0.0s
 => ERROR [6/7] COPY build/libs/*.jar app.jar                                                                                                                                                                                           0.0s
------
 > [6/7] COPY build/libs/*.jar app.jar:
------
Dockerfile:9
--------------------
   7 |     COPY src/main/resources/static/fonts/*.ttf /usr/share/fonts/opentype/noto
   8 |     COPY src/main/resources/static/fonts/*.otf /usr/share/fonts/opentype/noto
   9 | >>> COPY build/libs/*.jar app.jar
  10 |
  11 |     ARG VERSION_TAG
--------------------
ERROR: failed to solve: lstat /var/lib/docker/tmp/buildkit-mount2102415930/build/libs: no such file or directory
[root@vmi Stirling-PDF]#
`

**Comment by sbplat** [comment]
You need to build with Gradle first.

**Comment by mkamranmazhar** [comment]
yes,
it's working now with Gradle first.

Thank you.

**Comment by mkamranmazhar** [comment]
Stop Generating Multiple Docker Images After Code Updates.

Whenever I make changes to the source code, I find myself constantly rebuilding the Docker image using the Dockerfile.

This process, results in multiple Docker images being generated.

how to streamline this process to avoid creating unnecessary Docker images and update the same Docker image that was created during the initial build.

Thank you.

**Comment by mkamranmazhar** [comment]
Please also check the build Process is completed after apply changes in code.
now how to run this image?
`
[root@vmi Stirling-PDF]# ./gradlew build
Downloading https://services.gradle.org/distributions/gradle-7.6-bin.zip
...........10%............20%...........30%............40%............50%...........60%............70%............80%...........90%............100%

Welcome to Gradle 7.6!

Here are the highlights of this release:
 - Added support for Java 19.
 - Introduced `--rerun` flag for individual task rerun.
 - Improved dependency block for test suites to be strongly typed.
 - Added a pluggable system for Java toolchains provisioning.

For more details see https://docs.gradle.org/7.6/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :
0.22.6

> Task :compileJava
Note: /www/wwwroot/pdf.askseotools.com/Stirling-PDF/src/main/java/stirling/software/SPDF/controller/api/pipeline/PipelineProcessor.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

BUILD SUCCESSFUL in 1m 9s
10 actionable tasks: 10 executed
[root@vmi1766336 Stirling-PDF]# docker build .
[+] Building 103.2s (12/12) FINISHED                                                                                                                                                                                          docker:default
 => [internal] load build definition from Dockerfile                                                                                                                                                                                    0.0s
 => => transferring dockerfile: 2.26kB                                                                                                                                                                                                  0.0s
 => [internal] load metadata for docker.io/library/alpine:3.19.1                                                                                                                                                                        0.7s
 => [internal] load .dockerignore                                                                                                                                                                                                       0.0s
 => => transferring context: 2B                                                                                                                                                                                                         0.0s
 => [1/7] FROM docker.io/library/alpine:3.19.1@sha256:c5b1261d6d3e43071626931fc004f70149baeba2c8ec672bd4f27761f8e1ad6b                                                                                                                  0.4s
 => => resolve docker.io/library/alpine:3.19.1@sha256:c5b1261d6d3e43071626931fc004f70149baeba2c8ec672bd4f27761f8e1ad6b                                                                                                                  0.0s
 => => sha256:4abcf20661432fb2d719aaf90656f55c287f8ca915dc1c92ec14ff61e67fbaf8 3.41MB / 3.41MB                                                                                                                                          0.1s
 => => sha256:c5b1261d6d3e43071626931fc004f70149baeba2c8ec672bd4f27761f8e1ad6b 1.64kB / 1.64kB                                                                                                                                          0.0s
 => => sha256:6457d53fb065d6f250e1504b9bc42d5b6c65941d57532c072d929dd0628977d0 528B / 528B                                                                                                                                              0.0s
 => => sha256:05455a08881ea9cf0e752bc48e61bbd71a34c029bb13df01e40e3e70e0d007bd 1.47kB / 1.47kB                                                                                                                                          0.0s
 => => extracting sha256:4abcf20661432fb2d719aaf90656f55c287f8ca915dc1c92ec14ff61e67fbaf8                                                                                                                                               0.2s
 => [internal] load build context                                                                                                                                                                                                       0.7s
 => => transferring context: 139.27MB                                                                                                                                                                                                   0.7s
 => [2/7] COPY scripts /scripts                                                                                                                                                                                                         0.1s
 => [3/7] COPY pipeline /pipeline                                                                                                                                                                                                       0.0s
 => [4/7] COPY src/main/resources/static/fonts/*.ttf /usr/share/fonts/opentype/noto                                                                                                                                                     0.1s
 => [5/7] COPY src/main/resources/static/fonts/*.otf /usr/share/fonts/opentype/noto                                                                                                                                                     0.0s
 => [6/7] COPY build/libs/*.jar app.jar                                                                                                                                                                                                 0.3s
 => [7/7] RUN echo "@testing https://dl-cdn.alpinelinux.org/alpine/edge/main" | tee -a /etc/apk/repositories &&     echo "@testing https://dl-cdn.alpinelinux.org/alpine/edge/community" | tee -a /etc/apk/repositories &&     echo "  96.2s
 => exporting to image                                                                                                                                                                                                                  5.0s
 => => exporting layers                                                                                                                                                                                                                 5.0s
 => => writing image sha256:7174deb11792f0f8389e580e920e2f88be3558a0d25abc1625f0bc90f34963af                                                                                                                                            0.0s
[root@vmi Stirling-PDF]#
`
