### ISSUE TITLE
[Feature Request] Add command line parameter ‘—port’ to windows exe

### ISSUE THREAD

**Issue by imClumsyPanda** [Stirling-Tools/Stirling-PDF#1009]
#### Summary
I am currently using the `stirlingpdf` program on Windows by launching it as an `.exe` file. I'd like to request a feature that allows users to specify the port on which `stirlingpdf` runs when starting it from the command line.

#### Motivation
Being able to define the port via the command line would provide greater flexibility in various deployment and development scenarios where the default port might be in use or when running multiple instances on different ports.

#### Description
The feature could be implemented by introducing a new command-line parameter, such as `--port` or `-p`, which overrides the default port setting. For example:

```
stirlingpdf.exe --port 8080
```

Or with a shorthand flag:

```
stirlingpdf.exe -p 8080
```

This enhancement would enable users to launch `stirlingpdf` on a specific port with ease, facilitating better integration with other services and tools in their workflow.

I hope this feature aligns with the roadmap for `stirlingpdf` and look forward to your feedback on this proposal.

Thank you for considering my request.

Kind regards,
Panda

**Comment by Frooodle** [comment]
Can you try something like
``Stirling-PDF.exe --server.port=8085``

**Comment by imClumsyPanda** [comment]
> Can you try something like `Stirling-PDF.exe --server.port=8085`

It works! Thank you soooo much! By the way I’ve searched but haven’t found docs about this, would you share link about command line documentation?

**Comment by Frooodle** [comment]
There isnt any existing docs for this currently

**Comment by imClumsyPanda** [comment]
@Frooodle Thank you!

Here’s another problem, I’m running Stirling-PDF on windows, when i run the exe it always says as below: 
```
S.software.SPDF.SpdfApplication - Running configs … endpoints=Endpoints [toRemove=[], groupsToRemove=[CLI]] …
```
But actually my setting is:
```
endpoints:
  toRemove=[]
  groupsToRemove=[]
```
And in cmd it says `s.s.S.config.EndpointConfigration - Disabling file-to-pdf`, so is pdf-to-text, repair, and more functions.

Is there any way to solve this?

**Comment by Frooodle** [comment]
These are functions that the exe doesn't support so will always be disabled 
Sadly most conversions require externals apps which are only included in the docker

**Comment by imClumsyPanda** [comment]
@Frooodle thanks a lot!
