### ISSUE TITLE
Help needed: Pipeline / WatchedFolder - Wait for a second PDF-file.

### ISSUE THREAD

**Issue by Mikei386** [Stirling-Tools/Stirling-PDF#1030]
Can anyone help me solve this:

I'm using the pipeline-feature to merge and duplex-sort documents from my scanner, which is not able to duplex-scan.

So, I scan the first side of an document and then, after rotating the paper, the second side is scanned.
But bevor I’m able so scan the second side, S-PDF already processed the first PDF from the first scan.

Is there any way to wait for a second PDF inside the watched folder, before starting the process? Or is there a way to set a rate in which the folder is scanned?

Any help would be appreciated. Thanks

**Comment by Frooodle** [comment]
Not currently possible but i can see about this as a enhancement

**Comment by Frooodle** [comment]
Currently it's not for multiple pdfs

**Comment by Mikei386** [comment]
Thank you for your reply.

As for now I accomplished it via a workaround.
A little bash script, which monitors the folder I'm scanning to. As soon as it contains two pdf files, the script moves them to the watched folder of S-PDF.

Maybe, at some day, something like this could be implemented.

Thank you a lot.
