### ISSUE TITLE
Pipeline produces empty file download.txt

### ISSUE THREAD

**Issue by sjung87** [Stirling-Tools/Stirling-PDF#1034]
Hi Stirling-PDF Team,

first of all, thanks for this great app. I discovered it recently and immediately add it to my home services :)

I want to use the pipeline function to make a watchdog for scanned documents.
Scan to folder > OCR + some post processing > take it from the output folder

Unfortunate, when trying my pipeline in the GUI the output is always an empty file "download.txt". Also (of course) the pipeline is not working in the configured folder. Is there anything I done wrong?

Here is the pipeline definition:
[OCR-Watchdog.json](https://github.com/Stirling-Tools/Stirling-PDF/files/14885978/OCR-Watchdog.json)

`{
  "name": "OCR-Watchdog",
  "pipeline": [
    {
      "operation": "/api/v1/misc/remove-blanks",
      "parameters": {
        "threshold": 10,
        "whitePercent": 99.9,
        "fileInput": "automated"
      }
    },
    {
      "operation": "/api/v1/misc/ocr-pdf",
      "parameters": {
        "languages": [
          "deu",
          "eng"
        ],
        "sidecar": false,
        "deskew": true,
        "clean": true,
        "cleanFinal": false,
        "ocrType": "skip-text",
        "ocrRenderType": "hocr",
        "removeImagesAfter": false,
        "fileInput": "automated"
      }
    },
    {
      "operation": "/api/v1/misc/auto-rename",
      "parameters": {
        "useFirstTextAsFallback": false,
        "fileInput": "automated"
      }
    }
  ],
  "_examples": {
    "outputDir": "{outputFolder}/{folderName}",
    "outputFileName": "{filename}-{pipelineName}-{date}-{time}"
  },
  "outputDir": "{outputFolder}/Scan-Output",
  "outputFileName": "{filename}"
}`

Tried different language descriptions (e.g. "German","English") but none worked.
Running 0.22.8 on Docker.

Thanks a lot!

**Comment by Frooodle** [comment]
https://github.com/Stirling-Tools/Stirling-PDF/discussions/989

seem to have their languages as "languages": "deu, eng",

Not sure if that will fix it, also are there any docker logs you can share about this if you still facing issue?

**Comment by sjung87** [comment]
Thanks for the quick answer! Yes, that fixed it 👍
