### ISSUE TITLE
Converting pdf to img file name containing Chinese failed

### ISSUE THREAD

**Issue by While4** [Stirling-Tools/Stirling-PDF#1035]
<img width="1251" alt="image" src="https://github.com/Stirling-Tools/Stirling-PDF/assets/47239344/4f502bb1-7973-48e7-9039-062cc102a74e">
<img width="655" alt="image" src="https://github.com/Stirling-Tools/Stirling-PDF/assets/47239344/5f7b951b-d0d9-482c-a6e1-082b38650638">

Hi Stirling-PDF Team,
When I use the pdf to img function, if the name of the pdf file I upload contains Chinese, at this time, I will get a file named "download" instead of the "download.zip" file, although I can manually add ".zip" to make it work.

**Comment by xiaoxuesheng1006** [comment]
Use URLEncoder to solve errors caused by non-ASCII characters. You need to add file name modifications to the last else branch in the interface /pdf/img. The specific code is as follows

`            // support Chinese file names
            String encodedFilename =
                    URLEncoder.encode(filename, StandardCharsets.UTF_8.toString())
                            .replaceAll("\\+", "%20");
            // return the Resource in the response
            return ResponseEntity.ok()
                    .header(
                            HttpHeaders.CONTENT_DISPOSITION,
                            "attachment; filename=" + encodedFilename + "_convertedToImages.zip")
                    .contentType(MediaType.APPLICATION_OCTET_STREAM)
                    .contentLength(resource.contentLength())
                    .body(resource);`

**Comment by While4** [comment]
It does work, thank you
