### ISSUE TITLE
Merge Files Error

### ISSUE THREAD

**Issue by WaveZZZZZ** [Stirling-Tools/Stirling-PDF#1041]
Once the number of files exceeds a certain threshold, the browser throws an error and cannot download the merged file. Currently, it hasn't been tested whether it's the number of files exceeding the limit or the size of individual files exceeding it. In any case, the issue can definitely be replicated.
![微信截图_20240408161643](https://github.com/Stirling-Tools/Stirling-PDF/assets/116855502/985e0d1d-086c-4c8a-934a-ed3fff99a22e)

**Comment by Frooodle** [comment]
What's the error?

**Comment by WaveZZZZZ** [comment]
The testing should involve whether the error occurs when the number of pages exceeds a certain limit, or when the merged file size surpasses a threshold. Is it possible to adjust this value, or is it related to the web server?

**Comment by WaveZZZZZ** [comment]
> 有什么错误？
Apologies for not describing clearly. After clicking "Merge," EDGE displays a download failure.

**Comment by WaveZZZZZ** [comment]
> What's the error?

Apologies for not describing clearly. After clicking "Merge," EDGE displays a download failure.

**Comment by Frooodle** [comment]
Does this issue still happen? Closing for now as very old ticket
