### ISSUE TITLE
There is a problem with the output formatting of the url to pdf function.

### ISSUE THREAD

**Issue by fsteddycc** [Stirling-Tools/Stirling-PDF#1042]
When generating PDFs through URLs, the display is often incomplete. The text and pictures are moved to the right and the display is incomplete. Each page needs to be adjusted. Can it automatically adapt to the page width during conversion and display completely?
![Uploading _Users_jiancongtang_Downloads_https___zhuanlan_zhihu_com_p_643852738.pdf.png…]()

**Comment by fsteddycc** [comment]
![_Users_jiancongtang_Downloads_https___zhuanlan_zhihu_com_p_643852738 pdf](https://github.com/Stirling-Tools/Stirling-PDF/assets/166408092/0877d8fc-430d-4402-a284-29846eca3c92)

**Comment by Frooodle** [comment]
upstream issue sadly not with our application but our use of weasyprint, would need to raise with them
