### ISSUE TITLE
How to open a pdf in /view-pdf by double clicking?

### ISSUE THREAD

**Issue by stefan52a** [Stirling-Tools/Stirling-PDF#1058]
This might be OS and/or browser specific. But can I open a pdf in <base url>/view-pdf by **double clicking** on the pdffilename from ubuntu nautilus, window explorer and mac finder?

**Comment by Frooodle** [comment]
Not that i am aware sorry

**Comment by sbplat** [comment]
You can try using platform dependent configurations. For example, on Windows, you can [register](https://learn.microsoft.com/en-us/windows/win32/shell/fa-file-types#registering-a-file-type) a PDF file to a program that opens the URL with your browser.
