### ISSUE TITLE
When using the url to pdf function, the image cannot be saved.

### ISSUE THREAD

**Issue by Le1a** [Stirling-Tools/Stirling-PDF#1061]
When using the url to pdf function, the image cannot be saved.
<img width="848" alt="image" src="https://github.com/Stirling-Tools/Stirling-PDF/assets/97610822/235acc7d-6eda-4495-a110-f906678a6886">

https://xz.aliyun.com/t/14263?time__1311=mqmx9QiQi%3DDtWq05DI74CT%2BCodunxGIdx&alichlgref=https%3A%2F%2Fxz.aliyun.com%2F

<img width="1031" alt="image" src="https://github.com/Stirling-Tools/Stirling-PDF/assets/97610822/77d8bfce-9281-4371-8f73-d209de024bc2">

**Comment by deka014** [comment]
@Le1a Your images are not visible in the url itself ! Can you confirm it once ?
