### ISSUE TITLE
Save previously used settings

### ISSUE THREAD

**Issue by willieramosjr1** [Stirling-Tools/Stirling-PDF#1065]
For example when using OCR i always have to select english and the sandwich option for every file i convert but it would be nice if those settings stick instead of having to manually select them.

Another example:
Auto refresh the page after a conversion is done. I usually have stirling open in a window all day because I'm constantly doing conversions but one issue I have is after a conversion is done the same file is still attached until i refresh the page to make it drop that file. It's not a bug or a big deal but for me I'm always working fast so I end up dragging a new file to convert not realizing the previous file is still selected, which leads to both files being attached/selected.

![Uploading Screenshot 2024-04-12 135008.png…]()

**Comment by Frooodle** [comment]
I like the idea!
