### ISSUE TITLE
Issue with modifying the content of a PDF file.

### ISSUE THREAD

**Issue by wang1231** [Stirling-Tools/Stirling-PDF#1067]
I would like to inquire about how to replace specific text or images within a PDF file without altering the original style of the document. I need to replace only the designated elements within the PDF. How can I do this? Thank you.

**Comment by Frooodle** [comment]
Not currently possible sorry

**Comment by wang1231** [comment]
I see that this project is quite powerful. Can't we just export XML with LibreOffice, modify it, and then convert it to PDF?

**Comment by Frooodle** [comment]
I don't believe libre office supports pdf to XML conversion

**Comment by wang1231** [comment]
I have tried this project, and it uses LibreOffice for converting PDF to XML. Are there any good implementation ideas? I would appreciate some suggestions, thank you.

**Comment by Frooodle** [comment]
Could to pdf to html and then html to pdf
