### ISSUE TITLE
Pdftoword problem!  I am running inside the docker,but also  exist the problem!

### ISSUE THREAD

**Issue by xingzhej** [Stirling-Tools/Stirling-PDF#1074]
![微信截图_20240416152259](https://github.com/Stirling-Tools/Stirling-PDF/assets/7656535/6ef05f84-7fa0-4966-a7f7-ea3c8141ea72)
![微信截图_20240416152409](https://github.com/Stirling-Tools/Stirling-PDF/assets/7656535/c30c3b60-aa4c-4832-b5b0-82eec8b10666)

**Comment by xingzhej** [comment]
![微信截图_20240416153600](https://github.com/Stirling-Tools/Stirling-PDF/assets/7656535/bd0b1888-b9cf-46cc-b227-de395b58e60a)
There is no soffice installed,But when i built the image,office successed!

**Comment by Frooodle** [comment]
Seems to be a issue with latest alpine

**Comment by xingzhej** [comment]
> Seems to be a issue with latest alpine

Yestoday is ok!   when i build the image there are 400 tasks! but 401 today,I dont know why!
what can i do for this issue!

**Comment by xingzhej** [comment]
> > Seems to be a issue with latest alpine
> 
> Yestoday is ok! when i build the image there are 400 tasks! but 401 today,I dont know why! what can i do for this issue!

![Uploading 微信截图_20240416155230.png…]()

**Comment by xingzhej** [comment]
> > Seems to be a issue with latest alpine
> 
> Yestoday is ok! when i build the image there are 400 tasks! but 401 today,I dont know why! what can i do for this issue!

![微信截图_20240416155230](https://github.com/Stirling-Tools/Stirling-PDF/assets/7656535/8835373e-bb7d-46ae-8665-0b4eb19f0b60)

**Comment by xingzhej** [comment]
https://github.com/Stirling-Tools/Stirling-PDF/assets/7656535/91c2b05b-5db1-4da3-8980-d58b4c184bce

![微信截图_20240416161004](https://github.com/Stirling-Tools/Stirling-PDF/assets/7656535/940fdfe1-f8d4-4a8d-a960-840cb4e33f04)

**Comment by Frooodle** [comment]
issue should be fixed
