### ISSUE TITLE
set Time Zone

### ISSUE THREAD

**Issue by BeckeBauer** [Stirling-Tools/Stirling-PDF#1075]
I tried to set my Time Zone in docker-compose.yaml as follows:

```
environment:
    -TZ="Europe/Berlin"
```
However, when I enter the container and execute `date`, the UTC time is shown:
`Tue Apr 16 12:37:58 UTC 2024 `

Accordingly, the filenames of my scans to which the time is attached, do not show the time when the scan was made. 

Is there any way to adjust the Time Zone when running stirling-pdf in docker?

**Comment by Ludy87** [comment]
remove the quotes `"` and try again

**Comment by BeckeBauer** [comment]
> remove the quotes `"` and try again

that was it, thank you
