### ISSUE TITLE
Search Functionality on Navbar

### ISSUE THREAD

**Issue by jimdouk** [Stirling-Tools/Stirling-PDF#1076]
We've identified a front-end issue with the search functionality on the navbar. Currently, upon clicking the search icon for the first time, it displays an incomplete appearance:

![dde14f65-2d8a-4f77-bbff-a898143b0b1a](https://github.com/Stirling-Tools/Stirling-PDF/assets/115452543/efe81043-c63c-4676-8e4c-9c2a78fb8f30)

Subsequently, when users input text, relevant functionalities appear as expected. However, upon deleting the entered text, all functionalities are displayed, revealing a mismatch between the search bar and the suggestion box.

![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/115452543/f0c33c7e-4a27-42c9-b71d-4fb2e57fcd13)

To enhance user experience, I suggest that upon clicking the search icon, all suggestions are displayed immediately, or alternatively, improving the appearance of the suggestion box to ensure consistency with the search bar.

Thank you for your attention to this matter.

**Comment by Frooodle** [comment]
There are some big UI updates coming soon might want to hold off changes

**Comment by jimdouk** [comment]
Ok i will wait for the UI updates. Thanks you for the information!

**Comment by Frooodle** [comment]
I seen this got merged, 
right now search bar is removed in
https://github.com/Stirling-Tools/Stirling-PDF/pull/1193
Will try readd

**Comment by jimdouk** [comment]
thank you very much!
I will take a look on redesign open issue
