### ISSUE TITLE
Help me! alpine caused the problem!

### ISSUE THREAD

**Issue by xingzhej** [Stirling-Tools/Stirling-PDF#1077]
FROM alpine:3.19.1  pdftoword is not correct,nomatter how many pages,the word is only one page!
FROM alpine:20240329 the pdftowrd has soffce,No such file or directory problem. office was not installed!
Is there any other vertion？At the beginning, the 20240329 version is right!

**Comment by Frooodle** [comment]
Correct, this is blocking our release at moment it's very annoying

https://gitlab.alpinelinux.org/alpine/aports/-/issues/16005

**Comment by xingzhej** [comment]
@Frooodle  Iwonder if this problem is fixed?

**Comment by Frooodle** [comment]
Hope so 😂
