### ISSUE TITLE
extract images  error

### ISSUE THREAD

**Issue by goldyaphets** [Stirling-Tools/Stirling-PDF#1079]
![extracterror](https://github.com/Stirling-Tools/Stirling-PDF/assets/120435311/e8762bcc-f348-4695-bdce-e3db2d47da57)

when i  extract images from a pdf , it says   Internal Server Error:LCMS error 13: Mismatched alpha channels

**Comment by goldyaphets** [comment]
but i use the demo url   ,it can extract successfully

**Comment by sbplat** [comment]
Are you on the latest version?

**Comment by Frooodle** [comment]
duplicate of #1024
