### ISSUE TITLE
Activate SSL via Lets encrypt

### ISSUE THREAD

**Issue by Atoxien** [Stirling-Tools/Stirling-PDF#1081]
Dear community, dear creator,

I use the PDF tool with access to a public server. But how can I install SSL via Lets Encrypt? Don't want to use a self-signed certificate as it would be a Lets Encrypt certificate.

Is there a way to integrate this and make it only accessible via https?

LG Atoxien

**Comment by Ludy87** [comment]
## Import Certificate into a Keystore:
You need to convert the PEM-formatted certificate and private key into a PKCS12 keystore. This can be done with OpenSSL:

```bash
openssl pkcs12 -export -in /etc/letsencrypt/live/yourdomain.com/fullchain.pem -inkey /etc/letsencrypt/live/yourdomain.com/privkey.pem -out keystore.p12 -name yourdomain -CAfile /etc/letsencrypt/live/yourdomain.com/chain.pem -caname root
```

## Configure Spring Boot:

Enter the path and password information in your `application.properties`:

```bash
# Server port to run the application on HTTPS
server.port=8443

# SSL key-store configuration
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=yourkeystorepassword
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=yourdomain

# Require SSL
server.ssl.enabled=true
```

Replace `yourkeystorepassword` with your keystore password and `yourdomain` with the alias you used during the export.

I'm not sure if it will work, but you can test it.

**Comment by STREKOZZEL** [comment]
HTTPS works on standalone version with PEM key and certificate with this settings in file `/opt/Stirling-PDF/configs/custom_settings.yml`

```
server:
  port: 443
  ssl:
    certificate: /opt/Stirling-PDF/configs/fullchain.pem
    certificate-private-key: /opt/Stirling-PDF/configs/privkey.pem
```
HTTPS on docker version maybe works with configuration from this comment https://github.com/Stirling-Tools/Stirling-PDF/issues/425#issuecomment-2017584492
