### ISSUE TITLE
PDF2DOC failed

### ISSUE THREAD

**Issue by Softbox44** [Stirling-Tools/Stirling-PDF#1084]
I added a PDF, started conversion. 
The button went from "Convert" to "Processing" but neve finished. After 5mins the button went back to "Convert".
So I pressed Convert again and the following screen appeared: 

![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/163422442/8e201149-5ba4-4f94-ae64-bc3a7d7988f0)

**Comment by sbplat** [comment]
Try increasing the timeout duration.

**Comment by Softbox44** [comment]
How do I do this?

**Comment by sbplat** [comment]
Are you using a proxy? Also, is there anything in the logs?

**Comment by wlevene** [comment]
pdf2document.com - No loss of pdf layout
30 free page conversions daily for all users.
