### ISSUE TITLE
DOC Conversion

### ISSUE THREAD

**Issue by Softbox44** [Stirling-Tools/Stirling-PDF#1085]
I am trying to convert a 83 page document. Neither the DOC output nor the DOCX output of the conversion can be opened by LibreOffice.

When opening, the screen just stays white.

![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/163422442/9633cec4-38b8-4ce5-917c-c40ef0449ee3)

**Comment by Frooodle** [comment]
I have tried a 200 page doc and it seemed to work, it might be something unique to your file, Are you able to share or give similar file that causes this?

**Comment by Softbox44** [comment]
unfortunately I cannot share the doc publicly
