### ISSUE TITLE
Markdown to PDF doesn't work with cyrillic characters

### ISSUE THREAD

**Issue by GregoryKogan** [Stirling-Tools/Stirling-PDF#1087]
Version: 0.22.8
Hosted in docker via coolify

Cyrillic characters don't display properly after markdown -> pdf conversion.

<p align="center">
	<img width="50%" alt="image" src="https://github.com/Stirling-Tools/Stirling-PDF/assets/60318411/ba1f53ae-9d89-433d-9ac8-5924becbbc98">
</p>

It also does not support latex snippets inside `$$`. 
Why did you choose to use WeasyPrint instead of Pandoc?

**Comment by EvertonCardosoDeolinda** [comment]
Estou com uma situação Semelhante
![README](https://github.com/Stirling-Tools/Stirling-PDF/assets/43457563/cd78c7bf-2c76-42f2-a6c9-8d24ebec8434)

**Comment by Frooodle** [comment]
This is due to missing fonts, you can add them by specifying you language code
https://github.com/Stirling-Tools/Stirling-PDF/blob/main/exampleYmlFiles/docker-compose-latest.yml#L24
it should hopefully try download the correct font
