### ISSUE TITLE
Add remove watermark function

### ISSUE THREAD

**Issue by albanobattistella** [Stirling-Tools/Stirling-PDF#1089]
Hello,
in sterling I haven't found a function to remove watermarks.
That would be a nice feature to add.
Thank you.
Albano

**Comment by loviuz** [comment]
News about it? :-)

**Comment by Frooodle** [comment]
https://github.com/Stirling-Tools/Stirling-PDF/issues/55

Decided long back not to add it
Not many reasons anyone would want to remove watermarks and not also have original copy

**Comment by chenjuefei** [comment]
If there were a vote on adding a watermark removal feature, I would definitely support it. Acrobat allows users to add or remove watermarks with just one click, but some PDFs have been maliciously watermarked by people who don’t hold the copyright, and the content was originally free to access.
