### ISSUE TITLE
Loaded PDF file is not displayed?

### ISSUE THREAD

**Issue by phunkybeam** [Stirling-Tools/Stirling-PDF#1111]
I'm a little surprised that nobody seems to have any problems with this. No matter which tool I select in which a view of the loaded file is provided, it is not displayed to me! In the beginning it worked and then it didn't work anymore. 

The problem occurs in Chrome and Edge.

**Comment by Frooodle** [comment]
any logs in f12 console? are you using nginx?, what spdf version etc
