### ISSUE TITLE
【bug】Environment variables do not take effect

### ISSUE THREAD

**Issue by wintsa123** [Stirling-Tools/Stirling-PDF#1121]
i try to set              'e - LANGS=zh_CN' in docker,but it not show zh_CN default.

and i try to change setting.yml,, "defaultLocale: 'zh_CN' ",go on restart,and  it not show zh_CN default.

**Comment by Frooodle** [comment]
LANGS=zh_CN is not for default but for fonts

It's default locale which is for the default Lang 
We have a fix for default Lang coming I believe

**Comment by wintsa123** [comment]
> LANGS=zh_CN 不是默认值，而是字体
> 
> 这是默认语言环境，适用于默认 Lang 我相信我们对默认 Lang 进行了修复


I hope my Stirling will open in Chinese by default. I have set the environment to LANGS=zh-CN in Docker, and set defaultLocales: zh-CN in the settings. yml file of config. I have also restarted and refreshed the browser cache, but unfortunately it did not take effect

**Comment by gepcel** [comment]
It's not `zh_CN`, but `zh-CN`. So `settings.yml` should be like:

```
system:
  defaultLocale: 'zh-CN' 
```

**Comment by wintsa123** [comment]
> zh-CN


fine, i try to change 
![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/47288630/9b2163f9-087d-4655-bf1f-2c9327d25464)
 
I opened pdftool after clearing the cache and it's still default English。
Also I would like to use the nginx proxy but the subdomain can't open the page

**Comment by zallaevan** [comment]
> > zh-CN
> 
> fine, i try to change ![image](https://private-user-images.githubusercontent.com/47288630/325837863-9b2163f9-087d-4655-bf1f-2c9327d25464.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNDMxNDksIm5iZiI6MTcxNjI0Mjg0OSwicGF0aCI6Ii80NzI4ODYzMC8zMjU4Mzc4NjMtOWIyMTYzZjktMDg3ZC00NjU1LWJmMWYtMmM5MzI3ZDI1NDY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDIyMDcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyZTYyNDU5MTQ3NzVjN2U2MDRhY2M5NjQ5NjYzN2RkNTE3Y2VjOTc4OGQxNjg0MzZhNTZkZjFlNDNjY2UwY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zteb-pcVtjm6F7VkS6AYW2EeHe1PrbsscNmWEjj6Af4)
> 
> I opened pdftool after clearing the cache and it's still default English. Also, I would like to use the nginx proxy but the subdomain can't open the page

Maybe, after changing the configuration, try to restart the container on Docker via `sudo docker restart [container]`.
Additionally, you can test if it works by setting on your Docker Compose file or via the command the environmental variable `SYSTEM_DEFAULTLOCALE` equal to zh-CN.

Regarding the setup of the Nginx Reverse Proxy, I am not very versed in that regard, but I might assume you should add something like this to your active site configuration:

```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name stirling.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_app stirling-pdf;
        set $upstream_port 8080;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
}
```
All credit goes to [this guy](https://www.reddit.com/r/selfhosted/comments/1aj6rr1/comment/kp0wy4o/) here on Reddit, cheers mate!

祝你好运

**Comment by wintsa123** [comment]
I found that both problems are caused by caching
