### ISSUE TITLE
Issue on docker service / stack

### ISSUE THREAD

**Issue by carenswijaya01** [Stirling-Tools/Stirling-PDF#1127]
Hello sir, today i try to build your apps into local server, everything seems fine when i run this using 1 replica. But if i create 2 replica, it getting errors that stirling-pdf-DB.mv.db already use by other container (i mean another replica). So my latest solution is just deploy using 1 replica, i don't know if i have to scale it in the future, any suggestion?

**Comment by Ludy87** [comment]
I don't know of any application where two containers should run one and the same application and use the same file directory. What's the point of that? Could you explain that?

The reason why the database error occurs is that the database was opened by one instance, so the other can no longer open it.

**Comment by carenswijaya01** [comment]
In docker service, there is "scale" option, it just like built-in load balancer from docker, that create multi container with same network, image, and volume. For now, 1 replica should be enough, but i dont know in the future, will i need to scale it or not.

**Comment by Frooodle** [comment]
Currently we don't support this feature
We would need to migrate to dedicated database connection instead of our existing one within the same docker

**Comment by carenswijaya01** [comment]
So will it be a new feature on future?

And what if i need to scale in near? Should i create another service with different volume too?

**Comment by Frooodle** [comment]
Not planned for now
And yes different volume

**Comment by carenswijaya01** [comment]
Oh okay then, thanks for your answer
