### ISSUE TITLE
中文转换PDF为乱码

### ISSUE THREAD

**Issue by dong-dong6** [Stirling-Tools/Stirling-PDF#1136]
可以查看这个测试，中文转换为乱码
![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/73739354/247e434d-d9de-4ee9-ad19-73ecd7b919b2)
![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/73739354/02552543-957f-4708-8d41-8b1f1d7ac4ce)

**Comment by While4** [comment]
1. Please specify which feature you were using when you encountered the issue with converting to PDF.
2. Please provide a sample attachment.

Lastly, I suspect it is due to the lack of fonts.

**Comment by gepcel** [comment]
It mostly like have been fixed by #1139
