### ISSUE TITLE
Issue with ConfigInitializer not supporting the new OAuth

### ISSUE THREAD

**Issue by Frooodle** [Stirling-Tools/Stirling-PDF#1145]
ConfigInitializer  script is done badly and doesnt support 3 layered configs like the OAuth section. And has issues with tags of same name (two enabled etc)

Script should be fixed to allow better merging of yml files etc

**Comment by Ludy87** [comment]
The enable in oauth is actually not necessary, if oauth is activated, then the function is activated. Or have I thought incorrectly about that?

**Comment by Frooodle** [comment]
it could be done via a config presence check instead of a enable flag itself but due to how spring beans work it needs some conditional check

**Comment by Ludy87** [comment]
There should be clarity by checking the issuer, clientId and clientSecret

**Comment by Frooodle** [comment]
Fixed by splitting settings.yml and custom_settings.yml
Settings.yml is stirling-pdf settings
custom_settings.yml is any user entered settings such as server.port etc

**Comment by Frooodle** [comment]
Im a idiiot keeping this open

**Comment by Ludy87** [comment]
I think it can be closed -> #1284

https://github.com/Stirling-Tools/Stirling-PDF/pull/1284/files#diff-7bffa9b7042d2753de95baa6e66826e19c5116197bffc2df82c6e9be8f028a69
