### ISSUE TITLE
Flatten a pdf doesn't work at all

### ISSUE THREAD

**Issue by zaromarco** [Stirling-Tools/Stirling-PDF#1160]
Hi , i'm using the latest version of stirling-pdf , when i try to flatten a pdf with text selectable it gives me , very quickly, another pdf but again i can select text inside of it....it doesn't transform it into an image.
please let me know.

**Comment by Frooodle** [comment]
It flatterns in the term of making all inputs and forms flattened, it does not rasterize the pdf making it the text unselectable

**Comment by Frooodle** [comment]
I can work on adding this as a option

**Comment by zaromarco** [comment]
> It flatterns in the term of making all inputs and forms flattened, it does not rasterize the pdf making it the text unselectable

ah...no flatten is to make text unselectable converting it to an image , if you can add as an option it will be great.
one question: i don't understand the actual use of the flatten feature , why do i need to flatten an input and forms like these:
![immagine](https://github.com/Stirling-Tools/Stirling-PDF/assets/13431840/cb7623fd-7e83-4bad-9410-bcc33ed67fda)
