### ISSUE TITLE
Feature Suggestion for OCR

### ISSUE THREAD

**Issue by TheMattBin** [Stirling-Tools/Stirling-PDF#1162]
I think OCR feature is so far so good, some suggested PaddleOCR which is great as well. The following repo also do well for OCR, might consider as well,
https://github.com/VikParuchuri/surya?tab=readme-ov-file

**Comment by indigodelta** [comment]
+1 from me.  What we have now seems to be word recognition and , and make no sense of sentences or layout.  Improving this would be great.

**Comment by Frooodle** [comment]
Duplicate of #972
