### ISSUE TITLE
Issue with Docker build Stirling-PDF

### ISSUE THREAD

**Issue by mkamranmazhar** [Stirling-Tools/Stirling-PDF#1164]
Hello,

I'm trying to build docker image for Stirling-PDF.
When running the docker build command, I received the following error message:

![pdf askseotools](https://github.com/Stirling-Tools/Stirling-PDF/assets/106512746/bac07d50-3e18-4c49-b3df-ced8561005fe)

**Comment by Frooodle** [comment]
Removed the otf line from docker, please try pull and try again, not sure why it works on my system and github actions but not yours, but regardless to code isnt needed so now removed
