### ISSUE TITLE
How to change the port of 8080?

### ISSUE THREAD

**Issue by brisk21** [Stirling-Tools/Stirling-PDF#1173]
![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/17331991/84c35392-4484-4990-9bb3-5bf259e56b73)

I want to change the port of 8080

**Comment by bluestero** [comment]
So I also faced this issue, wanted to deploy on the host 0.0.0.0 and port 3000.
So from the directory where you are running the Stirling-PDF, it would create a configs directory there.
That would contain `configs.yml` and `custom_configs.yml`
In the `custom_configs.yml`, add:
```
server:
  host: 0.0.0.0 #(Can skip if don't want to add any).
  port: 3000 #(or whatever new port you want)
```

That's it, it would overwrite the config of the `configs.yml` at the application start, and deploy on the given host and port.
Hope it helps!

**Comment by t0mmili** [comment]
@Frooodle It would be really cool if these options were available as env vars, so it's easier to configure docker-compose.

**Comment by Frooodle** [comment]
If you are running in docker you have no need to change the port anyway since you can change the docker exposed port instead right?

**Comment by vdrover** [comment]
@Frooodle I have the same issue: when redirecting to a different port, nginx proxy fails.
