### ISSUE TITLE
Missing folders after installing Stirling-PDF on Raspberry 4 

### ISSUE THREAD

**Issue by kr1s3112** [Stirling-Tools/Stirling-PDF#1178]
Hello,

I just tried to install Stirling-PDF on my Raspberry Pi 4. I successfully installed docker, docker compose (without dash) and managed to do the docker compose up -d after creating the .yml file. All images get pulled (>660 MB) but afterwards the folders customFiles, extraConfigs and trainingData are missing. Consequently I cannot access Stirling-PDF in my browser. 

As I couldn't find any further info on the web: any suggestions what my mistake could be?

**Comment by Frooodle** [comment]
Anything in your docker logs which could help?

**Comment by kr1s3112** [comment]
Here is my docker-compose.yml:

services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    ports:
      - '6699:6699'
    volumes:
      - /root/stirling-pdf/trainingData:/usr/share/tesseract-ocr/4.00/tessdata
      - /root/stirling-pdf/extraConfigs:/configs
      - /root/stirling-pdf/customFiles:/customFiles/
    environment:
      - DOCKER_ENABLE_SECURITY=false
    restart: always

Logs:

pi@raspberry:~ $ docker logs 3c8c249733aa
Copying original files without overwriting existing files
cp: can't stat '/usr/share/tesseract-ocr/4.00/tessdata/*': No such file or directory
Running Stirling PDF with DOCKER_ENABLE_SECURITY=false and VERSION_TAG=0.23.1
Setting permissions and ownership for necessary directories...
Picked up JAVA_TOOL_OPTIONS:  -XX:MaxRAMPercentage=75
 ____ _____ ___ ____  _     ___ _   _  ____       ____  ____  _____
/ ___|_   _|_ _|  _ \| |   |_ _| \ | |/ ___|     |  _ \|  _ \|  ___|
\___ \ | |  | || |_) | |    | ||  \| | |  _ _____| |_) | | | | |_
 ___) || |  | ||  _ <| |___ | || |\  | |_| |_____|  __/| |_| |  _|
|____/ |_| |___|_| \_\_____|___|_| \_|\____|     |_|   |____/|_|
Powered by Spring Boot 3.2.4
16:38:45.542 [main] INFO  s.software.SPDF.SPdfApplication - Starting SPdfApplication v0.23.1 using Java 17.0.11 with PID 11 (/app.jar started by stirlingpdfuser in /)
16:38:45.559 [main] INFO  s.software.SPDF.SPdfApplication - No active profile set, falling back to 1 default profile: "default"
16:38:55.373 [main] INFO  o.s.b.w.e.tomcat.TomcatWebServer - Tomcat initialized with port 8080 (http)
16:38:55.429 [main] INFO  o.a.coyote.http11.Http11NioProtocol - Initializing ProtocolHandler ["http-nio-8080"]
16:38:55.441 [main] INFO  o.a.catalina.core.StandardService - Starting service [Tomcat]
16:38:55.442 [main] INFO  o.a.catalina.core.StandardEngine - Starting Servlet engine: [Apache Tomcat/10.1.19]
16:38:55.692 [main] INFO  o.a.c.c.C.[Tomcat].[localhost].[/] - Initializing Spring embedded WebApplicationContext
16:38:55.700 [main] INFO  o.s.b.w.s.c.ServletWebServerApplicationContext - Root WebApplicationContext: initialization completed in 9591 ms
16:38:56.842 [main] INFO  s.software.SPDF.SPdfApplication - Running configs ApplicationProperties [security=Security [enableLogin=false, initialLogin=null,  csrfDisabled=true], system=System [defaultLocale=en-US, googlevisibility=false, rootURIPath=null, customStaticFilePath=null, maxFileSize=null, enableAlphaFunctionality=false, showUpdate=true, showUpdateOnlyAdmin=false], ui=null, endpoints=Endpoints [toRemove=[], groupsToRemove=[]], metrics=Metrics [enabled=true], automaticallyGenerated=null, autoPipeline=null]
16:38:56.899 [main] INFO  s.s.S.config.EndpointConfiguration - Disabling pdf-to-book
16:38:56.901 [main] INFO  s.s.S.config.EndpointConfiguration - Disabling book-to-pdf
16:39:02.433 [main] INFO  o.s.b.a.e.web.EndpointLinksResolver - Exposing 1 endpoint(s) beneath base path '/actuator'
16:39:02.819 [main] INFO  o.a.coyote.http11.Http11NioProtocol - Starting ProtocolHandler ["http-nio-8080"]
16:39:02.954 [main] INFO  o.s.b.w.e.tomcat.TomcatWebServer - Tomcat started on port 8080 (http) with context path ''
16:39:03.104 [main] INFO  s.software.SPDF.SPdfApplication - Started SPdfApplication in 20.938 seconds (process running for 25.437)
16:39:04.357 [main] INFO  s.software.SPDF.SPdfApplication - Stirling-PDF Started.
16:39:04.359 [main] INFO  s.software.SPDF.SPdfApplication - Navigate to http://localhost:8080

pi@raspberry:~/stirling-pdf $ docker compose logs
stirling-pdf-1  | Copying original files without overwriting existing files
stirling-pdf-1  | cp: can't stat '/usr/share/tesseract-ocr/4.00/tessdata/*': No such file or directory
stirling-pdf-1  | Running Stirling PDF with DOCKER_ENABLE_SECURITY=false and VERSION_TAG=0.23.1
stirling-pdf-1  | Setting permissions and ownership for necessary directories...
stirling-pdf-1  | Picked up JAVA_TOOL_OPTIONS:  -XX:MaxRAMPercentage=75
stirling-pdf-1  |  ____ _____ ___ ____  _     ___ _   _  ____       ____  ____  _____
stirling-pdf-1  | / ___|_   _|_ _|  _ \| |   |_ _| \ | |/ ___|     |  _ \|  _ \|  ___|
stirling-pdf-1  | \___ \ | |  | || |_) | |    | ||  \| | |  _ _____| |_) | | | | |_
stirling-pdf-1  |  ___) || |  | ||  _ <| |___ | || |\  | |_| |_____|  __/| |_| |  _|
stirling-pdf-1  | |____/ |_| |___|_| \_\_____|___|_| \_|\____|     |_|   |____/|_|
stirling-pdf-1  | Powered by Spring Boot 3.2.4
stirling-pdf-1  | 16:38:45.542 [main] INFO  s.software.SPDF.SPdfApplication - Starting SPdfApplication v0.23.1 using Java 17.0.11 with PID 11 (/app.jar started by stirlingpdfuser in /)
stirling-pdf-1  | 16:38:45.559 [main] INFO  s.software.SPDF.SPdfApplication - No active profile set, falling back to 1 default profile: "default"
stirling-pdf-1  | 16:38:55.373 [main] INFO  o.s.b.w.e.tomcat.TomcatWebServer - Tomcat initialized with port 8080 (http)
stirling-pdf-1  | 16:38:55.429 [main] INFO  o.a.coyote.http11.Http11NioProtocol - Initializing ProtocolHandler ["http-nio-8080"]
stirling-pdf-1  | 16:38:55.441 [main] INFO  o.a.catalina.core.StandardService - Starting service [Tomcat]
stirling-pdf-1  | 16:38:55.442 [main] INFO  o.a.catalina.core.StandardEngine - Starting Servlet engine: [Apache Tomcat/10.1.19]
stirling-pdf-1  | 16:38:55.692 [main] INFO  o.a.c.c.C.[Tomcat].[localhost].[/] - Initializing Spring embedded WebApplicationContext
stirling-pdf-1  | 16:38:55.700 [main] INFO  o.s.b.w.s.c.ServletWebServerApplicationContext - Root WebApplicationContext: initialization completed in 9591 ms
stirling-pdf-1  | 16:38:56.842 [main] INFO  s.software.SPDF.SPdfApplication - Running configs ApplicationProperties [security=Security [enableLogin=false, initialLogin=null,  csrfDisabled=true], system=System [defaultLocale=en-US, googlevisibility=false, rootURIPath=null, customStaticFilePath=null, maxFileSize=null, enableAlphaFunctionality=false, showUpdate=true, showUpdateOnlyAdmin=false], ui=null, endpoints=Endpoints [toRemove=[], groupsToRemove=[]], metrics=Metrics [enabled=true], automaticallyGenerated=null, autoPipeline=null]
stirling-pdf-1  | 16:38:56.899 [main] INFO  s.s.S.config.EndpointConfiguration - Disabling pdf-to-book
stirling-pdf-1  | 16:38:56.901 [main] INFO  s.s.S.config.EndpointConfiguration - Disabling book-to-pdf
stirling-pdf-1  | 16:39:02.433 [main] INFO  o.s.b.a.e.web.EndpointLinksResolver - Exposing 1 endpoint(s) beneath base path '/actuator'
stirling-pdf-1  | 16:39:02.819 [main] INFO  o.a.coyote.http11.Http11NioProtocol - Starting ProtocolHandler ["http-nio-8080"]
stirling-pdf-1  | 16:39:02.954 [main] INFO  o.s.b.w.e.tomcat.TomcatWebServer - Tomcat started on port 8080 (http) with context path ''
stirling-pdf-1  | 16:39:03.104 [main] INFO  s.software.SPDF.SPdfApplication - Started SPdfApplication in 20.938 seconds (process running for 25.437)
stirling-pdf-1  | 16:39:04.357 [main] INFO  s.software.SPDF.SPdfApplication - Stirling-PDF Started.
stirling-pdf-1  | 16:39:04.359 [main] INFO  s.software.SPDF.SPdfApplication - Navigate to http://localhost:8080

Missing rights to create the folders?

**Comment by Frooodle** [comment]
your compose file is using paths from about 1 year ago! please use latest compose examples

**Comment by Frooodle** [comment]
/usr/share/tesseract-ocr/4.00/tessdata stopped existing long time about

as your log showed ``cp: can't stat '/usr/share/tesseract-ocr/4.00/tessdata/*': No such file or directory``
