### ISSUE TITLE
Using the PDF rotation function to repeatedly add PDF display errors

### ISSUE THREAD

**Issue by yusanb** [Stirling-Tools/Stirling-PDF#1182]
![_20240507203726](https://github.com/Stirling-Tools/Stirling-PDF/assets/100070053/4d648fd4-4a8e-40cc-b425-85d0f4167bb8)

**Comment by jimdouk** [comment]
Hello!
I find this issue very interesting and essential. May I take a look on this open issue?

**Comment by Frooodle** [comment]
Sure
