### ISSUE TITLE
 Converting Word to PDF failed and garbled characters appeared.

### ISSUE THREAD

**Issue by llllggggzzzz** [Stirling-Tools/Stirling-PDF#1189]
I have added LANGS correctly. 
but still failed
![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/116811192/505da06a-fa43-4d6c-b087-69fdccdf6c83)
![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/116811192/e3cf968d-32b8-4ab9-afff-49903b08155e)
Is it because of insufficient font support? In the Word document I used italics.

**Comment by Frooodle** [comment]
can you show your container startup logs and also run the command

``apk list --installed | grep font``

**Comment by binsir1** [comment]
> can you show your container startup logs and also run the command
> 
> `apk list --installed | grep font`

I also have the same situation, and it’s still the same after running this command
![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/99531497/4c8f866a-5124-4624-b528-a34d7ce92c76)

**Comment by Frooodle** [comment]
Can you show the output of the command *

**Comment by binsir1** [comment]
![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/99531497/59ffd3b5-921b-4b72-a311-960ffc91a994)

**Comment by Frooodle** [comment]
Issue still ongoing?
