### ISSUE TITLE
Setting page info while resizing or cropping page

### ISSUE THREAD

**Issue by dev-cb** [Stirling-Tools/Stirling-PDF#1194]
Is it possible with Stirling-PDF to redefine the MediaBox, CropBox, BleedBox, TrimBox and ArtBox?

Possible use case:

Having a 40x50cm poster template PDF. This poster should be printed 80x100cm, so with the scale factor 2.
But the tricky part is the bleed: The printer only accepts a 80x100cm sized PDF document with 5mm bleed on each side.

Any idea leads on this? Thank you!

**Comment by Frooodle** [comment]
Not currently

**Comment by Frooodle** [comment]
This is very niche of a usecase suitable more for a PDF API not a PDF application 
Will be closing for now!
