### ISSUE TITLE
docker版 版本显示和镜像版本不一致(The docker version display is inconsistent with the image version)

### ISSUE THREAD

**Issue by Firfr** [Stirling-Tools/Stirling-PDF#1198]
docker版 版本显示和镜像版本不一致
镜像版本 0.23.1
网页端显示版本 0.21.0
// 机翻
The docker version display is inconsistent with the image version
Mirror version 0.23.1
The web page shows version 0.21.0

<img width="563" alt="PixPin_2024-05-12_21-25-05" src="https://github.com/Stirling-Tools/Stirling-PDF/assets/93274140/6af27bd2-39c9-4915-aa9f-af0479ac6d54">
<img width="376" alt="PixPin_2024-05-12_21-22-00" src="https://github.com/Stirling-Tools/Stirling-PDF/assets/93274140/5cfc6c8c-5025-4f6d-8c04-151385cfce0f">

**Comment by Frooodle** [comment]
Im not sure if that is correct... I am seeing versions fine in all public instances of 0.23.1 
Are you sure you are running the image and its not cached etc

**Comment by Firfr** [comment]
应该不是缓存的问题,启动谷歌浏览器的无痕模式,在打开网页,按下f12,提示如下:
但是我容器的部署镜像是 frooodle/s-pdf:0.23.1
请问公开实例也是使用的docker部署的吗?采用的是那个镜像?我再试试
// Machine translation
It should not be a cache problem, launch Google Chrome Indent mode, in the open web page, press f12, the prompt is as follows:
But the deployment image for my container is frooodle/s-pdf:0.23.1
Is the public instance also deployed with docker? Which mirror image is used? I'll try again
![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/93274140/1b9a9456-8f5f-49fd-89fd-dcf03fa61bb4)

**Comment by Firfr** [comment]
现在好了,是我部署的有问题
That's it. I had a problem with my deployment
