### ISSUE TITLE
Box shows Update available but there is nothing to update 

### ISSUE THREAD

**Issue by Dtrieb** [Stirling-Tools/Stirling-PDF#1202]
The Box show that there is a Update available but if I look about, and on Github there is now newer version.

![chrome_2024-05-13_12-21-39](https://github.com/Stirling-Tools/Stirling-PDF/assets/3650284/e0790e92-b279-4c23-afce-3c87a9e98923)

**Comment by Frooodle** [comment]
should be fixed? Let me know, and if not fixed please share your f12 console log

**Comment by Dtrieb** [comment]
> should be fixed? Let me know, and if not fixed please share your f12 console log

Fixed for me in App-Version: 0.24.6
