### ISSUE TITLE
Helm chart queries non-existent tag from docker resulting in "ImagePullBackOff"

### ISSUE THREAD

**Issue by patrickfenn** [Stirling-Tools/Stirling-PDF#1209]
Currently, the helm chart will try to query version 0.23.2 from docker:

>   Normal   Scheduled  3m20s                 default-scheduler  Successfully assigned stirling-pdf/stirling-pdf-stirling-pdf-chart-77475b4959-7464f to services2
>   Normal   Pulling    117s (x4 over 3m20s)  kubelet            Pulling image "frooodle/s-pdf:0.23.2"
>   Warning  Failed     116s (x4 over 3m19s)  kubelet            Failed to pull image "frooodle/s-pdf:0.23.2": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/frooodle/s-pdf:0.23.2": failed to resolve reference "docker.io/frooodle/s-pdf:0.23.2": docker.io/frooodle/s-pdf:0.23.2: not found
>   Warning  Failed     116s (x4 over 3m19s)  kubelet            Error: ErrImagePull
>   Warning  Failed     105s (x6 over 3m19s)  kubelet            Error: ImagePullBackOff
>   Normal   BackOff    94s (x7 over 3m19s)   kubelet            Back-off pulling image "frooodle/s-pdf:0.23.2"

I managed to fix it by going into the deployment.yaml file and assigning "latest" as the tag to the image. It appears that this file is returning the wrong value:

templates/_helpers.tplf

**Comment by sharifm-informatica** [comment]
Easier to add a tag to your custom `values.yaml` file. 

The real issue is that the chart source here is updated correctly automatically with each version.  The chart on docker hub is not updated regularly.

**Comment by Frooodle** [comment]
should be good
