### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by venuswjx** [Stirling-Tools/Stirling-PDF#1210]
在执行任务: docker build --pull --rm -f "Dockerfile" -t stirlingpdf:latest "." 

[+] Building 3.4s (9/10)                                                                                                                                                   docker:default
 => [internal] load build definition from Dockerfile                                                                                                                                 0.0s
 => => transferring dockerfile: 2.38kB                                                                                                                                               0.0s
 => [internal] load metadata for docker.io/library/alpine:20240329                                                                                                                   3.3s
 => [internal] load .dockerignore                                                                                                                                                    0.0s
 => => transferring context: 2B                                                                                                                                                      0.0s
 => [1/6] FROM docker.io/library/alpine:20240329@sha256:e31c3b1cd47718260e1b6163af0a05b3c428dc01fa410baf72ca8b8076e22e72                                                             0.0s
 => [internal] load build context                                                                                                                                                    0.0s
 => => transferring context: 1.30kB                                                                                                                                                  0.0s
 => CACHED [2/6] COPY scripts /scripts                                                                                                                                               0.0s
 => CACHED [3/6] COPY pipeline /pipeline                                                                                                                                             0.0s
 => CACHED [4/6] COPY src/main/resources/static/fonts/*.ttf /usr/share/fonts/opentype/noto/                                                                                          0.0s
 => ERROR [5/6] COPY build/libs/*.jar app.jar                                                                                                                                        0.0s
------
 > [5/6] COPY build/libs/*.jar app.jar:
------
Dockerfile:9
--------------------
   7 |     COPY src/main/resources/static/fonts/*.ttf /usr/share/fonts/opentype/noto/
   8 |     #COPY src/main/resources/static/fonts/*.otf /usr/share/fonts/opentype/noto/
   9 | >>> COPY build/libs/*.jar app.jar
  10 |
  11 |     ARG VERSION_TAG
--------------------
ERROR: failed to solve: lstat /var/lib/docker/tmp/buildkit-mount4002336963/build/libs: no such file or directory

**Comment by Frooodle** [comment]
https://github.com/Stirling-Tools/Stirling-PDF/issues/1005#issuecomment-2028837450
