### ISSUE TITLE
Login is invalid

### ISSUE THREAD

**Issue by jojo100** [Stirling-Tools/Stirling-PDF#1220]
I had set docker-compose environment:
      - DOCKER_ENABLE_SECURITY:"true"
      - SECURITY_ENABLELOGIN:"true"
  & set /configs/setting.yml
security:
  enableLogin: true # set to 'true' to enable login
  csrfDisabled: true
  loginAttemptCount: 5 # lock user account after 5 tries
  loginResetTimeMinutes : 120 # lock account for 2 hours after x attempts

but when i start up docker,the log shows:
**Running Stirling PDF with DOCKER_ENABLE_SECURITY=false and VERSION_TAG=alpha**
the app running without login,i read all the issues,it seems no the same question

**Comment by Frooodle** [comment]
Login not supported with alpha tag
Must use a versioned tag
