### ISSUE TITLE
Error during template parsing in Merge PDF's

### ISSUE THREAD

**Issue by Wav3y** [Stirling-Tools/Stirling-PDF#1235]
Hey guys,

First of all, Stirling PDF is nothing short of AMAZING!

I have just got it set up on a docker container and everything seems to be in working order, except the Merge PDF tool for which I keep getting the following issue:

Error: 500 Internal Server Error An error happened during template parsing (template: "class path resource [templates/merge-pdfs.html]" - line 15, col 13) for path: /merge-pdfs

Any ideas on what's happening here / how I can access the template path and check if something's happening there? 

![error template parsing](https://github.com/Stirling-Tools/Stirling-PDF/assets/78494690/7a9e00ed-19d5-48fd-979f-ab29a5b67a6f)

Thanks!

**Comment by Frooodle** [comment]
Ahh I see issue thanks for this, was introduced in latest release 4 hours ago

**Comment by Frooodle** [comment]
fixed in 0.24.2 ! thanks

**Comment by Wav3y** [comment]
> fixed in 0.24.2 ! thanks

Thank you, working perfect on the new update
