### ISSUE TITLE
Option for SSO only login

### ISSUE THREAD

**Issue by seang96** [Stirling-Tools/Stirling-PDF#1238]
I'd prefer to limit user authentication to only be SSO so an option to disable the sign in form and only show "Login via Single Sign-on". This would make it less confusing on my user's view since SSO is the only login option I'll provide.

Thank you for the awesome work on this!

**Comment by guyke01** [comment]
I'd tink it is more prefered to have no button and automatic redirect as requested in #1232.

**Comment by seang96** [comment]
I imagine there would be some cases where an automatic redirect would not be preferred as well such as in the future there is support for multiple SSO providers and the user "consenting" to use it by selecting the provider themselves.

**Comment by guyke01** [comment]
From an enterprise perspective it's more common to have auto redirection as per organization a instance of a application will be running.

Therefore feature request to create the auto redirect when enabled in the environment settings. With this option you can choose between auto redirect or not.
