### ISSUE TITLE
Landing page Style

### ISSUE THREAD

**Issue by andercard0** [Stirling-Tools/Stirling-PDF#1241]
Hi

I would like to know how would i return the lading page how it was before this:
![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/43047877/77918cb3-51ca-4328-b1ed-d08521f9164e)

Perssonally, I prefer this style

![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/43047877/5b58d53e-f9d3-4f34-89f6-f0fe5902616c)

For me it's a bit confusing to go in this menu, I'd prefer the way it was before this, is it possible ? 

![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/43047877/52e7f19d-be60-458b-8a8f-3de765bc83db)

**Comment by Frooodle** [comment]
UI should look like this
https://stirlingpdf.io/

**Comment by Frooodle** [comment]
might be a cache issue or something similar, can you press f12 and right click the refresh icon and do hard reload and clear cache?
![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/77850077/3fc30c9e-1848-4cff-a9e3-db087f59b525)

**Comment by Frooodle** [comment]
Should be fixed in latest 0.24.3 release to avoid cache issue, let me know if it works

**Comment by andercard0** [comment]
> Should be fixed in latest 0.24.3 release to avoid cache issue, let me know if it works

Ah, much better!
To be honest, Just made a clean install and yeah looks good!

Thank you, also, there is a site which is way more convenient when a client of mine asks for a free trusted solution, good to know tho. Thanks again.

![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/43047877/0f9228a8-33f4-4965-b7f7-3ea3e103aeb9)
