### ISSUE TITLE
Using multiple SSO providers

### ISSUE THREAD

**Issue by Ludy87** [Stirling-Tools/Stirling-PDF#1242]
- [x] implementation
- [x] backwards compatibility
- [x] use with Google
- [x] use with Keycloak
- [x] use with Github
- [x] Login screen

**Comment by Frooodle** [comment]
LDAP next? ;p

**Comment by kabaga** [comment]
> LDAP next? ;p

Any plans on adding LDAP?

**Comment by Frooodle** [comment]
Not yet 

Yes but not yet, via survey we have had a lot of support for a business version, might have LDAP under that instead

**Comment by VincentSC** [comment]
What should be the time-out for oAuth? It looks like an hour or so. Can it be configured?
