### ISSUE TITLE
multi-tools create bigger file than single merge tool

### ISSUE THREAD

**Issue by kintaro1981** [Stirling-Tools/Stirling-PDF#1248]
I'm using multi-tool to merge and rotate a "text pdf" of 400 pages with a single page "image-pdf".

If I use the single merge tool I get a file size like the sum of the size of the merged files.
If I use the multi-tools the size is much bigger of the sum of the size of the merged files.

pdf examples:
input:
[many_pages_only_text.pdf](https://github.com/Stirling-Tools/Stirling-PDF/files/15375315/many_pages_only_text.pdf)
[single_page_image.pdf](https://github.com/Stirling-Tools/Stirling-PDF/files/15375316/single_page_image.pdf)
output:
[merged_with_single_tool.pdf](https://github.com/Stirling-Tools/Stirling-PDF/files/15375312/merged_with_single_tool.pdf)
[merged_with_multi-tool.pdf](https://github.com/Stirling-Tools/Stirling-PDF/files/15375314/merged_with_multi-tool.pdf)

I tried 23.1 and latest the 24.3

**Comment by Frooodle** [comment]
This is due to the backend PDF tooling being different for merge vs multi-tool
Not a bug just how they handle PDFs
