### ISSUE TITLE
Button in wrong Language

### ISSUE THREAD

**Issue by t71rs** [Stirling-Tools/Stirling-PDF#1260]
# Wrong Language in Button

The button to open the File Explorer to add Files to most of the Operations is in the wrong Language. I have Stirling Pdf set to English, but the Button is in German which is the System Language of my Laptop. The following screenshot shows the button when using "Merge".

![GithubBild](https://github.com/Stirling-Tools/Stirling-PDF/assets/166131967/31ef2d2d-b169-4b20-8d91-456e277303ba)

I could start working on this if you approve.

**Comment by Frooodle** [comment]
Yes please start working!
