### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by FormadorLar** [Stirling-Tools/Stirling-PDF#1264]
This is not really an "issue" (i hope), but somtimes i have docx files with non-defaults fonts. The converted PDF doesn't seem to have those fonts, instead they are being replaced with Arial or something like that. How can i add fonts, at least?.. or.. (maybe in the future) were fonts autodetected and autodownloaded from free sites like dafont and similar, that would really help a lot! I already love your project and hope you keep developing to have a serious Adobe Pro alternative.

**Comment by Frooodle** [comment]
the backend uses a CLI for libreOffice so the fonts and such are not actually part of stirling-pdf
