### ISSUE TITLE
Feature Request: Improved PDF Compare

### ISSUE THREAD

**Issue by pholcroft** [Stirling-Tools/Stirling-PDF#1290]
I have a few ideas to improve PDF Compare.

1. Allow export of the new PDF with the different text highlighted.
![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/4210486/b7323f7e-4175-4f9a-bdf7-309ed8ce3be7)
Example: https://www.ilovepdf.com/compare-pdf
2. Add a hover tooltip to show the difference between the exported version and the alternative.
Example: https://evermap.com/Tutorial_ABM_CreateTooltipsViaTextSearch.asp
3. Allow the export of either the old, or new PDF.
4. Allow ignoring minor differences by %.
5. Add quick links to the next difference.
6. Allow highlight colour selection.
![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/4210486/0eb08839-3355-4132-919c-8aa32f33d6c0)
7. Allow viewing of the PDF's side-by-side.

Although there are other PDF comparison tools, I find them lacking, there is an opportunity to create a better solution here.
Ilovepdf is the best I've found, but there's no way to choose if you get the old or new version, or if there is, it doesn't always work.
It also doesn't offer tooltips.

You could add these features gradually. I've put them in my order of preference. Even just the first one would be a huge help, 1 and 2 would beat the competition.

The use case I have for these is comparing new versions of PDF's when there is an update. e.g. user manuals/systems requirements/release notes.
I like to share the highlighted differences, as I know otherwise nobody would bother to read them.

**Comment by ShawnJohnston** [comment]
Completed item number 6. Contributing guide says I have to comment here and wait for approval before sending a PR.

Items 1 & 3:  These items require the page's code to be able to edit the input PDF files directly. At this time, comparePDFs() only extracts raw text from PDF files, so there's no output PDF files to export.
Item 7: I attempted to display PDF's onto the page using <embed>, <object>, and <iframe>, but the project config is set to deny X-Frame-Options, so I was not able to do it.

![FireShot Capture 005 - Stirling PDF - Compare - localhost](https://github.com/Stirling-Tools/Stirling-PDF/assets/44795446/6a6af809-8e6d-4f57-a6ca-15ecf47d65e7)
