### ISSUE TITLE
Missing translation for Chinese

### ISSUE THREAD

**Issue by wai4y** [Stirling-Tools/Stirling-PDF#1291]
Hi thanks for the wonderful tool, I just noticed there are some pages not been well translated when shown in Chinese, if possible, I can help to add the translation for these pages.

![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/9801268/3d4b9972-3d87-4427-8fb5-87a4a200767d)
![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/9801268/d4fcca13-2726-4be4-b9f2-dcddd4c03164)

**Comment by Frooodle** [comment]
https://github.com/Stirling-Tools/Stirling-PDF/tree/main/src%2Fmain%2Fresources

All the messages properties here are the translations

**Comment by Frooodle** [comment]
You can raise pr
