### ISSUE TITLE
Why does the color change after compression?

### ISSUE THREAD

**Issue by pipuwong** [Stirling-Tools/Stirling-PDF#1310]
The source file is srgb, and the color changes after compression.
I don't want to change its color, I just want to make its size smaller,So I clicked the compress button,Strength is 1,Finally, he actually changed color, which was not the color I wanted.
![CleanShot 2024-05-28 at 14 24 15](https://github.com/Stirling-Tools/Stirling-PDF/assets/53525622/31d5d989-07a4-4d5d-b8f9-e7db5bc8454c)

**Comment by Frooodle** [comment]
@pipuwong  Sorry for late reply, can you provide any example file to reproduce this? Closing this ticket in meantime but happy to reopen if you can get example
