### ISSUE TITLE
view-pdf added text removes first line

### ISSUE THREAD

**Issue by Schauflerin** [Stirling-Tools/Stirling-PDF#1312]
Added Text via view-pdf removes first line if you click on print.
I can workaround if my first line is blank.  But only when its not edited text.

**Comment by Frooodle** [comment]
Sorry for late reply, Does this still happen on latest version? closing ticket for now but happy to re-open if you can still reproduce

**Comment by Schauflerin** [comment]
We are now on 0.29.0. It was resolved 1 or 2 updates after opening my issue. I'm sorry for not responding.
