### ISSUE TITLE
Getting Error on login when using Zitadel for SSO

### ISSUE THREAD

**Issue by thinkbig1979** [Stirling-Tools/Stirling-PDF#1315]
I've set up SSO using Zitadel and set up all the parameters, including the scope parameter in my compose file.
(Side note: The scope parameter is not shown in the OIDC chapter of the online docs yet, so I did not set that parameter initially, but I got an error on trying to log in telling me that the scope had not been defined for the client, so I searched and found the scope parameter, added it to my compose config and then that error disappeared).

When I now click on long in with SSO, I get an error, saying:
"The requested redirect_uri is missing in the client configuration. If you have any questions, you may contact the administrator of the application."

![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/18327273/b466d55a-d1a7-44ae-a0a3-c6652030f9ea)

**Comment by Ludy87** [comment]
Log in to your project at Zitadel and go to the project. Select your APPLICATIONS and go to REDIRECT SETTINGS and add the Redirect URI

**Comment by thinkbig1979** [comment]
I'd already done that before I tried to log in.
See below, I believe that's correct. I've just used the base url for the logout redirect, as I could not find any mentnion of a logout redirect url in the documentation.
![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/18327273/4e9f762f-8af4-4c82-b946-1ec36b8d45d6)

**Comment by Ludy87** [comment]
It should look something like this:
http://localhost:8080/login/oauth2/code/oidc

**Comment by thinkbig1979** [comment]
I've added the /login/ into the url, and tried removing the other option, as well as having them both in, the issue persists. 
![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/18327273/5bf23ba6-55e4-4bbb-9e8a-1a84963edb55)

**Comment by Frooodle** [comment]
StirlingTools website is very out of date and is user updated at moment as we dont have time to update ourselves (we dont get funding so we do stirling-pdf in our spare time)
Every doc page has a edit button which you can hit to take you to github to make any changes yourself
If you want you can raise a PR for any changes you think would be good
https://github.com/Stirling-Tools/Stirling-Tools.github.io/blob/main/docs/Advanced%20Configuration/Single%20Sign-On%20Configuration.md

**Comment by thinkbig1979** [comment]
Totally understood, thanks for your help on this, and let me see what I can do on the docs side. :-)
