### ISSUE TITLE
Czech language dont show diacrictics

### ISSUE THREAD

**Issue by QWJETAK** [Stirling-Tools/Stirling-PDF#1316]
Hi, I have problem with czech language which doesnt show diacritics, instead showing random characters.

What it shows: Va?e lok�ln? hostovan� jednotn� kontaktn� m�sto pro v?echny va?e pot?eby ve form�tu PDF
What it should be: Vaše lokální hostované jednotné kontaktní místo pro všechny vaše potřeby ve formátu PDF

**Comment by Ludy87** [comment]
This should be fixed here: https://github.com/Stirling-Tools/Stirling-PDF/commit/c2179ccd63bd476aeeb2b5e265a28ac3147b5455 Which version are you using?

**Comment by Frooodle** [comment]
> This should be fixed here: [c2179cc](https://github.com/Stirling-Tools/Stirling-PDF/commit/c2179ccd63bd476aeeb2b5e265a28ac3147b5455) Which version are you using?

not in a release yet, about to make it

**Comment by Frooodle** [comment]
should be fixed in 0.25.0

**Comment by QWJETAK** [comment]
It´s working. Thank you.
