### ISSUE TITLE
Docker Container not starting after update 0.25.0

### ISSUE THREAD

**Issue by guyke01** [Stirling-Tools/Stirling-PDF#1320]
With the new update 0.25.0 multiple oAuth2 clients is introduced. I'm using Authentik and have the following Docker Config:

```
DOCKER_ENABLE_SECURITY: "true"
SECURITY_ENABLELOGIN: "true"
SECURITY_OAUTH2_ENABLED: "true"
SECURITY_OAUTH2_AUTOCREATEUSER: "true"
SECURITY_OAUTH2_ISSUER: "https://<REDACTED>/application/o/stirling-pdf/"
SECURITY_OAUTH2_CLIENTID: "<REDACTED>"
SECURITY_OAUTH2_CLIENTSECRET: "<REDACTED>"
```

The example config in this repository is not changed after this update, but i'm getting the following error:
`05:03:39.087 [main] ERROR s.s.S.c.s.SecurityConfiguration - At least one OAuth2 provider must be configured`

Is there a config change for the Docker container as the mutli oAuth2 is introduced so a other provider keeps working besides the providers that are added in #1284

**Comment by Ludy87** [comment]
i missing:

```
      SECURITY_OAUTH2_USEASUSERNAME: "email"
      SECURITY_OAUTH2_SCOPES: "openid, profile, email"
      SECURITY_OAUTH2_PROVIDER: "keycloak"
```

add it, if necessary you should adapt it to your or your provider's needs

**Comment by guyke01** [comment]
Thanks, that was it! It is starting now and SSO is working.

**Comment by ollioddi** [comment]
How did you actually solve this? I experience the exact same after updating, breaking my Authentik integration.

Docker environment (Ansible Jinja template)
```
      DOCKER_ENABLE_SECURITY: "true"
      SECURITY_ENABLE_LOGIN: "true"
      SECURITY_OAUTH2_ENABLED: "true"
      SECURITY_OAUTH2_AUTOCREATEUSER: "true"
      SECURITY_OAUTH2_ISSUER: "{{ pdf_oauth_issuer }}"
      SECURITY_OAUTH2_CLIENTID: "{{ pdf_oauth_client_id }}"
      SECURITY_OAUTH2_CLIENTSECRET: "{{ pdf_oauth_client_secret }}"
      SECURITY_OAUTH2_SCOPES: "openid, profile, email"
      SECURITY_OAUTH2_PROVIDER: "keycloak"
```

Also tried changing and removing the provider, since i do not use keycloak. Worked wonderfully before.

```
15:20:56.042 [main] ERROR s.s.S.c.s.SecurityConfiguration - At least one OAuth2 provider must be configured
```

**Comment by Ludy87** [comment]
@ollioddi `SECURITY_OAUTH2_USEASUSERNAME: "email" `is missing

**Comment by ollioddi** [comment]
@Ludy87 yes I found out. Thanks a lot though, I can see my edit wasn't quite clear.
