### ISSUE TITLE
Error when trying to use compress function

### ISSUE THREAD

**Issue by xillibit** [Stirling-Tools/Stirling-PDF#1323]
I'am using the Stirling-PDF.exe in version 0.25.0 on Windows 11, when i want use the compress function i have this error : 

![Capture d'écran 2024-05-29 133921](https://github.com/Stirling-Tools/Stirling-PDF/assets/876395/b1444f15-d491-4077-84d5-111a99ff0668)

**Comment by Frooodle** [comment]
Ahh compress is not supported by .exe, it should be hidden from navbar
(its hidden in tool section and main menu but not navbar i forgot! thanks for raising this)

**Comment by xillibit** [comment]
ok understood
