### ISSUE TITLE
[SOLVED] Doesn't work with files larger than 100MB?

### ISSUE THREAD

**Issue by vultux** [Stirling-Tools/Stirling-PDF#1325]
Hi!

First thanks for the Stirling PDF, fantastic tool!

I'm having problems with PDFs larger than 100MB for any function, I tried to use split but it gave the error HTTP error status: 413.
![erro_413](https://github.com/Stirling-Tools/Stirling-PDF/assets/882781/48c6b2da-005d-44cb-8793-3258560620b9)

I tested it with a 93MB PDF and it worked.

Is there a way to configure it to allow you to work with large PDF files?

**Comment by Frooodle** [comment]
This will be your reverse proxy configuration most likely, you should see other issue tickets for same issue raised you can use as reference for possible fixes

**Comment by vultux** [comment]
> This will be your reverse proxy configuration most likely, you should see other issue tickets for same issue raised you can use as reference for possible fixes
Thank you!

The problem was the CloudFlare reverse proxy, I only left the NGINX reverse proxy and it worked.
