### ISSUE TITLE
Can't select the Draw tool in View 

### ISSUE THREAD

**Issue by smeredith** [Stirling-Tools/Stirling-PDF#1328]
When I click the Draw button in View, nothing happens. If the Text tool is selected, it stays selected, so I know that at least one of the buttons works.

<img width="149" alt="image" src="https://github.com/Stirling-Tools/Stirling-PDF/assets/6439539/6b1affef-e8e6-420b-9eb3-0426c551d1a7">

I tried this on the default document that opens in View, and with several of my own documents.
I tried Edge and Chrome on Windows, Chrome on ChromeOS, and Firefox on Linux.

App version is  0.25.0.

**Comment by friishon** [comment]
I have the same problem, didn't work with my Samsung tablet too
I thought it was possible tu use the S-Pen, but it didn't do anything
