### ISSUE TITLE
[Feature Request] Have a OAUTH Provider called "custom" or brandable

### ISSUE THREAD

**Issue by pcanham** [Stirling-Tools/Stirling-PDF#1330]
At the moment its hardcoded for one of the following providers;

- Keycloak
- Google
- GitHub

Could we have a provider called "custom" or something you can brand yourself. There are lots of different providers out there and thinking a generic provider (or client looking at the config) reference will help reduce the amount of coding work in the future setting up each provider within the code. Unless truly needed due to some unique configuration settings.

I am using Authelia and as a workaround I am using the provider/client "keycloak" which works but the UI is all branded as Keycloak as the SSO provider which could confuse users

![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/778646/d1f8b926-fc24-4259-80ba-7078c3e8dea7)

**Comment by Ludy87** [comment]
Hi, we have it see:

https://github.com/Stirling-Tools/Stirling-PDF/blob/316b4e42afbac31696dc188bb2de1ab783d47a03/src/main/resources/settings.yml.template#L13-L21

New providers are only encoded if they have a different behavior that others do not have, e.g. the logout with keycloak
