### ISSUE TITLE
【BUG】0.25.0版本，PDF 转换成图片 功能报错

### ISSUE THREAD

**Issue by null0034** [Stirling-Tools/Stirling-PDF#1335]
用 Docker 部署的此项目，项目版本是0.25.0，在使用 `PDF转图片` 功能时出现如图所示的报错：
![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/53291628/d046735a-6b4d-4247-a0f4-2dffe87a9afb)
我尝试更换不同大小的文件，转换成JPG或PNG格式，DPI使用默认的300，均会出现如图所示的报错信息。

**Comment by null0034** [comment]
这个是堆栈跟踪信息
![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/53291628/0afc6484-6257-4685-9358-15b52307eeb5)

**Comment by Frooodle** [comment]
duplicate of #1024
