### ISSUE TITLE
[BUG] Pipeline issue with loading/saving string arrays

### ISSUE THREAD

**Issue by smeredith** [Stirling-Tools/Stirling-PDF#1341]
To repro, create a custom pipeline config with only one step: ocr-pdf. Then try to OCR a pdf. You get an empty download.txt.

My config looks like this:

![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/6439539/bb962b63-ea1c-4152-b4fc-cb34fe6e2576)

**Comment by smeredith** [comment]
Another data point: the OCR operation tool in the main part of the app works fine. It's just when trying to use it in a pipeline that it fails.

**Comment by Frooodle** [comment]
https://github.com/Stirling-Tools/Stirling-PDF/issues/1034

**Comment by Frooodle** [comment]
not sure why it is handling it as comma seperated ill check and try have it support correct json

**Comment by smeredith** [comment]
Thanks.

The only way I could get it to work is to download the .json file, edit it (add "languages": "eng",) and upload it. Changes to the web form don't seem to save reliably.

**Comment by Frooodle** [comment]
I think this was resolved? let me know if still a issue
