### ISSUE TITLE
Server Not Listening on Port 808

### ISSUE THREAD

**Issue by foivospro** [Stirling-Tools/Stirling-PDF#1353]
When starting the application, I noticed that the log message suggests navigating to http://localhost:808, which seems incorrect. Typically, the application should be accessible via port 8080. Here is the relevant log message:
09:59:20.853 [restartedMain] INFO  s.software.SPDF.SPdfApplication - Navigate to http://localhost:808

![Στιγμιότυπο οθόνης 2024-06-01 100000](https://github.com/Stirling-Tools/Stirling-PDF/assets/115726918/dbcf9020-92f8-4a54-8269-853de4949466)

**Comment by Ludy87** [comment]
Seems to be a display error, does the error always occur when starting?

**Comment by foivospro** [comment]
No, only sometimes

**Comment by Ludy87** [comment]
Then it's really just a display error caused by your system.
