### ISSUE TITLE
Option to Hide Password Login

### ISSUE THREAD

**Issue by mark-monteiro** [Stirling-Tools/Stirling-PDF#1357]
I have turned on the new functionality for authentication via single sign on, and it's working great.

One piece that is a bit confusing for my users is the login screen still has an option to log in with a username/password. All the users on my site are authenticating via single-sign on, so it is a bit confusing/unnecessary to have the username/password fields appear.

I could see a couple ways to improve this:
- Add a new configuration option to hide the username/password fields on the login page
- Add a new configuration option to automatically redirect from the login page to the configured Single-Sign On provider. This is how another popular open source project Audiobookshelf does it, and I like their approach: https://www.audiobookshelf.org/guides/oidc_authentication/. There is a setting `Auto Launch` that enables the automatic redirect. However, there is also a special query parameter that can be added to the end of the login page url `?autoLaunch=0` to disable the automatic redirect. This is useful if you want to keep the auto-generated `admin` account around and still have the ability to log in with it via username/password

**Comment by mark-monteiro** [comment]
@Frooodle or @Ludy87 Can you clarify how this was resolved? I can see the linked PR, but it's not clear to me how I would use any of those changes to hide the username/password login.

I see there is a now a getter and setter for a new `loginMethod` field in `ApplicationProperties.java`, and based on the template for the login form HTML it seems like I should set that to `oauth2`. But I can't see how I would change that setting, is there an associated configuration setting?

**Comment by Ludy87** [comment]
@mark-monteiro Check out the documentation and you should be able to do it: https://github.com/Stirling-Tools/Stirling-PDF?tab=readme-ov-file#customisation

**Comment by mark-monteiro** [comment]
Hi @Ludy87, thanks for the clarification. I just realized the referenced PR has not been released yet, which is why I was confused

**Comment by Frooodle** [comment]
I'll get a release out today hopefully :)

**Comment by VincentSC** [comment]
Heads up for who uses Docker, this has seemingly not been added to "latest" on Docker Hub yet

**Comment by Frooodle** [comment]
Yeah had some issues with alpine recently 
Delayed releases
Sorted hopefully this weekend
