### ISSUE TITLE
May I ask how to deal with windows flash back, remind me to download the jdk every time, even if I download it, but every time I open it there is still this prompt, resulting in my inability to use

### ISSUE THREAD

**Issue by aqpmzngldh** [Stirling-Tools/Stirling-PDF#1372]

**Comment by Frooodle** [comment]
Did you install the jdk?

**Comment by aqpmzngldh** [comment]
> Did you install the jdk?

I have installed jdk8, and then I was prompted to install jdk21. After I installed it, every time I opened the exe file, I was still asked to download 21. Do I need to add it to the environment variable after installing jdk21 or do some configuration

**Comment by aqpmzngldh** [comment]
> Yeah I am presuming that your java home environment variable is set to jdk8 and that must be causing issues

Okay, thank you. I'm good
