### ISSUE TITLE
Existence of an empty class

### ISSUE THREAD

**Issue by jimdouk** [Stirling-Tools/Stirling-PDF#1377]
I was examining the classes in the SDPF/utils directory when I came across PDFManipulationUtils.java, which is empty and I could not understand the reason of its existence. 

![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/115452543/9fbb2792-ec70-47d4-bf0f-98d0b5e86def)

You can find this class at: src/main/java/stirling/software/SPDF/utils/PDFManipulationUtils.java

**Comment by Frooodle** [comment]
seems good to remove
