### ISSUE TITLE
Running as a service .env file doesnt work properly

### ISSUE THREAD

**Issue by bert3ch** [Stirling-Tools/Stirling-PDF#1378]
Hi,
First of all, I m not a pro,
after local installation and running as a service everything is working fine except environment file.
in the instructions, /opt/Stirling-PDF/.env is created but when I put system:  enableLogin: 'true' into that env file, it doesn't ask a login. 
how can it be fixed? Is environment file working just for Docker?

**Comment by Frooodle** [comment]
You should be using configs/settings.yml
not any .env file
what instructions did you read?

**Comment by Frooodle** [comment]
https://stirlingtools.com/docs/Advanced%20Configuration/How%20to%20add%20configurations

![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/77850077/ca69b9b6-87be-48b6-879f-78420a8866f7)

you can see the difference here

**Comment by Frooodle** [comment]
same config also in readme.md

**Comment by bert3ch** [comment]
Hi,

Thank you for your answer. The problem was solved after changing the configs/settings.yml file. Appreciate 

In the LocalRunGuide.md, under the "Running as a Service" section, it says that after creating the .env file, "you can add all variables, one variable per line." This part confused me.
