### ISSUE TITLE
[Feature request] Watched folder autoconvert

### ISSUE THREAD

**Issue by gittynick** [Stirling-Tools/Stirling-PDF#138]
This is a very useful application 👍 
I would much like to be able to mount folders (for ex /scanner) so that new files are accessible inside Stirling-PDF without browsing... Even better : some kind of "watch folder" that could auto-convert files to predefined PDF settings ?

**Comment by poudenes** [comment]
Had same idea. Didn't saw this request. I love automation stuff. Would be nice to able to create actions and save them as separate settings:

Check folder, what do you want to do (a), what do you want to do (b), where to export the new file
Example:
Read folder /data/images/ > convert them to PDF > OCR > save new file to /data/export
or
Read folder /data/pdf/ > split PDF > save new file to /data/export
or
Read folder /data/ocr_import/ > OCR PDF > save new file to /data/export

etc, etc

User can create multiple folder for different things and create some automation actions.

//Keep up the good work!

**Comment by Frooodle** [comment]
I am finally making this now and having discussions on how to develop it on my discord, please feel free to give inputs!

**Comment by Frooodle** [comment]
Watched folder now supported
https://github.com/Stirling-Tools/Stirling-PDF/blob/main/FolderScanning.md
