### ISSUE TITLE
Setting default language does not take effect

### ISSUE THREAD

**Issue by ws910616** [Stirling-Tools/Stirling-PDF#1383]
Modify the defaultLocale: 'en US' in the settings. yml file to: zh_cN, whether to open the page in English or not. Attempting to run Docker to add LANGS=zh_cN language or English, may I ask if my operation method is incorrect?

**Comment by terrytw** [comment]
> LANGS to define custom font libraries to install for use for document conversions

**Comment by Frooodle** [comment]
settings. yml  should work but the docker env way to do it is not LANGS as other commenter mentioned that is for fonts
correct docker env way would be 
``SYSTEM_DEFAULTLOCALE: en_US``

**Comment by Frooodle** [comment]
also did you mean to write
``zh_cN`` with a lower case c ? 

I believe it should be ``zh-CN`` if i refer to
https://github.com/Stirling-Tools/Stirling-PDF/issues/481

also note the - not _

**Comment by ws910616** [comment]
Thank you very much, I made a mistake. I made a mistake in writing zh_cN and changed it to zh-CN, which will be displayed in Chinese by default
