### ISSUE TITLE
Sign a PDF with your certificate: Show Signature options explanation?

### ISSUE THREAD

**Issue by Kofl** [Stirling-Tools/Stirling-PDF#1384]
Hi,

I am running the latest docker version and when signing a pdf with PKCS#12 file I also select "Show Signature"
Shouldn't that show the signature directly in the document itself like a stamp on the document (Acrobat Pro default setting)?

I cant get it working and also unsure about the Location input field. What values are here valid?

Thanks,
Thomas

![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/6079097/c5196800-6830-4851-9036-6fddba30d97d)

**Comment by Frooodle** [comment]
location means location of office which did signing etc

London, UK 
etc
Much like adobe
![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/77850077/f26fccce-069e-453a-9fe0-ac2acfcc3c04)

Currently there is no location were this signature can be placed, it is hard coded to a set location
