### ISSUE TITLE
PDF viewer broken in (slightly) old version of chrome

### ISSUE THREAD

**Issue by terrytw** [Stirling-Tools/Stirling-PDF#1392]
When using older version of chrome, PDF viewer gives a `Uncaught TypeError: Promise.withResolvers is not a function
    at app.js:104:14`

I have downloaded some versions of chrome from https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win_x64/

It seems that at 1197778 it is broken and at 1203642 it is working. 
Considering that 1197778 is a build from last September, which is less than a year, I say maybe it is better to support it?

**Comment by Kofl** [comment]
Dont think thats an good idea:

_Because of security concerns, Google does not provide an official repository of older versions._

**Comment by terrytw** [comment]
What's not a good idea? Downloading older version of chrome (it's chomium actually) or supporting older version of chrome?

Besides from the domain name you know it is a google official repository.

**Comment by Kofl** [comment]
Which use case requires to support older versions of chrome?

**Comment by terrytw** [comment]
Some people won't always update to the latest version of chrome. 

There are a lot of other browsers that is built on top of chromium, and they don't always follow the chrome update cycle.

Besides, like I said, a version from Sep 2023 is broken, it is not even that old. It is common practice for a lot of tech companies to support at least 20 versions of chrome. Based on how fast Google is racking up the version numbers, 20 version does not even go that far back.

**Comment by Frooodle** [comment]
So view pdf support is caused by update in pdf.js which was done due to security so sadly we cant support that older model!
Thanks for raising for this however

**Comment by terrytw** [comment]
> So view pdf support is caused by update in pdf.js which was done due to security

OK thanks for the info, good to know.

**Comment by terrytw** [comment]
Reading through https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

It seems that they provide a translated/polyfilled build for older browsers, which supports at least chrome 98+, and that sounds very reasonable.

If it is easy to implement (like a simple swap), could Stirling PDF ship with both versions of PDF.js and let users choose which flavor they want? I searched through codebase, seems that you guys don't really tamper with PDF.js too much, but rather treats it like a dependency.

**Comment by Frooodle** [comment]
yes very true, might be possible!
