### ISSUE TITLE
App Version Number gone in Docker Container

### ISSUE THREAD

**Issue by rmayergfx** [Stirling-Tools/Stirling-PDF#1398]
Docker installed from https://registry.hub.docker.com/r/frooodle/s-pdf
is missing the App Version Number, only shows 0.0.0
![grafik](https://github.com/Stirling-Tools/Stirling-PDF/assets/105392164/0568ce3e-0cf7-4058-be9d-58dbcf5eeb79)

**Comment by Frooodle** [comment]
should be fixed :)
