### ISSUE TITLE
[Feature Request]: Merge Odd-Even Pages

### ISSUE THREAD

**Issue by Skillkiller** [Stirling-Tools/Stirling-PDF#1432]
### Feature Description

I would like to add a PDF Page Organiser Mode which re-sorts manual double-sided scans.

Specifically, it is about scans where first all front pages (odd pages) and then all back pages (even pages) were scanned. Example: 1,3,5,2,4,6

I have already mentioned this in discussion #1365 but have not yet received an answer, so I assume that this is not yet possible.

### Why is this feature valuable?

I think this feature is useful for manual one-sided bulk scans

### Suggested Implementation

I would add a new PDF Page Organiser mode for this. 

### Additional Information

I would implement this feature or the new mode myself and submit it as a PR.

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

**Comment by Frooodle** [comment]
Sounds good to add!

**Comment by Frooodle** [comment]
Duplex sort might already do this not sure

**Comment by Skillkiller** [comment]
Hello, I have tested all previous modes. None sorted in the appropriate order.
[Odd-Even Scan.pdf Example](https://github.com/user-attachments/files/15778871/Odd-Even.Scan.pdf)

Just for the record in the hope that they might be useful:
[Normal Order.pdf](https://github.com/user-attachments/files/15778959/Normal.Order.pdf)
[Example.docx](https://github.com/user-attachments/files/15778961/Beispiel.docx)

<details>
  <summary>Initial situation</summary>

![Odd-Even Scan(1)](https://github.com/Stirling-Tools/Stirling-PDF/assets/18444809/f1993ea1-a6d8-44a3-a4d0-8650547fa6f0)

</details>

<details>
  <summary>Duplex Sort</summary>

![Odd-Even Scan Duplex](https://github.com/Stirling-Tools/Stirling-PDF/assets/18444809/c3db0e5c-71f3-460b-baf6-ccdd9558ceef)


</details>

<details>
  <summary>Booklet Sort</summary>

![Odd-Even Scan Booklet](https://github.com/Stirling-Tools/Stirling-PDF/assets/18444809/5dd462b1-64ae-4c33-9973-197f3f783904)


</details>

<details>
  <summary>Side Stitched Booklet Sort</summary>

![Odd-Even Scan Side Stitched Booklet](https://github.com/Stirling-Tools/Stirling-PDF/assets/18444809/fc456b3b-fff3-4767-b999-57e3a629f5b0)


</details>


<details>
  <summary>Odd-Even Split</summary>

![Odd-Even Scan Odd-Even Split](https://github.com/Stirling-Tools/Stirling-PDF/assets/18444809/5623a57d-4590-4c6b-a887-6921d761410f)


</details>

**Comment by Frooodle** [comment]
Sure then!

**Comment by Skillkiller** [comment]
I will do that. How can I add a new text string which can be translated? I have seen that in ``src/main/resources/messages_en_US.properties`` + other languages all the strings are defined. Can I simply enter them there in German and English or is there a central translation platform or a central definition centre/file?

**Comment by Frooodle** [comment]
En_GB is central 
Anything added there will be spread to rest later via scripts after merge if they don't have their own translations
