### ISSUE TITLE
[Bug]: unable to open pdf in view-pdf

### ISSUE THREAD

**Issue by huouer** [Stirling-Tools/Stirling-PDF#1439]
### The Problem

No response whrn click the "open File" button

### Version of Stirling-PDF

0.26.0

### Page Where the Problem Occurred

http://localhost:8080/view-pdf

### Browsers Affected

Chrome

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by Ludy87** [comment]
is there a connection with this issues https://github.com/Stirling-Tools/Stirling-PDF/issues/1392

**Comment by terrytw** [comment]
There is possibly another related issue https://github.com/Stirling-Tools/Stirling-PDF/issues/1375
I feel like if problem is not solved, there will be issue reports every week.

**Comment by Ludy87** [comment]
I will look into it, I have no idea yet how to distinguish which browser with which version is used

**Comment by terrytw** [comment]
I think swapping to translated/polyfilled version of PDF.js might be the easiest way to deal with it, mozilla's demo runs fine on older versions of chrome.
