### ISSUE TITLE
[Feature Request] - Quick Codes & Paperless-ngx integration (Pre-Consumption Scripting)

### ISSUE THREAD

**Issue by nodecentral** [Stirling-Tools/Stirling-PDF#144]
Hi @Frooodle 

Hope all is well..

I’m sure a number of people coming here will be users of Paperless-ngx (myself included) and a common theme within that group is how to best prepare a pdf for import. And a facility that paperless team make available is a [Pre-Consume Script](https://docs.paperless-ngx.com/advanced_usage/#pre-consume-script) which allows you to call other tools/processes before a file is imported.

I’m wondering what the best approach is to integrate Stirling-PDF with Paperless-ngx via this script, e.g. could Stirling-PDF look for a particular `processing code` within the filename and automatically process it ? For example if I added `[R2,4]` to file name could Stirling PDF interpret that to mean [R] = Remove and [2,4] = Pages 2 and 4 ?

There are likely better ways to do this, but I wanted to float this as a new feature idea to see what you and others thought..

**Comment by Frooodle** [comment]
I'm wanting to do this as part of a bigger enhancement where you can define full processing flows to run multiple operations within stirling pdf itself rather than everyone having to wrap their own scripts around each endpoint 

But this will take time to design and make

**Comment by Frooodle** [comment]
I could probably add a feature similar to what you mentioned in meantime though I'll consider it and see what's best

**Comment by nodecentral** [comment]
Hi @Frooodle , hope you don’t mind but I’ve updated the title and started to think about the `QuickCode` format that could be used.. (and keeping it simple for likely the main ones, that best support a single quick code reference in the file name)

[RO] = Rotate
[RE] = Remove
[SP] = Split

After the requirement, you then add the parameter/criteria so 

[RE_2,4] = Remove pages 2 and 4
[SP_3] = Split at page 3

** Trying to think of the safe characters to use, so not to have issues

**Comment by Karsto-sys** [comment]
I do not have a duplex scanner right now I merge my scans with a small python script. Would be nice if it something like that what also be integratable.

**Comment by damomato** [comment]
Not sure if this is the right place to put this, but on the topic of paperless integration, would it be possible to select a pdf directly from there to edit in stirling pdf?

**Comment by Frooodle** [comment]
@damomato Never actually used paperless so unsure of that integration sorry, also it would be seperate ticket to not get it mixed up

**Comment by damomato** [comment]
No worries. Honestly it's easy enough to just download from paperless then upload into stirling so I won't submit anything. Great work on this by the way!

**Comment by henrywintif** [comment]
I just found this repo and would love to use it with paperless as well. 

Right now I scan to a folder on my NAS, and then edit locally (rotating, removing blank pages, etc) before uploading to the NAS folder that paperless-ngx ingests from. 

A use case that I could see really useful would be if I could scan to a folder that Stirling has access to. I'd go to the UI, see the un-cleaned pdfs, and then be able to use stirling features on these files, either in batch or one by one. Then maybe export them to the paperless ingest folder via API, local command, or something else. 

Just an idea... i haven't even started hosting stirling yet but I saw this thread and figured I'd toss in my 2¢. Excited to get this up and running on my server. Thanks for the project and I'll contribute if I'm able, although I haven't used Java since college.

**Comment by Frooodle** [comment]
I wanted Stirling-PDF to be a application which have a API but its UI is very userfriendly and your dad can use it kind of thing.
It being something which you have pre-populated things and create a workspace of PDFs to select isnt really what i am wanting from the app.
I will have a think on it maybe a advanced button in setting or something but i want to hide most of these complex API and automation things away from main UI

**Comment by Frooodle** [comment]
Didnt have time to do quickcodes but I am finally making automation steps now and having discussions on how to develop it on my discord, please feel free to give inputs!

**Comment by Frooodle** [comment]
Watched folder now supported
https://github.com/Stirling-Tools/Stirling-PDF/blob/main/FolderScanning.md

No quick code format though, instead json setting files
