### ISSUE TITLE
[Bug]: "ERR_TOO_MANY_REDIRECTS" when served under sub path

### ISSUE THREAD

**Issue by terrytw** [Stirling-Tools/Stirling-PDF#1442]
### The Problem

I have stirling pdf served under a subpath: `https://maydomain.com/pdf/`, reverse proxied from `http://192.168.17.173:8080/pdf`

I have reported an issue regarding the wrong path of first time login credential change: https://github.com/Stirling-Tools/Stirling-PDF/issues/1387

After that is fixed, I tried again, this time the path is correct, I got `https://maydomain.com/pdf/change-creds` and `http://192.168.17.173:8080/pdf/change-creds`, but the site is not loading, I got error message:
```
mydomain.com redirected you too many times.
[Try clearing your cookies](https://support.google.com/chrome?p=rl_error&hl=en-US).
ERR_TOO_MANY_REDIRECTS
```

### Version of Stirling-PDF

lastest

### Browsers Affected

Chrome

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by Frooodle** [comment]
Please correctly report which version you are on and see if it's truely our latest version and update if not

**Comment by terrytw** [comment]
Hi this is the sha256 of the image:
![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/24227628/89157d5c-0b87-435e-9054-defea531abd9)

**Comment by Frooodle** [comment]
Can you get version number from the UI settings menu

**Comment by terrytw** [comment]
> Can you get version number from the UI settings menu

I didn't because I cannot login, because of the error....

I created another container without the sub path, here is the version:
![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/24227628/3079c5b9-167f-4353-8b0e-192ca4ca0b41)

**Comment by Frooodle** [comment]
Please add env var
SYSTEM_ROOTURIPATH  as /pdf

**Comment by terrytw** [comment]
> Please add env var SYSTEM_ROOTURIPATH as /pdf

I already did, this is the docker run command:

```
docker run -d \
  --restart unless-stopped \
  --name Stirling-PDF \
  --hostname Stirling-PDF \
  --net custom --ip **** \
  -e PUID=*** \
  -e PGID=*** \
  -e TZ=America/**** \
  -e SYSTEM_ROOTURIPATH=/pdf \
  -e DOCKER_ENABLE_SECURITY=true \
  -e SECURITY_ENABLE_LOGIN=true \
  -e INSTALL_BOOK_AND_ADVANCED_HTML_OPS=true \
  -e LANGS=en_GB \
  -v ***/Stirling-PDF/data:/usr/share/tessdata \
  -v ***/Stirling-PDF/configs:/configs \
  -v ***/Stirling-PDF/logs:/logs \
  frooodle/s-pdf:latest
```

**Comment by Ludy87** [comment]
@Frooodle Maybe the PR can fix it: https://github.com/Stirling-Tools/Stirling-PDF/pulls

**Comment by terrytw** [comment]
Fixed in latest version, thanks @Ludy87!
