### ISSUE TITLE
[Bug]: Docker Container Reset stays with wrong version

### ISSUE THREAD

**Issue by rmayergfx** [Stirling-Tools/Stirling-PDF#1443]
### The Problem

Stirling-PDF is running as Docker Container on Synology NAS. First setup was done by portainer script.
services:
  stirling-pdf:
    container_name: Stirling-PDF
    image: frooodle/s-pdf:latest

i update the container by downloading the new image with a script polling all new images. stop and reset the container.
now i was wondering, why the Container was still using an old version. I found that the environmental variable
VERSION_TAG 0.2.xxx
ist never updated and still is pointig to the old installed version. If i delete this variable and reset the container, the variable will be set with the latest version number. Why is this "VERSION_TAG" not updated with the matching Version number from the actual image?

There is no VERSION_TAG set in portainer at Environment variables.

### Version of Stirling-PDF

0.2.x

### Last Working Version of Stirling-PDF

0.x

### Additional Information

Download new image from frooodle/s-pdf:latest. Stop Container, Reset Container. Start Container.
Until the VERSION_TAG is not deleted, it will stay on the already installed older Version.

### Browsers Affected

Firefox, Chrome, Safari, Microsoft Edge, Other

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by Frooodle** [comment]
Cant reproduce this issue, i assume its related to how you are updating the containers, i recommend 
https://github.com/containrrr/watchtower
to update all your containers

**Comment by Frooodle** [comment]
I assume your version you are downloading is older version which is why VERSION_TAG  does not match, 
Can you prove that VERSION_TAG  is old BUT the jar within docker is new? otherwise i assume both are old

**Comment by rmayergfx** [comment]
i am not using watchtower, i have a simple scheduled script that is running as root to pull the latest images, for froodle i use
docker pull frooodle/s-pdf:latest
It´s working fine, i got every time a new version is downloaded an e-mail and so i can check for me if i wan´t to update the docker.
This script is also downloading other images, so i am sure it is working as expected. Also i can check the downloaded image and checksum with portainer, no problems with the images.
The only docker not working with stop, reset and start is frooodle/s-pdf:latest,  i always need to remove the line "VERSION_TAG", if i don´t do this, the container stays at the old version and i don´t know why.

**Comment by Frooodle** [comment]
are you able to provide script?

**Comment by Frooodle** [comment]
and also docker run/compose

**Comment by rmayergfx** [comment]
sript is just a scheduled task as root with 
docker pull frooodle/s-pdf:latest

to get the latest updates/image

Installation was done with portainer and tutorial from
https://mariushosting.com/how-to-install-stirling-pdf-on-your-synology-nas/

modified with :latest tag and valid language settings, as en_US or de_DE is wrong, should be en-US oder de-DE.
also appname and user/passwd was changed to my credentials

**Comment by Frooodle** [comment]
So to confirm you stop old instance 

Remove old image 

Run docker pull 

Start container again? 


There is something wrong in the process as I don't believe there is issue our end so trying to lay it out

**Comment by rmayergfx** [comment]
The sequence is different.
Scheduler is downloading latest version, if there is a newer one, i get informed by email.
then i stop container, reset container and restart container. 
this is successfull with any other docker i am running, only stirling has a "VERSION_TAG" in environmental variables that is staying on the old version until i delete.

**Comment by Frooodle** [comment]
Cant reproduce

**Comment by rmayergfx** [comment]
Tested just a few minutes ago, as there was the old image 0.26.0 and a new image 0.26.1 is online, got an email from my system that a new image was downloaded 
`Status: Downloaded newer image for frooodle/s-pdf:latest` so my scheduler has done the job fine.
So i looked at the container:
![grafik](https://github.com/Stirling-Tools/Stirling-PDF/assets/105392164/a5d63948-326a-4615-9a3a-6c8e1f4df80f)
VERSION_TAG is 0.26.0. i stopped and reset the conainer. Still 0.26.0. Protokoll shows me 
`Running Stirling PDF with DOCKER_ENABLE_SECURITY=true and VERSION_TAG=0.26.0` and this is still wrong. System started with old Version. Image can´t be deleted, as it is used by the container, equal if the container is stopped or not. So i deleted again the VERSION_TAG in the Container, do a reset and the VERSION_TAG switches to 0.26.1.
So the issue is still there. i can show you this also remote if you need to see this.

**Comment by Frooodle** [comment]
the docker latest fat should be a workaround for you for this, the version tag is for the security jar to be downloaded as a optional addon,
docker fat does not do this and uses the exact version of the docker file and doesnt use this far

**Comment by rmayergfx** [comment]
Tested today with tag:Latest. Still the same, why is this Version Tag not updated when the container is reset? I didn´t understand why this version tag is not updated during the reset, only by deleting the complete variable or doing a fresh container it is automatically set. 
It this is needed for security jar, maybe there is a better way to implement, e.g. not as version tag better as jar version tag?
