### ISSUE TITLE
[Feature Request]: Could you please add PDF to Excel function?

### ISSUE THREAD

**Issue by Maccell** [Stirling-Tools/Stirling-PDF#1451]
### Feature Description

Could you please add PDF to Excel function?It's useful.

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

**Comment by Frooodle** [comment]
we have a WIP pdf to csv but its heavily WIP but is live

**Comment by noseshimself** [comment]
Might be heavily WIP but is already heavily helpful.
