### ISSUE TITLE
[Feature Request]: Invert PDF colors for printing

### ISSUE THREAD

**Issue by IkelAtomig** [Stirling-Tools/Stirling-PDF#1452]
### Feature Description

Upon using this option, it would invert the color of the pdf document like a negative in Old microfilms used in camera.

It could be either of Full inversion or as follows :

- Black text on White
- Green, Yellow and White Text on Black
- Custom Color for Background and Text

The Above three are from Adobe's Accessibility settings.

---
- [ ] Pure Inversion 
- [ ] Inversion based on Color Profiles

### Why is this feature valuable?

This is a really needed feature, if somebody want to print, say, a powerpoint presentation file exported as PDF.

It's Colors will be printed as Charcoal Black during printing. While inverting the colors, The text which is the main material is turned black and background to white.

This saves a lot of valuable ink and prevents the toner from running out quickly.

While adobe has this but has the feature named as Print Production where you adjust it but paywall-ed. Which is used to print in this way. 

Adobe primarily has this inversion for viewing inverted only not printing.

### Suggested Implementation

Upon research for my personal use case, I found [this](https://github.com/merkez/darkpdf) project which is very useful in Full inversion. 

But I don't know if it will be supporting other modes, I stated though. Those are necessary in case inversion doesn't work out and it could help the user as backup to adjust the color profiles for inversion.

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

**Comment by Hashim0510** [comment]
is this still needs to work on ?

**Comment by IkelAtomig** [comment]
Indeed, It is a very useful feature and saves ink. People just don't know it exists.

24 Sept 2024, by ***@***.***:

**Comment by Hashim0510** [comment]
few queries :
Customization for color of background and text should be given to user ? 
client side and server side needs to done for this feature on this single ticket ?

**Comment by Frooodle** [comment]
Colour is so visual that it makes sense for it to be client only 
We already have a contrast/ colour feature existing 
Would be enhancement for that

**Comment by Hashim0510** [comment]
What I have understood is that, It should invert the color of everything in pdf including texts and images. right ?
For example :

Input pdf :  
[INPUT-tets-invertColor.pdf](https://github.com/user-attachments/files/17128191/INPUT-tets-invertColor.pdf)

OUTPUT should look like :
[output-test-invert-colors.pdf](https://github.com/user-attachments/files/17128209/output-test-invert-colors.pdf)

**Comment by Hashim0510** [comment]
please assign to me.

**Comment by IkelAtomig** [comment]
It needs to support various color pallets too for other colors in case it doesn't work well by default as a contingency plan. 

25 Sept 2024, by ***@***.***:

**Comment by Hashim0510** [comment]
In that, do I need to find out which are all colors doesn't work and should have various options for those colors ? @IkelAtomig

**Comment by IkelAtomig** [comment]
I would say, Just install Adobe Acrobat reader and use the color pallets listed. It is about a number of three, of I remember correctly. 

25 Sept 2024, by ***@***.***:

**Comment by Hashim0510** [comment]
I don't see that exists in adobe, can you please direct me towards absolute @IkelAtomig

**Comment by Hashim0510** [comment]
![image](https://github.com/user-attachments/assets/3e1f6e36-bf6c-45a5-9c4d-6b0c34271920)

From the issue description and @IkelAtomig mentioned in above comment, I can see the feature from adobe. Refer to the feature of Adobe from the above pasted image.

features on adobe are :

   1. changing text and background (yellow, green, white)

   2. custom color option for text and background
  
Do you expect me to replicate the same with full inversion added to that ? 
let us dispel this misconception @IkelAtomig @Frooodle

**Comment by IkelAtomig** [comment]
Indeed.

25 Sept 2024, by ***@***.***:

**Comment by Hashim0510** [comment]
Raised the PR. Please review and comment it!

**Comment by Frooodle** [comment]
> Colour is so visual that it makes sense for it to be client only We already have a contrast/ colour feature existing Would be enhancement for that

I notice the PR you raised is server side not client? I don't think many people would want to use a colour editor without visualising the changes etc

**Comment by Frooodle** [comment]
However still seems good so happy to merge, but I think it would have made more sense to be client side... It could be this code gets replaced down the line etc

**Comment by Hashim0510** [comment]
https://github.com/Stirling-Tools/Stirling-PDF/issues/1452#issuecomment-2374720034

As per discussion, I did this feature. Your comment on enhancement for the contrast feature to visually exist when client changes was acknowledgeable.
But the issue title and whatever the discussion before implementation was around the the invert color, and adobe's custom color and high contrast color feature.
I was confirming it before implementation, whatever I was going to do.
I hope misconceptions on issue title and clear goals for features should be taken care of in the future.

**Comment by Hashim0510** [comment]
I have added the request changes om navbar. html anf en_gb.properties files @Frooodle
