### ISSUE TITLE
Request survey translation

### ISSUE THREAD

**Issue by albanobattistella** [Stirling-Tools/Stirling-PDF#1474]
### Feature Description

Hi,
the survey is a nice initiative.
Is it possible to translate it?
This is because, some definitions in English may change in other languages ​​and may alter some answers.
Thank you.
A.

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

**Comment by Frooodle** [comment]
Sadly I could not find any survey applications that have translations for free :(

**Comment by Frooodle** [comment]
Seems i can get a 30 day trial... worth a try :) let me find out

**Comment by Frooodle** [comment]
seems it takes 24h on business day for key to arrive
