### ISSUE TITLE
[Bug]: Convert does not work (show finished job) with Vivaldi Browser

### ISSUE THREAD

**Issue by MrMic** [Stirling-Tools/Stirling-PDF#1477]
### The Problem

Try to convert the image to PDF and nothing appears to warn that the job is finished...

### Version of Stirling-PDF

0.26.1

### Docker Configuration

```txt
the one provided
```

### Browsers Affected

Chrome, Other

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by Frooodle** [comment]
Anything in docker logs?

**Comment by Frooodle** [comment]
Closing due to no reply
