### ISSUE TITLE
[Bug]: Problem converting pdf to doc.

### ISSUE THREAD

**Issue by yumibad** [Stirling-Tools/Stirling-PDF#1484]
### The Problem

When converting PDF to Word, the document is converted line by line and depending on the document, it breaks the lines leaving some words spaced.
Some words are getting spaced, for example: Google  “Go ogle”

### Version of Stirling-PDF

0.26.0

### Browsers Affected

Other

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by yumibad** [comment]
I also can't add a line after converting. 
I can only edit lines that already have something.

**Comment by Frooodle** [comment]
This is a known bug with libreoffice conversion the 3rd party application we use for conversions
Nothing we can do our side sorry!
