### ISSUE TITLE
[Bug]: Missing description for Split function in top bar

### ISSUE THREAD

**Issue by ProvaTeams** [Stirling-Tools/Stirling-PDF#1491]
### The Problem

In the top bar when hovering over the Split section, the description is missing
![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/142001287/b1155d97-a370-4342-a196-51f7fa3ad6e5)

However in the Tools section the description is there
![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/142001287/7bddd2aa-a62d-481d-ac79-618ff60098bc)

The problem is related to the navbar.html file, where there is th:title="#{home.split-pdfs.desc}" instead of th:title="#{home.split.desc}"

### Version of Stirling-PDF

0.26.1

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by Frooodle** [comment]
You are welcome to raise pr for this ! Thanks for finding this

**Comment by ProvaTeams** [comment]
I've created the pr
