### ISSUE TITLE
[Bug]: Compressing PDF

### ISSUE THREAD

**Issue by cvt8** [Stirling-Tools/Stirling-PDF#1502]
### The Problem

When compressing PDF an error appears : HTTP error! status: 413. No more information is given.

### Version of Stirling-PDF

0.23.1

### Browsers Affected

Firefox

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by Ludy87** [comment]
An HTTP 413 error occurs when the HTTP request or HTTP response sent by the client or server is too large and exceeds the maximum allowed size.

**Comment by Gokulviper** [comment]
@cvt8 I need some information about the issue you are facing. Are you encountering this problem with every PDF file or just a single PDF file? If it is a single PDF file, what is its size?
