### ISSUE TITLE
[Feature Request]: google-symbol.woff2 font is too large

### ISSUE THREAD

**Issue by Joulloy** [Stirling-Tools/Stirling-PDF#1506]
### Feature Description

is it already compressed to the smallest size? Currently,it takes 30 seconds for my website to request it.so what can i do to reduce its size

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

**Comment by Frooodle** [comment]
https://github.com/Stirling-Tools/Stirling-PDF/pull/1723

**Comment by Frooodle** [comment]
reduced by 80% in next update
