### ISSUE TITLE
Port Change

### ISSUE THREAD

**Issue by Nino678190** [Stirling-Tools/Stirling-PDF#1517]
I changed the port in the docker-compose.yml from 8080:8080 to 3000:3000 because 8080 is a used Port but it starts on port 8080 and I can't access it. It said that it is on http://localhost:8080 but I do this on a raspi and can't access this.
Help

**Comment by Frooodle** [comment]
You need to do 3030:8080

**Comment by Nino678190** [comment]
Thanks
