### ISSUE TITLE
[Bug]: Multi-tool drag to rearrange on FF not supported correctly

### ISSUE THREAD

**Issue by Frooodle** [Stirling-Tools/Stirling-PDF#1539]
### The Problem

When dragging a page it first pops up the drag to upload menu before allowing the user to then drag the page

### Version of Stirling-PDF

0.26.1

### Page Where the Problem Occurred

multi-tool

### Additional Information

Works fine on brave, edge, chrome etc

### Browsers Affected

Firefox

**Comment by Frooodle** [comment]
![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/77850077/c06cbd43-a84b-4b00-ac0e-ad792085a649)

**Comment by Clemens-E** [comment]
Thank you!
