### ISSUE TITLE
[Feature Request]: Add Split Pages feature to Multitool

### ISSUE THREAD

**Issue by Clemens-E** [Stirling-Tools/Stirling-PDF#1540]
### Feature Description

Add the "Split Pages" feature into the Multitool.
It should be possible to View and Rearrange Pages, and then split them at specific positions.

### Why is this feature valuable?

I think the Multitool makes for a really great feature, especially because you can see all pages and visually edit them.

The "Split Pages" feature would be a great addition, as currently you have to open the PDF separately and scroll through the pages and write them down. This is very slow and confusing because you might miss a page, and also can't rearrange them.

### Suggested Implementation

I dont have a clear idea of how this should be implemented, but I could see the following be a solution:

- Option to add "Seperator" Blocks between pages to split.
- Being able to "create" rectangles to group specific pages 

### Additional Information

I appreciate all the Work spent on this, I think something like Stirling-PDF was a thing many people needed and wanted in the self-hosted community.

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

**Comment by FiratUsta** [comment]
Since no one was assigned to this, I thought I would have a crack at it. Turns out it was relatively simple to do. The patch is ready, should I wait for an assignment before submitting a PR as per the contributing guidelines or should I just make the PR?

**Comment by FiratUsta** [comment]
Very similar to how you've done it, but I've added the split button on top of the insert pages button instead. Once clicked, it creates a separator in that place, and another click removes it. 

At export time, after all other operations are done if there are any separators it sends the file blob to the split-pdfs API endpoint instead of downloading it with separator positions as the input text.

**Comment by FiratUsta** [comment]
Most likely you can, I just didn't want to rewrite the whole split, rename, compress functionalities when it already exists. I think this is more advantageous since there wouldn't be two different methods to maintain and bug-fix if there are any.

Cheers!

**Comment by Frooodle** [comment]
Server side is mostly for API usage, ideally we would have as much possible client side for reduced load etc

**Comment by FiratUsta** [comment]
I've went ahead and submitted a PR, please review and let me know how can I improve it. This is an important improvement for me so I'd like to work on it to resolve it if possible. 

Thank you!
