### ISSUE TITLE
[Feature Request]: Make Extract Images multithreaded

### ISSUE THREAD

**Issue by Sf298** [Stirling-Tools/Stirling-PDF#1556]
### Feature Description

Extract Images seems to only run on 1 core.

### Why is this feature valuable?

It could really boost the performance when processing large documents.

### Suggested Implementation

Note: I would recommend adding a configuration variable to limit the number of threads used system wide

The easiest approach might be to split the list of pages across the available cores. Possibly at this [line](https://github.com/Stirling-Tools/Stirling-PDF/blob/5751b1ac2dc8ba66df4ceb9ff44ecd96b5521764/src/main/java/stirling/software/SPDF/controller/api/misc/ExtractImagesController.java#L76C9-L76C48)?

### No Duplicate of the Feature

- [x] I have verified that there are no existing features requests similar to my request.

**Comment by HimaGirija99** [comment]
May I work on this feature if it is not yet addressed?

**Comment by Frooodle** [comment]
Sure! Please go ahead

**Comment by aditya76-webdev** [comment]
Hii team,  @Frooodle ! If this issue is still open and no one is working on it so may i work on this feature ? i have good command on java

**Comment by Frooodle** [comment]
Ahh I believe this has been done and should be closed

**Comment by aditya76-webdev** [comment]
ohh okay no problem! i will find some new issues and will ask for that!!

**Comment by Frooodle** [comment]
Sorry about that 
But I am sure their are plenty of other operations which can be multi threaded out there 

BlankPageController as an example
