### ISSUE TITLE
[Feature Request]: Validate Removed Blank Pages

### ISSUE THREAD

**Issue by StanBarrows** [Stirling-Tools/Stirling-PDF#1574]
### Feature Description

To validate the removed blank pages, it would be helpful to have the deleted blank pages as a dedicated file output so they can be validated. Currently, no "control" exists over which pages are removed from the action. 

### Why is this feature valuable?

- To validate the removed blank pages

### Suggested Implementation

- [ ] Provide a dedicated file with the deleted pages
- [ ] Provide the page-numbers of the deleted pages within the API-Request

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

**Comment by KAHO-TONG** [comment]
agree with it

**Comment by mannam11** [comment]
@StanBarrows I have gone through it and it make sense.  Here we can do like creating separate files and Zip both PDF files into a single archive. is that make sense?
@Frooodle can you please assign this to me.

**Comment by mannam11** [comment]
@sbplat can you please assign this to me
