### ISSUE TITLE
[Feature Request]: Can you consider to add Java 8 support？

### ISSUE THREAD

**Issue by heator** [Stirling-Tools/Stirling-PDF#1583]
### Feature Description

Can you consider to add Java 8 support？Java 21 is too much progressive and basically no one uses it. The present environment requirement (Java 21) will hinder a great number of users to access this pdf software. Can you consider to add Java 8 support (most users use Java 8)? Thanks!

### Why is this feature valuable?

Java 21 is too much progressive and basically no one uses it. The present environment requirement (Java 21) will hinder a great number of users to access this pdf software. Conversely, most users use Java 8 or Java 11.

### Suggested Implementation

Can you consider to add Java 8 support (most users use Java 8)? Thanks!

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

**Comment by Frooodle** [comment]
We support 17 and 21 

But no we are using some dependencies that require 17 or higher sadly
