### ISSUE TITLE
[Feature Request]: OCR language support

### ISSUE THREAD

**Issue by mhasanunal** [Stirling-Tools/Stirling-PDF#1594]
### Feature Description

As per I see, there is only one choice of OCR and it doesn't cover for any language  but English. 

Currently OCRmyPDF uses Tesseract, and Tesseract indeed support multiple languages...

### Why is this feature valuable?

Current OCR solution doesn't support Turkish Language.

### Suggested Implementation

Language Agnostic OCR input (Let tesseract do the job)

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

**Comment by Frooodle** [comment]
We support all languages, just not out of box, on the OCR page at bottom there should be a link on how to use OCR which goes over how to add all languages to it etc

**Comment by Frooodle** [comment]
They link to
https://github.com/Stirling-Tools/Stirling-PDF/blob/main/HowToUseOCR.md
