### ISSUE TITLE
Stirling-PDF as a service and enableLogin  Help

### ISSUE THREAD

**Issue by bert3ch** [Stirling-Tools/Stirling-PDF#1595]
Hello, I have made a local installation, also enable the Stirling-PDF as a service it was working but suddenly it stopped working even the systemctl status is active, when I run manually with ./gradlew bootRun, it works
Also enableLogin is set to true but I can not login.

any suggestions?  Thanks

**Comment by Ludy87** [comment]
Can you describe "I can not login" in more detail? there are errors in the log file?

**Comment by bert3ch** [comment]
Hi,
Login issue is , in the settings.yml file, initialLoginn username and password are set. However it does not accept the credentials , just default credentials (admin-stirling) working.
as I mentioned earlier, the systemctl status stirlingpdf.service is active but I am not able to open the Stirling page thorugh browser. I have to manually start it through /gradlew bootRun. How can I fix it? Please find attached screenshot of the log file.
![log](https://github.com/user-attachments/assets/b997aa9e-db14-44dd-8f4e-63cac01ead47)

**Comment by Ludy87** [comment]
Hi, in your screenshot you can see that you have used or set the user berto. So it must work with that too.

Regarding your second problem, I can only speculate and say that you may be using the wrong IP address and/or the wrong port when accessing it.

**Comment by bert3ch** [comment]
Hi again,
if I run it with /gradlew bootRun. ,I am able to access. but if the server restarts and and even status is Stirling service active it does not come up. I have to run it manually. 
the username is berto, you are right but it does not allow me to log in. It says wrong username or password

**Comment by Frooodle** [comment]
For logs can you provide a full txt file, will greatly help in debugging

**Comment by bert3ch** [comment]
Hello,Thank you for your reply.
 It will be a silly question [ as I m not pro:) ] but, when the program runs as a service, it uses the /opt/Stirling-PDF/configs/custom_settings.yml + settings.yml file. Is it correct? I think answer is yes, this was why I couldn't access app through web, because ports are different in  /opt/Stirling-PDF/configs/custom_settings.yml and .git/Stirling-PDF/configs/custom_setting.yml.
However, still I am not able to login with initial username and password. it does not accept Which log file would you like me to send?

**Comment by bert3ch** [comment]
Hello,
I am still facing the same issue.
