### ISSUE TITLE
[Feature Request]: enhance CSV excel conversion 

### ISSUE THREAD

**Issue by Frooodle** [Stirling-Tools/Stirling-PDF#1614]
### Feature Description

use https://github.com/tabulapdf/tabula-java

### Suggested Implementation

use https://github.com/tabulapdf/tabula-java

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

**Comment by azertylr** [comment]
You can also use: https://github.com/atlanhq/camelot

**Comment by omar-ahmed42** [comment]
Can I work on this issue?

**Comment by Frooodle** [comment]
Yes!
