### ISSUE TITLE
[Bug]: auto-rename fails if an image appears before any text

### ISSUE THREAD

**Issue by ag-gaphp** [Stirling-Tools/Stirling-PDF#1618]
### The Problem

I am using auto-rename as part of a pipeline that does two operations:
1. Split each page of a 3-page PDF
2. Rename each page according to the largest font-size text

Only 1 of the 3 pages gets renamed.

### Version of Stirling-PDF

0.26.1

### Page Where the Problem Occurred

/pipeline

### Relevant Log Output

```txt
spdf  | 14:33:52.999 [qtp1710180594-28] INFO  s.s.S.c.a.misc.AutoRenameController - File has no good title to be found
spdf  | 14:33:53.069 [qtp1710180594-27] INFO  s.s.S.c.a.misc.AutoRenameController - File has no good title to be found
spdf  | 14:33:53.218 [qtp1710180594-27] INFO  s.s.S.c.a.misc.AutoRenameController - File has no good title to be found
```

### Additional Information

One of my pages works without issue. It finds the largest text at the top of my page and renames the split file accordingly. The other 2 pages do not get renamed, even if I set the boolean for `useFirstTextAsFallback` to `true`. These three pages have a logo in the top left, where as the page that works properly has the logo in the top-right instead. Otherwise, my titles are all setup identically with the same font-size, style, and location on the page.

Here is an example PDF. Page 2 gets renamed properly, but pages 1 and 3 do not.
[auto_rename_example.pdf](https://github.com/user-attachments/files/16458160/auto_rename_example.pdf)

This is the json for the pipeline as generated by the `/pipeline` endpoint

```json
{
  "name": "Split Enrollment Packet",
  "pipeline": [
    {
      "operation": "/api/v1/general/split-pages",
      "parameters": {
        "pageNumbers": "1,2,3",
        "fileInput": "automated"
      }
    },
    {
      "operation": "/api/v1/misc/auto-rename",
      "parameters": {
        "useFirstTextAsFallback": true,
        "fileInput": "automated"
      }
    }
  ],
  "_examples": {
    "outputDir": "{outputFolder}/{folderName}",
    "outputFileName": "{filename}-{pipelineName}-{date}-{time}"
  },
  "outputDir": "{outputFolder}",
  "outputFileName": "{filename}"
}
```

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by Frooodle** [comment]
should be fixed when new release comes out, let me know!
