### ISSUE TITLE
[Feature Request]: Convert BASE64 to PDF

### ISSUE THREAD

**Issue by magaiverpr** [Stirling-Tools/Stirling-PDF#1634]
### Feature Description

We store some images and archives in base64 inside a database, and we need to convert to PDF this files manually.

It will be awesome if Stirling could convert the files, and provide an API to this.

### Suggested Implementation

Some documentations: https://base64.guru/converter/decode/pdf

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

**Comment by Frooodle** [comment]
Is this a PDF file which was converted to Base64 at some point? 
So the file itself is a fully valid PDF file just encoded to Base64?

This seems like a very niche feature that I cant see applicable to many users, Why was this converted to Base64 in first place, what was the usecase?

**Comment by PingLin8888** [comment]
> Is this a PDF file which was converted to Base64 at some point? So the file itself is a fully valid PDF file just encoded to Base64?
> 
> This seems like a very niche feature that I cant see applicable to many users, Why was this converted to Base64 in first place, what was the usecase?

Hi, could you assign this issue to me? I’d like to work on it.

**Comment by magaiverpr** [comment]
> Is this a PDF file which was converted to Base64 at some point? So the file itself is a fully valid PDF file just encoded to Base64?
> 
> This seems like a very niche feature that I cant see applicable to many users, Why was this converted to Base64 in first place, what was the usecase?

Hello,

We convert PDFs to base64 to store them "as text" in a database, then we need to decript to see the content of the PDF.

**Comment by sbplat** [comment]
> > Is this a PDF file which was converted to Base64 at some point? So the file itself is a fully valid PDF file just encoded to Base64?
> > This seems like a very niche feature that I cant see applicable to many users, Why was this converted to Base64 in first place, what was the usecase?
> 
> Hello,
> 
> We convert PDFs to base64 to store them "as text" in a database, then we need to decript to see the content of the PDF.

Why not just decode the PDF the same way it was encoded?

**Comment by leonbrehme** [comment]
@PingLin8888 maybe this is your solutions: https://it-tools.tech/base64-file-converter

As this is a not a non-technical-user issue, i can understand why it should not be added.
