### ISSUE TITLE
Extract pages via API

### ISSUE THREAD

**Issue by reikjarloekl** [Stirling-Tools/Stirling-PDF#1637]
### Feature Description

Enable extraction of pages through the API. 
Currently there is no endpoint for this feature that is available in the web front end. 

### Why is this feature valuable?

I frequently need to extract the first page of a PDF document programatically. 

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

**Comment by Frooodle** [comment]
/api/v1/general/rearrange-pages
should work fine

it can be used as
6,1,4

but to "extract pages" 
you can just use this as
1,5,7,8,10-15 etc to extract those pages into a new pdf

**Comment by Frooodle** [comment]
In your usecase of wanting first page just entering 1 should work

**Comment by Frooodle** [comment]
extract-page on UI side calls rearrange-pages in backend

**Comment by reikjarloekl** [comment]
@Frooodle Awesome, thanks for that super quick response! 🤩
