### ISSUE TITLE
Features missing from PDF24

### ISSUE THREAD

**Issue by trytomakeyouprivate** [Stirling-Tools/Stirling-PDF#165]
This is just a small list of all the features PDF24 supports, and this tool doesnt, yet.

PDF24 also uses lots of FOSS tools, but its not FOSS itself and not available on Linux at all.

- [x] website to PDF
- [x] PDF editor (maybe integrate Firefoxes PDF.js ?)
- [x] rate PDFs (nessecary? Metadata editor supported)
- [ ] create PDF from Photo / with camera (editing, maybe OCR)
- [x] add Page numbers
- [x] PDF Viewer (Again use Firefox pdf.js)
- [x] Layer PDFs (low priority? edgy use case)
- [x] optimize PDF (lowlevel probably artefact removal, compression, readability)
- [x] Black out (Firefox pdf.js ? Textmarker in black, also freeform shapes in black. Maybe a different mode in Firefox pdf.js, could redirect there

And also it seems there are already some features not supported by PDF24! like

- changing permissions
- standalone Metadata editor
- Some conversion options like RTF, XML, PDF/A, Presentation, Word formats
- flatten a PDF
- remove blank pages

Great work! Literally just the last step, as there are nearly all Tools on Linux, combining them in a simple user interface.

**Comment by webysther** [comment]
Maybe add some features from here: https://github.com/SimplePDF/simplepdf-embed

**Comment by Frooodle** [comment]
On 13 Jul 2023 00:42, Webysther Sperandio ***@***.***> wrote:
Maybe add some features from here: https://github.com/SimplePDF/simplepdf-embed

**Comment by Frooodle** [comment]
> Hi there!
> 
> _I'm Ben, the developer behind SimplePDF, @webysther pinged me to possibly collaborate on Stirling-PDF_
> 
> Happy to assist you with implementing SimplePDF in Stirling-PDF!
> 
> Do note however that telemetry data as well as document metadata is sent to the SimplePDF server, which would go against this statement in the readme:
> 
> > Stirling PDF makes no outbound calls for any record keeping or tracking.
> 
> 

Appreciate the offer! Sadly IFrame route etc is not where I want to take this app. As you found I ideally want spdf to keep everything local without external calls 

I greatly appreciate the offer though!

**Comment by trytomakeyouprivate** [comment]
yes the simplepdf editor is nice. But pdf.js is already implemented which would cause some deduplication

**Comment by Frooodle** [comment]
Think we are good for this now, i dont expect to ever have create pdf from photo unless its a standalone request for something unique!
we made some good progress
