### ISSUE TITLE
[Bug]: 'entityManagerFactory' that could not be found.

### ISSUE THREAD

**Issue by MuazAshraf** [Stirling-Tools/Stirling-PDF#1664]
### The Problem

I have install stirling-pdf locally on mac using their md file and I successfully do that and it is running. For automatically(KM) running I create a sh file and write this cd project directory
./gradlew bootRun

I am testing the features again, I ran into new issues like this this is not in the directory but it is present. And then it stops running.

### Version of Stirling-PDF

0.26.1

### Relevant Log Output

```txt
***************************
APPLICATION FAILED TO START
***************************

Description:

Field userRepository in stirling.software.SPDF.config.security.CustomUserDetailsService required a bean named 'entityManagerFactory' that could not be found.

The injection point has the following annotations:
        - @org.springframework.beans.factory.annotation.Autowired(required=true)

Action:
Consider defining a bean named 'entityManagerFactory' in your configuration.
```

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by Ludy87** [comment]
Please try again with the new version https://github.com/Stirling-Tools/Stirling-PDF/releases/tag/v0.27.0
