### ISSUE TITLE
[Bug]: PDF page remover is prompting for a file upload for specifying pages to remove rather than allowing input.

### ISSUE THREAD

**Issue by BurningSmile** [Stirling-Tools/Stirling-PDF#1692]
### The Problem

Currently the pdf page remover tool is prompting for a file to be uploaded for specifying what pages to remove. I'm assuming this is a bug and should instead be a text input field, similar to what's on split tool.

![image](https://github.com/user-attachments/assets/4e0290e3-3b4e-4bef-a331-7709cb1fe10d)

### Version of Stirling-PDF

0.27.0

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by Frooodle** [comment]
duplicate issue already raised, issue should be resolved in next update
