### ISSUE TITLE
[Feature Request]: Disable failed login counter

### ISSUE THREAD

**Issue by ambroisie** [Stirling-Tools/Stirling-PDF#1738]
### Feature Description

I want to use Fail2Ban to have a centralized system to take care of malicious login attempts, rather than leave each app to fend for itself. To that end, I would rather avoid setting up any limits to the failed login attempt workflow, as I would then need to sync between Fail2Ban and Stirling PDF to make sure it is working properly.

### Why is this feature valuable?

It's valuable for people who want to use an externalized filtering system.

### Suggested Implementation

Accept 0 or -1 as a value for this setting, which would disable any limits.

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

**Comment by Ludy87** [comment]
Hi @ambroisie  there is no need to integrate a new function, you can use existing method.

set `loginAttemptCount` `-1`

**Comment by ambroisie** [comment]
Ah thank you. I guess this issue is now about documenting this behavior, as I couldn't find how to disable it.

**Comment by Ludy87** [comment]
Sorry, that wasn't the way to go - I had set my reset time too low and it had already reset. But I'll take care of it.
