### ISSUE TITLE
[CSS Bug]: Tooltip support can be added for Theme & Settings in Navigation bar

### ISSUE THREAD

**Issue by Vamsi1810** [Stirling-Tools/Stirling-PDF#1801]
### Installation Method

Docker

### The Problem

![image](https://github.com/user-attachments/assets/9029c0c9-d07a-4058-a7e0-273b54574bc1)
Tooltip support can be added for highlighted areas in the navigation bar

### Version of Stirling-PDF

0.28.3

### Page Where the Problem Occurred

http://localhost:8080/

### Browsers Affected

Chrome

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by Frooodle** [comment]
If you are proficient in CSS you are welcome to resolve these in PR !

**Comment by xiangdyzz** [comment]
Hi @Frooodle , could you please clarify what specific tooltips you would like to see for the highlighted areas in the navigation bar? This will help me ensure the implementation meets your expectations. Thank you!
