### ISSUE TITLE
[CSS Bug]: Search card should be expanded dynamically based on the text entered.

### ISSUE THREAD

**Issue by Vamsi1810** [Stirling-Tools/Stirling-PDF#1802]
### Installation Method

Docker

### The Problem

![image](https://github.com/user-attachments/assets/c3633bf8-ef5f-4bb9-8ded-e737c3d1a839)
On clicking search icon, the card should expand dynamically based on the results. the search results card should not be with the static size.

### Version of Stirling-PDF

0.28.3

### Browsers Affected

Chrome

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by bxjyj** [comment]
I would like to be assigned this issue

**Comment by Frooodle** [comment]
Also would be good to have the search bar auto selected when you hit search button, so that you don't need to click twice to search
