### ISSUE TITLE
[CSS Bug]: App Name & Back to Home page button was invisible at View pdf page (text & icon color change required) 

### ISSUE THREAD

**Issue by Vamsi1810** [Stirling-Tools/Stirling-PDF#1817]
### Installation Method

Docker

### The Problem

![image](https://github.com/user-attachments/assets/e948df9c-8d5e-4f5f-b11c-0316b8a7ebe0)
The Text in the marked area was invisible. Change the color of the text to make it visible.

### Version of Stirling-PDF

0.28.3

### Page Where the Problem Occurred

http://localhost:8080/view-pdf

### Browsers Affected

Chrome

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by Vamsi1810** [comment]
![image](https://github.com/user-attachments/assets/b48902df-b244-443b-82b0-76306dc183b1)
Icon color change required

**Comment by NPKLTacocat** [comment]
Can I get assigned to this, I would like to take a shot at it

**Comment by Frooodle** [comment]
Sorry didnt see this message i can assign to you if you are still interested?

**Comment by sorydi3** [comment]
assign it to me, if it's still available.

**Comment by amankhangit** [comment]
![Screenshot 2024-09-22 232320](https://github.com/user-attachments/assets/33246226-36b9-442d-9dfb-637d83306e2e)
Is this issue fixed?

**Comment by Frooodle** [comment]
https://github.com/Stirling-Tools/Stirling-PDF/pull/1948
