### ISSUE TITLE
[CSS Bug]: Favourite Icon can be highlighted with yellow color when selected

### ISSUE THREAD

**Issue by Vamsi1810** [Stirling-Tools/Stirling-PDF#1818]
### Installation Method

Docker

### The Problem

![image](https://github.com/user-attachments/assets/529a0e6e-f7ec-4823-9615-27e5c53aff42)
Favorite icon can be highlighted with yellow color when clicked on it. At present, it was tough enough to identify the change whether favorite icon was enabled or no

### Version of Stirling-PDF

0.28.3

### Page Where the Problem Occurred

http://localhost:8080/

### Browsers Affected

Chrome

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by Frooodle** [comment]
Would prefer a dark fill star not yellow due to contrast of colour

**Comment by landonmcintosh** [comment]
I would like to be assigned this issue!
