### ISSUE TITLE
[CSS Bug]: Card size and placement of Download button should be improved

### ISSUE THREAD

**Issue by Vamsi1810** [Stirling-Tools/Stirling-PDF#1819]
### Installation Method

Docker

### The Problem

![image](https://github.com/user-attachments/assets/d2e9c3d6-8224-4d97-b257-6c9cb74938ef)
Download button should be in the center position.
Card size can be reduced to appropriate size. Unnecessary space was getting occupied. To maintain uniformity among the pages, card size can be reduced.

### Version of Stirling-PDF

0.28.3

### Page Where the Problem Occurred

http://localhost:8080/adjust-contrast

### Browsers Affected

Chrome

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by Geaboi** [comment]
Hi I would like to be assigned this issue.

**Comment by dk-talks** [comment]
Hi @Geaboi Are you working on this issue right now? If no, please let me know.

**Comment by Geaboi** [comment]
Yes I am still working on it

**Comment by Frooodle** [comment]
Seems issued is fixed, button is to left aligning with other pages
