### ISSUE TITLE
[CSS Bug]: Reduce extra space between input field & button

### ISSUE THREAD

**Issue by Vamsi1810** [Stirling-Tools/Stirling-PDF#1829]
### Installation Method

Docker

### The Problem

![image](https://github.com/user-attachments/assets/3783bddb-26e8-4f5b-a070-7b8dc6ac8c4d)

### Version of Stirling-PDF

0.28.3

### Page Where the Problem Occurred

http://localhost:8080/remove-image-pdf

### Browsers Affected

Chrome

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by dk-talks** [comment]
<img width="1426" alt="Screenshot 2024-09-08 at 12 41 08 PM" src="https://github.com/user-attachments/assets/47d93e54-1c4f-4136-a63c-3b008223a7d0">

Hi @Vamsi1810, if we try to remove the extra space, there won't be any space left for the progress bar and the "Bored Waiting" button in case the algorithm takes more time. So, either we keep it as it is, or if the space looks unattractive, we can shift the "Bored Waiting" button to the right side.

**Comment by Frooodle** [comment]
"Or let me increase the space when the progress bar and "Bored Waiting?" button appears."
I think this makes sense, dynamically add spacing based on the elements being added/removed

**Comment by dk-talks** [comment]
Working on it, will create a PR once I complete it. Thanks
