### ISSUE TITLE
[CSS Bug]: Stamp pdf page improvements

### ISSUE THREAD

**Issue by Vamsi1810** [Stirling-Tools/Stirling-PDF#1830]
### Installation Method

Docker

### The Problem

![image](https://github.com/user-attachments/assets/2a57ca0f-6f21-40e2-8168-ad5489dd9671)
1. Gap can be reduced in the highlighted area
2. it would be good if we move the border for custom text color.

### Version of Stirling-PDF

0.28.3

### Page Where the Problem Occurred

http://localhost:8080/stamp

### Browsers Affected

Chrome

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by designtesbrot** [comment]
@Frooodle while https://github.com/Stirling-Tools/Stirling-PDF/pull/1848 has fixed the spacing, the border situation is still a thing. I am happy to tidy that up, can you assign the issue to me?

**Comment by designtesbrot** [comment]
@Vamsi1810 I have a PR pending. It includes a video of the fix. Could you quickly confirm that this is what you would visualy expect? https://github.com/Stirling-Tools/Stirling-PDF/pull/1862 Thank you
