### ISSUE TITLE
[CSS Bug]: Split pdf by size page improvements

### ISSUE THREAD

**Issue by Vamsi1810** [Stirling-Tools/Stirling-PDF#1831]
### Installation Method

Docker

### The Problem

![image](https://github.com/user-attachments/assets/9dff0156-b842-4347-96f4-c204b4d5b16d)
Spacing should be maintained uniformly at highlighted sections

### Version of Stirling-PDF

0.28.3

### Page Where the Problem Occurred

http://localhost:8080/overlay-pdf

### Browsers Affected

Chrome

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by DrSommer20** [comment]
Hello, 
I would like to take on that Problem
