### ISSUE TITLE
[CSS Bug]: Spacing should be maintained uniformly across highlighted areas.

### ISSUE THREAD

**Issue by Vamsi1810** [Stirling-Tools/Stirling-PDF#1832]
### Installation Method

Docker

### The Problem

![image](https://github.com/user-attachments/assets/e25cee79-353f-4971-a80e-d7156459027d)

### Version of Stirling-PDF

0.28.3

### Page Where the Problem Occurred

http://localhost:8080/split-by-size-or-count

### Browsers Affected

Chrome

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by designtesbrot** [comment]
I believe this is fixed by https://github.com/Stirling-Tools/Stirling-PDF/pull/1848. Can not reproduce on latest main anymore (that is commit 291bad)

**Comment by Frooodle** [comment]
Agreed I have asked he same here
https://github.com/Stirling-Tools/Stirling-PDF/issues/1847#issuecomment-2336797462

I believe a large amount of these tickets can be closed
