### ISSUE TITLE
[CSS Bug]: Reduce card size in "Get info on PDF page"

### ISSUE THREAD

**Issue by Vamsi1810** [Stirling-Tools/Stirling-PDF#1834]
### Installation Method

Docker

### The Problem

![image](https://github.com/user-attachments/assets/a85003e7-aeab-4aca-a89f-d33a4e72d7ca)

### Version of Stirling-PDF

0.28.3

### Page Where the Problem Occurred

http://localhost:8080/get-info-on-pdf

### Browsers Affected

Chrome

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by Frooodle** [comment]
We dont want the gap to small either though :P
