### ISSUE TITLE
[CSS Bug]: Maintain Uniform Gap in "Markdown to PDF page" 

### ISSUE THREAD

**Issue by Vamsi1810** [Stirling-Tools/Stirling-PDF#1835]
### Installation Method

Docker

### The Problem

![image](https://github.com/user-attachments/assets/52505459-d560-4292-9ae1-06a22dcccb88)

### Version of Stirling-PDF

0.28.3

### Page Where the Problem Occurred

http://localhost:8080/markdown-to-pdf

### Browsers Affected

Chrome

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by aditya76-webdev** [comment]
Hii @Frooodle can you assign this to me ??

**Comment by Vamsi1810** [comment]
resolved
