### ISSUE TITLE
[CSS Bug]: Highlighted gaps can be reduced at PDF to XML page

### ISSUE THREAD

**Issue by Vamsi1810** [Stirling-Tools/Stirling-PDF#1847]
### Installation Method

Docker

### The Problem

![image](https://github.com/user-attachments/assets/709e8b06-3c79-4282-b497-94957d8d4bad)

### Version of Stirling-PDF

0.28.3

### Page Where the Problem Occurred

http://localhost:8080/pdf-to-xml

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by Frooodle** [comment]
@Vamsi1810  a lot of these should get fixed with the same changes with progress bar and things that were made dynamic

**Comment by Frooodle** [comment]
Can you pull the most recent changes merged from https://github.com/Stirling-Tools/Stirling-PDF/pull/1848

I believe it should close quite a few of these tickets
