### ISSUE TITLE
Problems after Docker deployment

### ISSUE THREAD

**Issue by taohe009** [Stirling-Tools/Stirling-PDF#1852]
### Feature Description

After Docker deployment is completed, my website domain name is successfully bound and the website runs successfully, but there is no management backend?

I would like to ask, I want to change the Stirling PDF on the homepage to my own name, where can I modify it? ?

Where can I modify the LOGO? Where can I add advertising code in the future? ? Give a user click

Without these management functions, you can't make a profit after deployment and construction? ?

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

**Comment by Frooodle** [comment]
You can customise logo and such, information is in readme, but we have no plans to support users easily adding monitisation etc

**Comment by taohe009** [comment]
docker run -d \
-p 8080:8080 \
-v /location/of/ trainingData :/ usr /share/ tessdata
- v ./extraConfigs : / configs\
-v ./logs:/logs \
- v . /location/of/ customFiles :/ customFiles \
-e DOCKER_ENABLE_SECURITY=false \
-e INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false \
-e LANGS= en_GB \
--name stirling -pdf \
frooodle / s- pdf:latest

Please check if the command I run in this container is correct? Or is it like the following?

docker run -d \
-p 8080:8080 \
-v /location/of/ trainingData :/ usr /share/ tessdata
- v ./extraConfigs : / configs\
-v ./logs:/logs \
- v ./customFiles:/customFiles/
-e DOCKER_ENABLE_SECURITY=false \
-e INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false \
-e LANGS= en_GB \
--name stirling -pdf \
frooodle / s- pdf:latest

Like this? Or like this? :

docker run -d \
-p 8080:8080 \
-v /location/of/ trainingData :/ usr /share/ tessdata
- v ./extraConfigs : / configs\
-v ./logs:/logs \
- v ./customFiles / templates: / customFiles /
-e DOCKER_ENABLE_SECURITY=false \
-e INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false \
-e LANGS= en_GB \
--name stirling -pdf \
frooodle / s- pdf:latest

Or like this :

docker run -d \
-p 8080:8080 \
-v /location/of/ trainingData :/ usr /share/ tessdata
- v ./extraConfigs : / configs\
-v ./logs:/logs \
/ customFiles /templates:/templates
-e DOCKER_ENABLE_SECURITY=false \
-e INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false \
-e LANGS= en_GB \
--name stirling -pdf \
frooodle / s- pdf:latest
