### ISSUE TITLE
[Bug]: BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 67 > Unsupported class file major version 67

### ISSUE THREAD

**Issue by LeviAckerman666** [Stirling-Tools/Stirling-PDF#1853]
### Installation Method

Local Installation

### The Problem

./gradlew build        

FAILURE: Build failed with an exception.

* What went wrong:
BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 67
> Unsupported class file major version 67

### Version of Stirling-PDF

0.28.3

### Relevant Log Output

```txt
BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 67
```

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by Frooodle** [comment]
I believe you have the wrong version of java installed and/or JAVA_HOME is set to wrong java version

**Comment by LeviAckerman666** [comment]
Yes that was the problem.. I was using a wrong version of java than you
