### ISSUE TITLE
[CSS Bug]: Card length & width should be expanded dynamically in PDF Multi tool 

### ISSUE THREAD

**Issue by Vamsi1810** [Stirling-Tools/Stirling-PDF#1857]
### Installation Method

Docker

### The Problem

![image](https://github.com/user-attachments/assets/b48ea4d0-766a-4c5b-9a0b-7befc3c5d776)

### Version of Stirling-PDF

0.28.3

### Page Where the Problem Occurred

http://localhost:8080/multi-tool

### Browsers Affected

Chrome

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by TamsilAmani** [comment]
Can you explain more about the issue? What does 'dynamically' signify here? Is it the resizing of the browser window or do you mean that the width of the card must be expanded depending on the size of the file name or anything else? @Vamsi1810

**Comment by Frooodle** [comment]
Hmm i Dont think i actually agree with this issue ticket in first place, reducing this size makes it near unusable
