### ISSUE TITLE
[CSS Bug]: Highlighted gap should be reduced in image to pdf page

### ISSUE THREAD

**Issue by Vamsi1810** [Stirling-Tools/Stirling-PDF#1858]
### Installation Method

Docker

### The Problem

![image](https://github.com/user-attachments/assets/27da6381-3232-4bd9-aaa4-a5df617b3910)

### Version of Stirling-PDF

0.28.3

### Page Where the Problem Occurred

http://localhost:8080/img-to-pdf

### Browsers Affected

Chrome

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by DrSommer20** [comment]
Hi,
would like to fix this with #1860 and #1859

**Comment by Frooodle** [comment]
sounds good!
