### ISSUE TITLE
[Bug]: Submit button on each card should be aligned to left for each pdf operation

### ISSUE THREAD

**Issue by Vamsi1810** [Stirling-Tools/Stirling-PDF#1881]
### Installation Method

Docker

### The Problem

At present in some pdf operation pages, the submit button was aligned in the center.
![image](https://github.com/user-attachments/assets/3e8511f4-fe4b-4dbf-88c9-67248840554f)
These should be moved to left corner and should be aligned with the input field

### Version of Stirling-PDF

0.28.3

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by Ahar28** [comment]
Hi @Vamsi1810 , could you please assign it to me ? I would like to work on it.
