### ISSUE TITLE
[Feature Request]: command flag to use the next available port

### ISSUE THREAD

**Issue by knyipab** [Stirling-Tools/Stirling-PDF#1882]
### Feature Description

Perhaps a `--port <port_num>` commandline option. And specifying `--port auto` will find the next available port that is larger than 8080. 

### Why is this feature valuable?

8080 port is way to common for web apps. I well understand that docker can do port forwarding. However, there are non-docker user, as well as OS/arch that could not quite use docker e.g. arm board and Termux. It would be really helpful if there could be a flag to find and use the next available port, which is what app like jupyterlab behave. User can simply click the link shown in terminal to open webui. User can simply click the link shown in terminal to open webui. 

Now I actually use below script to detect link and start the styling-pdf when it is ready. It seems better than opening the browser before the server is even ready
```
url_opened=false
cd "/usr/var/lib/stirling-pdf"

exec $JAVA_HOME/bin/java --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.desktop/javax.swing=ALL-UNNAMED -jar /usr/share/stirling-pdf/stirling-pdf-0.28.3.jar "$@" | while IFS= read -r line; do
echo "$line"
if echo "$line" | grep -qE 'http://localhost:[0-9]+'; then
url=$(echo "$line" | grep -oE 'http://localhost:[0-9]+')
if [ "$url_opened" = false ]; then
-xdg-open "$url"
url_opened=true
fi
fi
done

```

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

**Comment by Akhil-2020171** [comment]
I can integrate the command line flag for port functionality in the existing project. Please assign it to me.

**Comment by sbplat** [comment]
Sure, I've assigned this issue to you! If you have any questions, please feel free to ask.

**Comment by akashsin63** [comment]
Hello Akhil are you still working on this issue ??
I know the fix for this let me know if you are interested let me know we can discuss the fix for this .

**Comment by Akhil-2020171** [comment]
Hi Akash, I have already released the pull request, which has been approved.  The changes will be merged shortly.

**Comment by Akhil-2020171** [comment]
> Hello Akhil are you still working on this issue ?? I know the fix for this let me know if you are interested let me know we can discuss the fix for this .

Hi Akash, I have already released the pull request, which has been approved. The changes will be merged shortly.
