### ISSUE TITLE
[Feature Request]: PDF editor using a selfhosting onlyoffice server

### ISSUE THREAD

**Issue by knyipab** [Stirling-Tools/Stirling-PDF#1883]
### Feature Description

A new function to edit and insert texts, images, tables and more, more than just commenting. Such feature can be done with a selfhosting onlyoffice pdf editor. 

### Why is this feature valuable?

The most recent onlyoffice server provides a pdf editor: https://www.onlyoffice.com/pdf-editor.aspx

If I'm not mistaken, stirling-pdf is a project that incorporates several different open source pdf tools. Wouldn't it be really great for stirling-pdf to operate with a selfhosting onlyoffice server and link to their pdf editor? Other open source projects, such as nextcloud, does similar integration. 

### Suggested Implementation

refer to cloud project like nextcloud

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

**Comment by Frooodle** [comment]
Yes we use other open source apps
this is not open source and we want to keep everything locally hosted not link externally

**Comment by archef2000** [comment]
The only office server is AGPL: https://github.com/ONLYOFFICE/DocumentServer/blob/master/LICENSE.txt

**Comment by knyipab** [comment]
Just like stirling-pdf, onlyoffice server is open source and available on docker and Archlinux AUR. They are also available on snapcraft, Ubuntu PPA and more.
