### ISSUE TITLE
[Bug]: [Remove Image] There were few areas, when image gets removed, we were seeing blue tile, but some areas we were seeing white tile

### ISSUE THREAD

**Issue by Vamsi1810** [Stirling-Tools/Stirling-PDF#1896]
### Installation Method

Docker

### The Problem

You can take the attached pdf for reference : 
[presentation.pdf](https://github.com/user-attachments/files/17003182/presentation.pdf)
Attaching the removed images pdf also to show where was the difference : 
[presentation_removed_images.pdf](https://github.com/user-attachments/files/17003184/presentation_removed_images.pdf)
in page 6 of removed images pdf, there are blue tile when image was removed.
where as in page 7 , we don't see any blue tile when image was removed. 

please maintain uniformity when images are getting removed.

### Version of Stirling-PDF

0.28.3

### Page Where the Problem Occurred

http://localhost:8080/remove-image-pdf

### Browsers Affected

Firefox, Chrome, Safari, Microsoft Edge, Other

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by Frooodle** [comment]
I can confirm the same with other tools, this PDF actually has the colour blue behind these images

**Comment by Frooodle** [comment]
its correctly showing what is behind the image itself

**Comment by Frooodle** [comment]
Looks like its a blue "Crop box" used to crop images and or text as the images themselves in those blue boxes is actually bigger than shown, 
we cant tell if it would be used for text along side images or if the blue colour would be intended or not etc, we are correctly removing the image

**Comment by Frooodle** [comment]
as example of crop box
![image](https://github.com/user-attachments/assets/0f7f03dc-bafd-490b-954d-3eeb82275d54)
 vs
 actual photo being 
![image](https://github.com/user-attachments/assets/ee9a0bda-dca6-4671-b657-404d7299d015)
