### ISSUE TITLE
[CSS Bug]: Multi-tool vertical scrolling doesnt work when mouse over PDFs

### ISSUE THREAD

**Issue by Frooodle** [Stirling-Tools/Stirling-PDF#1898]
### Installation Method

None

### The Problem

Multi-tool vertical scrolling doesnt work when mouse over PDFs

### Version of Stirling-PDF

0.28.3

### Browsers Affected

Chrome

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by lionking102** [comment]
Same problem for me. This makes the multi-tool a bit annoying to use.
Despite that it is great now :)

**Comment by Frooodle** [comment]
For context this is caused by us used to supporting horizontal scrolling, and now its vertical, old code now causes issues
