### ISSUE TITLE
[Feature Request]: Flatten function to separate into "flatten" and "rasterise"

### ISSUE THREAD

**Issue by sjlai1993** [Stirling-Tools/Stirling-PDF#1906]
### Feature Description

I believe before an update, the flatten function only "flattens" the pdf and not converting it into image as per current implementation. 
However, I am not sure that the flatten function flattens only forms or also flatten pdf comments as well.

### Why is this feature valuable?

Flatten function without converting pdf into image will produce a pdf that is smaller in size but is still sufficient to deter most people from accidentally editing forms and pdf comments.

### Suggested Implementation

Suggest to add a "rasterise" check box at the current flatten function page for users that intend to create pdf that is converted into images if it is practical.

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

**Comment by Frooodle** [comment]
![image](https://github.com/user-attachments/assets/69a54587-52d2-4196-8195-7129e6b9d998)
"flattern only forms" actually means "Dont rasterise"  and do previous functionality

**Comment by sjlai1993** [comment]
Oh. Understood. 

May I know if the flatten using “flatten only forms” will also flatten pdf comments in previous version?

if it’s not, should I close this and create another new issue for that?

**Comment by Frooodle** [comment]
Honestly been a while since I used it 
You are best off testing and telling me 😂

**Comment by sjlai1993** [comment]
I have tried a pdf with “flatten only forms” and pdf comments are not flattened.

However, I am not sure to place "flattening pdf comments" under "enhancement" or "bug"
