### ISSUE TITLE
[Bug]: Missing Home Button in PDF Viewer Due to Nonexistent toolbarButton-home.svg File

### ISSUE THREAD

**Issue by ubbg** [Stirling-Tools/Stirling-PDF#1914]
### Installation Method

Docker

### The Problem

The Home Button of view-pdf is not displayed because the file toolbarButton-home.svg does not exist.

https://stirlingpdf.io/view-pdf

![image](https://github.com/user-attachments/assets/77a0b4ad-0cc7-4e88-8979-223abf3b5d20)

### Version of Stirling-PDF

0.29

### Browsers Affected

Chrome

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by ubbg** [comment]
The file

`src/main/resources/static/pdfjs-legacy/images/toolBarButton-home.svg`

needs to be renamed to

`src/main/resources/static/pdfjs-legacy/images/toolbarButton-home.svg`.

**Comment by HardikaZalavadia** [comment]
Hi, @Frooodle I want to work on this issue can you assign it to me?

**Comment by Frooodle** [comment]
Seems simple enough to do without assignment 
Welcome to raise PR
