### ISSUE TITLE
[Bug]: Create new OAUTH2 User - Requires Password

### ISSUE THREAD

**Issue by checkso** [Stirling-Tools/Stirling-PDF#1918]
### Installation Method

Docker

### The Problem

Trying to add a new user in the admin portal:
![image](https://github.com/user-attachments/assets/be285774-2f25-4419-b128-ca326855194a)

Error message:
![image](https://github.com/user-attachments/assets/956f1f05-0370-417d-a1e0-7a246b662f0d)

Container message:
`16:06:35.525 [qtp1511661742-33] WARN  o.s.w.s.m.s.DefaultHandlerExceptionResolver - Resolved [org.springframework.web.bind.MissingServletRequestParameterException: Required request parameter 'password' for method parameter type String is not present]`

### Version of Stirling-PDF

0.29.0

### Browsers Affected

Chrome

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by checkso** [comment]
Also the button "Stack-Trace anzeigen" (show) and "Stack-Trace kopieren" (copy) doesn't do anything

**Comment by Frooodle** [comment]
Will be fixed next update thanks for raising
