### ISSUE TITLE
[Bug]: Auto Redact without PDF-Image conversion causes error

### ISSUE THREAD

**Issue by cinderblockgames** [Stirling-Tools/Stirling-PDF#1941]
### Installation Method

Docker

### The Problem

Using Auto Redact without selecting the PDF to PDF-Image conversion doesn'tw ork.

### Version of Stirling-PDF

0.29.0

### Page Where the Problem Occurred

https://pdf.squeakers.space/api/v1/security/auto-redact

### Relevant Log Output

```txt
jakarta.servlet.ServletException: Request processing failed: java.lang.IllegalStateException: PDF contains an encryption dictionary, please remove it with setAllSecurityToBeRemoved() or set a protection policy with protect() for path: /api/v1/security/auto-redact
```

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by Frooodle** [comment]
Looking at your log you sent it appears the pdf is encrypted 

Are you saying this does work when you do pdf to image? 

Can you try send the pdf through remove password function (if you don't know password leave it blank)

**Comment by cinderblockgames** [comment]
That did it, t hank you!

Yes, it worked with pdf to image without having to go through the remove password function.
