### ISSUE TITLE
[Feature Request]: multi-tool.html should edit pdf metadata to change creator and producer to Stirling PDF

### ISSUE THREAD

**Issue by Frooodle** [Stirling-Tools/Stirling-PDF#1963]
### Feature Description

multi-tool.html should edit pdf metadata to change creator and producer to Stirling PDF

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

**Comment by Akhil-2020171** [comment]
Can I work on this? (if no one has been assigned yet)

**Comment by Akhil-2020171** [comment]
I have made changes according to the requirements. Am I allowed to create a pull request?

**Comment by Frooodle** [comment]
Works been completed by me in local sorry about hat

**Comment by Akhil-2020171** [comment]
ok no worry, I am creating a pull request for this, discard the pull request if you want.
