### ISSUE TITLE
[Feature Request]:  I don't see the OCR function

### ISSUE THREAD

**Issue by YJL12345** [Stirling-Tools/Stirling-PDF#1968]
### Feature Description

I saw other suggestions "I propose adding support for configuring the tessdata path specifically for local Windows users within the application." The author answered that it has been completed, but I don't see the OCR function. It seems to be a problem with "/usr/share/tessdata". I dare not move Tesseract. I have been using OCRmyPDF with PowerShell. I am worried that there will be problems. Have I understood all this wrongly?

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

**Comment by Frooodle** [comment]
Right now you would need to use the.jar not the .exe
