### ISSUE TITLE
[Feature Request]: Operations on multiple pages in Multitool

### ISSUE THREAD

**Issue by Stroomtang** [Stirling-Tools/Stirling-PDF#1976]
### Feature Description

Be able to do the move, rotate or delete operations on multiple pages at once in the Multitool

### Why is this feature valuable?

At te moment you only can move, rotate and delete 1 page at a time in the Multitool. In larger files you'd want to do these operations on multiple pages at once. For instance moving 5 pages at the back to the front; now you have to move these one by one.

### Suggested Implementation

Select mutiple files by using the CTRL or SHIFT-buttons (don't know how well this would work on a webpage) or by providing a checkbox per page so you can select mutiple pages at once before moving/rotating/deleting them.

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

**Comment by Akhil-2020171** [comment]
is anyone working on this? If no I can work on this.

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by Stroomtang** [comment]
Looks very good, you can delete and rotate multiple pages at once now. But if I'm not mistaken **moving** multiple pages at once still isn't possible? Or did I miss how you can do this?
