### ISSUE TITLE
[Feature Request] Better logging for when File `download.htm` downloaded when server returns 413 Request Entity Too Large

### ISSUE THREAD

**Issue by timotheeandres** [Stirling-Tools/Stirling-PDF#199]
First, awesome project! I've been hoping for a self-hosted replacement of smallpdf, this might be it!

Now, I used the docker container for this, and tried to compress a PDF. However, clicking on "Compress" only resulted in a very light `download.htm` file being downloaded. Here was its content:
```html
<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.14.2</center>
</body>
</html>
```

I do not know if this issue also happens if nginx returns any other non-200 return code, but at least for this one, it could be nice to have some message printed on the page, a toast or a pop-up?

Thanks :)

**Comment by Frooodle** [comment]
https://github.com/Frooodle/Stirling-PDF#q3-why-is-my-application-downloading-htm-files

**Comment by timotheeandres** [comment]
Thank you for pointing out solutions! What I was suggesting with this issue was to rather have a small message displayed on the page when this happens, like "File too large"?

**Comment by Frooodle** [comment]
This is purely from Nginx side though, i am not sure if my app can grab that or change it

**Comment by Frooodle** [comment]
I dont think there is any way to hook this and get response other than on client side detect if output is htm.
Change wouldnt be server side

**Comment by timotheeandres** [comment]
Maybe some JS check when the button is clicked that the returned code is 2xx?

**Comment by neuhaus** [comment]
I've added pull request #2226 so the FAQ mentions HTTP error code 413 and the fix.
