### ISSUE TITLE
[Feature Request]: Sign multiple PDF pages at the same time in the same location

### ISSUE THREAD

**Issue by gavinfraser6** [Stirling-Tools/Stirling-PDF#2008]
### Feature Description

Have the ability to upload my signature and place it on the place where I want to sign the pdf document, then have an option to sign on that same place on every page in the PDF document.

### Why is this feature valuable?

It is very valuable where a person is required to initial a page on every page of the document.

### Suggested Implementation

Have an option to sign on that same place on every page in the PDF document.

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by thisisrenan** [comment]
Hi, can I work on this?

**Comment by gavinfraser6** [comment]
Good job, please check how landscape pages are being handled. I do not think it works with those as intended.
