### ISSUE TITLE
[Feature Request]: Using a Windows EXE file to start the system has limited functionality.

### ISSUE THREAD

**Issue by jacbo0112** [Stirling-Tools/Stirling-PDF#2010]
### Feature Description

Using a Windows EXE file to start the system has limited functionality. Where is the problem? Does the configuration file need to be modified
![image](https://github.com/user-attachments/assets/bc07aad3-16d2-45e3-97ea-55f4ef6d45da)

09:53:42.804 [main] INFO  s.s.S.config.EndpointConfiguration - Disabling file-to-pdf
09:53:42.807 [main] INFO  s.s.S.config.EndpointConfiguration - Disabling repair
09:53:42.809 [main] INFO  s.s.S.config.EndpointConfiguration - Disabling xlsx-to-pdf
09:53:42.810 [main] INFO  s.s.S.config.EndpointConfiguration - Disabling ocr-pdf
09:53:42.811 [main] INFO  s.s.S.config.EndpointConfiguration - Disabling pdf-to-pdfa
09:53:42.812 [main] INFO  s.s.S.config.EndpointConfiguration - Disabling pdf-to-word
09:53:42.815 [main] INFO  s.s.S.config.EndpointConfiguration - Disabling html-to-pdf
09:53:42.816 [main] INFO  s.s.S.config.EndpointConfiguration - Disabling book-to-pdf
09:53:42.821 [main] INFO  s.s.S.config.EndpointConfiguration - Disabling pdf-to-xml
09:53:42.822 [main] INFO  s.s.S.config.EndpointConfiguration - Disabling compress-pdf
09:53:42.824 [main] INFO  s.s.S.config.EndpointConfiguration - Disabling pdf-to-presentation
09:53:42.827 [main] INFO  s.s.S.config.EndpointConfiguration - Disabling url-to-pdf
09:53:42.828 [main] INFO  s.s.S.config.EndpointConfiguration - Disabling pdf-to-book
09:53:42.829 [main] INFO  s.s.S.config.EndpointConfiguration - Disabling pdf-to-rtf
09:53:42.837 [main] INFO  s.s.S.config.EndpointConfiguration - Disabling extract-image-scans
09:53:42.839 [main] INFO  s.s.S.config.EndpointConfiguration - Disabling pdf-to-html

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

**Comment by Frooodle** [comment]
These features are only available with additional dependencies some of which are Linux/docker only

**Comment by jacbo0112** [comment]
Thank you for your answer. If possible, please clearly indicate it in the readme
