### ISSUE TITLE
[Bug]: Please fix the problem of error 413 when using "Merge multiple PDFs (more than 2)" function, when the number of PDFs exceeds 4.

### ISSUE THREAD

**Issue by MchalTesla** [Stirling-Tools/Stirling-PDF#2024]
### Installation Method

Docker

### The Problem

Please fix the problem of error 413 when using "Merge multiple PDFs (more than 2)" function, when the number of PDFs exceeds 4.

### Version of Stirling-PDF

0.29.0

### Page Where the Problem Occurred

https://pdf.nilcloud.link/merge-pdfs

### Browsers Affected

Chrome

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by Frooodle** [comment]
Please lookat existing tickets for 413 issue
