### ISSUE TITLE
[Feature Request]: add to DeveloperGuide.md explaining thymeleaf and general steps on how to add new feature to stirling pdf and its API + UI

### ISSUE THREAD

**Issue by Frooodle** [Stirling-Tools/Stirling-PDF#2027]
### Feature Description

[Feature Request]: add to DeveloperGuide.md explaining thymeleaf and general steps on how to add new feature to stirling pdf and its API + UI

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
