### ISSUE TITLE
[Bug]:   Image to PDF - Image Rotation and EXIF

### ISSUE THREAD

**Issue by Noneangel** [Stirling-Tools/Stirling-PDF#2028]
### Installation Method

None

### The Problem

When converting an image to a PDF, Stirling-PDF discard the EXIF rotation attribute, so the resulting image in the PDF is not correctly rotated.

### Version of Stirling-PDF

0.29.0

### Page Where the Problem Occurred

https://stirlingpdf.io/img-to-pdf

### Additional Information

Steps to reproduce on Windows 11:
1. Open `my-picture.jpeg` using the default app [`Photos`](https://apps.microsoft.com/detail/9wzdncrfjbh4)
2. Rotate the image
<img src="https://github.com/user-attachments/assets/913c6024-ddcd-4a20-91fd-8c3146342eab" width="240" />

"[Cat](https://www.flickr.com/photos/23226676@N08/2243532184)" by [joshuascottphotos](https://www.flickr.com/photos/23226676@N08) is licensed under [CC BY 2.0](https://creativecommons.org/licenses/by/2.0/?ref=openverse).
3. Save the image as `my-picture-rotated.jpeg`
4. Convert `my-picture-rotated.jpeg` using https://stirlingpdf.io/img-to-pdf with default option.
5. The resulting PDF display the image without the rotation (i.e. image identical to  `my-picture.jpeg`)

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by sbplat** [comment]
ImageIO doesn't load the exif data so we need to read it ourselves.
