### ISSUE TITLE
[Bug]: Translated text not shown (German)

### ISSUE THREAD

**Issue by leonbrehme** [Stirling-Tools/Stirling-PDF#2039]
### Installation Method

Docker

### The Problem

The name for the link "Privacy Policy" ist not translated in the gui. The link does not show up as "Datenschutz" (as set in messages_de_DE.properties, line 83).

I get this:
![image](https://github.com/user-attachments/assets/d9f55062-71a9-471d-9b0a-a5788cb36805)

### Version of Stirling-PDF

0.29.0

### Page Where the Problem Occurred

/

### Browsers Affected

Chrome

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by Ludy87** [comment]
Hi @leonbrehme It has already been released in the main version and will be available in the next release.

**Comment by leonbrehme** [comment]
Nice! Thank you for the update :)
And sorry for the duplicate.
