### ISSUE TITLE
[Feature Request]: Increase watermark coverage to fill page

### ISSUE THREAD

**Issue by remygrandin** [Stirling-Tools/Stirling-PDF#2049]
### Feature Description

When using the watermark function as default (45° watermark) the lower rightcorner of the page is untouched by the watermark.

It would need some extra lines to be filled completely.

### Why is this feature valuable?

Watermark should be able to be on the full size of the page

### Suggested Implementation

option 1 : Compute the right amount of line, not based only on page height like now, but incorporating the angle. Probably nee a trigonometry calculation to compute the "extra height".
option 2 : Add an extra field to the existing watermark generator for line counts. When empty (default) use the existing computation, when filed, use the amount specified.

### Additional Information

Seem to happend only on long watermark string, when it don't have the oportunity to "repeat"

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by thisisrenan** [comment]
Hi, I can work on this.

**Comment by remygrandin** [comment]
Lovely, great work !
