### ISSUE TITLE
Question about Stirling PDF Pro/Enterprise Version

### ISSUE THREAD

**Issue by thiagoor-cpu** [Stirling-Tools/Stirling-PDF#2051]
Hello, I have configured a server with Stirling PDF using Docker version and later Source version, using Google SSO/OAuth of my organization and customized Favicons, now Im seeing new documentation appearing about Stirling PDF Pro and Enterprise, and according to this documentation this configuration Im using is PRO only.

Just to make sure I understand, the software have features available now that we can use, but after a while, this "advanced" features will be behind paywall? a more expensive paywall than Google Workspace Suite, at least in my country.

Im just asking because if thats the case no point in configuring a new deployment with features that will be removed..

**Comment by Frooodle** [comment]
In future we are actually considering the opposite and moving some paid features to free.

**Comment by Frooodle** [comment]
Makes sense, thanks for pointing this out, will try to improve wording to help explain this better

**Comment by thiagoor-cpu** [comment]
> Makes sense, thanks for pointing this out, will try to improve wording to help explain this better

No problem, Im not a native english speaker so I cant help much in the text, but maybe a comparative table with the differences between the versions is a good alternative.

Many thanks for the explanation and quick responses, good work!

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
