### ISSUE TITLE
[Bug]: Tools are not being moved to categories in Brave browser (even with shields off)

### ISSUE THREAD

**Issue by shmshd** [Stirling-Tools/Stirling-PDF#2078]
### Installation Method

Docker fat

### The Problem

Tools categorization introduced in 0.30 is not working on Brave browser with even shields turned off. Works well with other browsers. See below screenshot

![image](https://github.com/user-attachments/assets/ce25874f-5516-44de-bc8d-6ddec32c45d4)

### Version of Stirling-PDF

0.30.1

### Docker Configuration

```txt
name: stirling-pdf

services:
  stirling-pdf:
    container_name: spdf
    image: frooodle/s-pdf:0.30.1-fat
    ports:
      - "5002:8080"
    volumes:
      - ~/deployments/stirlingpdf/trainingData:/usr/share/tessdata
      - ~/deployments/stirlingpdf/extraConfigs:/configs
      - ~/deployments/stirlingpdf/customFiles:/customFiles/
      - ~/deployments/stirlingpdf/logs:/logs/
    environment:
      DOCKER_ENABLE_SECURITY: false
      INSTALL_BOOK_AND_ADVANCED_HTML_OPS: false
      LANGS: en-US
```

### Browsers Affected

Other

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by Frooodle** [comment]
Looks like a cache issue, works fine for me on brave, can you try doing a hard refresh?

**Comment by shmshd** [comment]
That's the only thing I left to try. Yes, it works fine after a hard refresh.
