### ISSUE TITLE
[Bug]: Bored waiting button doesnt remove itself after processing

### ISSUE THREAD

**Issue by Frooodle** [Stirling-Tools/Stirling-PDF#2079]
### Installation Method

None

### The Problem

Bored waiting button doesnt remove itself after processing

### Version of Stirling-PDF

all

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by v3nus-py** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by alonsofabila-dev** [comment]
hii, can i work on this issue?

**Comment by alonsofabila-dev** [comment]
can I get more information about the button referred to in the issue?

**Comment by Frooodle** [comment]
If you go to settings and select bored waiting 

And then run a process which takes more than x settings (try OCR on a large doc) a bored waiting button appears
This let's users play a game while they wait!

**Comment by alonsofabila-dev** [comment]
can i use AJAX?

**Comment by Frooodle** [comment]
Id rather not since its not used elsewhere in repo

**Comment by alonsofabila-dev** [comment]
I thought about using AJAX, since it will allow me to fix the bug without changing the codebase for the enpoints. I'll try finding another solution.
