### ISSUE TITLE
Stirling PDF 0.30.1: uncorrect visualization on firefox (latest version)

### ISSUE THREAD

**Issue by topoldo** [Stirling-Tools/Stirling-PDF#2087]
### Installation Method

Local Installation

### The Problem

I tried to launch Stirlin PDF 0.30.1on 3 different browser (all at their latest version) under Win 11 24H2 and the result is reported in the attached images.
As you can see: Google Chrome & MS Edge are OK, while an uncorrect visualizazion is present in Mozilla Firefox

**Google Chrome**

![chrome](https://github.com/user-attachments/assets/64b5fd67-4b3a-45cb-819e-18d17514cd3e)

**Mozilla Firefox**

![Firefox](https://github.com/user-attachments/assets/f2855aaa-96a5-443f-b983-a6fb2b9f3cdc)

**Microsoft Edge**

![MS Edge](https://github.com/user-attachments/assets/b25a6d7b-ffb1-46ff-863a-12c6e808586c)

Regards,
Leopoldo Saggin aka Topoldo

### Version of Stirling-PDF

0.30.1

### Last Working Version of Stirling-PDF

0.29.3

### Browsers Affected

Firefox

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by Frooodle** [comment]
Works fine for me, are you sure this is not a cache issue? can you do a hard reload?
