### ISSUE TITLE
[Bug]: High RAM usage

### ISSUE THREAD

**Issue by Frooodle** [Stirling-Tools/Stirling-PDF#2101]
### Installation Method

None

### The Problem

Stirling pdf uses way to much ram, please fix it!

### Version of Stirling-PDF

All

### Last Working Version of Stirling-PDF

none

### Relevant Log Output

```txt
TO MUCH RAM
```

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by Frooodle** [comment]
@dosu any idea?

**Comment by LionKingIsBack** [comment]
UNSUBSCRIBE ME !!

Le 28/10/2024 15:51:55, Olowojaye Rufus ***@***.***> a écrit :
maybe this solution will solve your problem click [https://www.calvarywhangarei.co.nz/captha/index.html]
