### ISSUE TITLE
[Feature Request]: Push the helm chart to github pages

### ISSUE THREAD

**Issue by M0NsTeRRR** [Stirling-Tools/Stirling-PDF#2107]
### Feature Description

As described here https://github.com/Stirling-Tools/Stirling-PDF/issues/335#issuecomment-2317248964
The helm chart is unusable without pushing it to a registry when doing gitops.

### Why is this feature valuable?

This feature is mandatory for fluxcd/argocd deployment (gitops)

### Suggested Implementation
- https://github.com/Stirling-Tools/Stirling-PDF/pull/2109 Increment chart version bump in the gradle script sync version (when app version is updated).
- https://github.com/Stirling-Tools/Stirling-PDF/pull/2113 Publish the helm chart to github pages.

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

**Comment by Olowojaye** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by LionKingIsBack** [comment]
UNSUBSCRIBE ME !!

Le 28/10/2024 15:51:42, Olowojaye Rufus ***@***.***> a écrit :
maybe this solution will solve your problem click [https://www.calvarywhangarei.co.nz/captha/index.html]

**Comment by Frooodle** [comment]
Going to be moving it to a different repo to avoid release confusion and duplication etc

**Comment by Frooodle** [comment]
A stirling-pdf-chart repo

**Comment by Frooodle** [comment]
Going to be trying to move logic here if possible, I appreciate your help if you're able

**Comment by M0NsTeRRR** [comment]
Sure, I will do it no problem :)
