### ISSUE TITLE
[Feature Request]: Document Options for Imprint & Privacy Policy in README

### ISSUE THREAD

**Issue by colfes** [Stirling-Tools/Stirling-PDF#2111]
### Feature Description

In the footer, there is currently no option to add a link to an Imprint / Privacy Policy. Having an imprint is mandatory in the EU (very little exceptions that noone understands, so best to just have it). It would be nice to have a configurable env variable with the URL to an imprint and a second URL to a privacy policy, so that one can configure the docker container with e.g. SYSTEM_IMPRINTURL set to example.org/imprint and the same for the privacy policy.

### Why is this feature valuable?

It's unclear whether its legal to host the software as-is in the EU. It would require "tricks" in the reverse proxy or similar, which would be nice to be able to avoid.

### Suggested Implementation

In the same area as the current Licenses and Survey buttons, add buttons for "Imprint" and "Privacy Policy" with user-configurable URLs they lead to.
If the environment variable has not been configured, do not display the button at all (only display if the user has wished to do so).

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

**Comment by colfes** [comment]
Hi Froodle, just read your reply in the discussion. Looks like this is already implemented. Then this issue likely just comes down to updating the current list of settings in the README.

**Comment by colfes** [comment]
Just verified it, imprint URL works in my Docker setup! :) Updated the issue name to reflect it's only a documentation issue.

**Comment by colfes** [comment]
Just another hint: The survey URL leads to "Survey not found" (using frooodle/s-pdf:latest)

**Comment by Frooodle** [comment]
Are you sure that's the latest version you're on? Survey was updated

**Comment by colfes** [comment]
No! Either old image or browser cache. Works now, sorry.
