### ISSUE TITLE
[Bug]: Terms and conditions URL hard-coded in settings.yml

### ISSUE THREAD

**Issue by colfes** [Stirling-Tools/Stirling-PDF#2112]
### Installation Method

None

### The Problem

The settings.yml contains this line:

legal:
  Automatically Generated Settings (Do Not Edit Directly)
  termsAndConditions: https://www.stirlingpdf.com/terms-and-conditions # URL to the terms and conditions of your application (e.g. https://example.com/terms) Empty string to disable or filename to load from local file in static folder

When using through docker, this leads to the Terms and Conditions button being shown (and linking to stirlingpdfs' T&C), even though this should not be the case.

Even when setting LEGAL_TERMSANDCONDITONS: "" in the compose file, the link will not disappear.

Behaviour should be similar to privacyPolicy / Impressum etc, where there is '' in the settings.yml

### Version of Stirling-PDF

latest

### Page Where the Problem Occurred

Start page

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by ilacftemp** [comment]
Hey, can I work on this issue?

**Comment by ilacftemp** [comment]
Sorry, I accidentally created a PR for this issue ahead of time 😅 but I already closed it and plan on waiting for this issue to be assigned to me before reopening it.

**Comment by omar-ahmed42** [comment]
If no one is working on this issue, can I pick it up?

**Comment by Frooodle** [comment]
Thinking about this more...

I actually want to always have terms and conditions for legal reasons
You can replace with your own if required but by default showing Stirling pdf seems like good functionality
