### ISSUE TITLE
[Bug]: Auto language detection doesnt seem to work? Language doesnt show as selected in navbar either

### ISSUE THREAD

**Issue by Frooodle** [Stirling-Tools/Stirling-PDF#2122]
### Installation Method

None

### The Problem

[Bug]: Auto language detection doesnt seem to work? Language doesnt show as selected in navbar either

### Version of Stirling-PDF

All

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by Ludy87** [comment]
Yes there is a misnomer in Javascript.

Even after the fix, there is still another problem affecting Firefox regarding this bug.
