### ISSUE TITLE
[Bug]: Drag drop files on Sign has weird results

### ISSUE THREAD

**Issue by Frooodle** [Stirling-Tools/Stirling-PDF#2131]
### Installation Method

None

### The Problem

Drag drop files on Sign has weird results producing multiple images

### Version of Stirling-PDF

all

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by TomLincoln066** [comment]
I'd love to help but
is there more background context about this bug?

**Comment by Frooodle** [comment]
When on sign pdf 
Upload pdf normally 
Go to sign with image

Drag drop a image, produces multiple images on page

**Comment by TomLincoln066** [comment]
Got it.
I'd like to work on this 
could you assign me?
Thanks

**Comment by omar-ahmed42** [comment]
Hello, are you still working on this issue? If not, can I have it assigned to me?

**Comment by Frooodle** [comment]
Been stale for quite a while probably good to pick up

**Comment by omar-ahmed42** [comment]
Well, I can start working on it
