### ISSUE TITLE
[Feature Request]: customizing HTML files 

### ISSUE THREAD

**Issue by lyknny** [Stirling-Tools/Stirling-PDF#2150]
### Feature Description

Hello,

I set the customHTMLFiles to true in settings.yml and placed files including common.html and footer.html in the /customFiles/templates but the page doesn't change.

 Can anyone guide me in this step? 

Thanks.

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

**Comment by lyknny** [comment]
I did several times. And I don't get any errors.

**Comment by Frooodle** [comment]
Can you provide screenshots of your directory mapping along with your docker config?

**Comment by lyknny** [comment]
Sure,
![Screenshot 2024-11-01 231957](https://github.com/user-attachments/assets/3b1cbd67-261d-4451-9a40-6c685b7d4ce3)
![Screenshot 2024-11-01 232036](https://github.com/user-attachments/assets/1dda0743-ee5f-4333-a6ea-bb8851beb379)
![Screenshot 2024-11-01 232100](https://github.com/user-attachments/assets/a3db1e34-fce0-4bbf-8a0b-5cd31f8f9e28)

**Comment by Frooodle** [comment]
the path should be ``./customFiles/templates/fragments`` where the files are located

**Comment by lyknny** [comment]
Unfortunately, It also doesn't work.
![Screenshot 2024-11-01 233523](https://github.com/user-attachments/assets/c7024790-3dfa-48f6-bcd0-e887ba01ab13)

**Comment by Frooodle** [comment]
Is that after a restart?

**Comment by lyknny** [comment]
I checked the chrome inspect. It didn't override the file and still.

**Comment by MaratheHarshad** [comment]
Hey @lyknny,
I recommend ensuring you're running the correct .jar file located at:

./build/libs/Stirling-PDF-0.*.jar

Customizing HTML files appears to be working fine for me.

Please find the screenshots attached:

![image](https://github.com/user-attachments/assets/4d420850-5335-4174-b902-1b6ee006bd96)
![image](https://github.com/user-attachments/assets/ea33cbc1-9b8d-4b23-aa7f-14bd717e09d1)

**Comment by Frooodle** [comment]
what was the exact fix for you in end?

**Comment by lyknny** [comment]
I overrode all HTML files in the fragments folders.
