### ISSUE TITLE
[Feature Request]: Remove files from file input after sucessful operation to allow continuous usage 

### ISSUE THREAD

**Issue by Frooodle** [Stirling-Tools/Stirling-PDF#2172]
### Feature Description

Remove files from file input after sucessful operation to allow continuous usage 

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

**Comment by thisisrenan** [comment]
Hi @Frooodle, Can I work on this? And would it be possible to describe the feature idea in more detail? I didn't quite understand it.

**Comment by rafael-encinas** [comment]
I can work on this!

**Comment by thisisrenan** [comment]
@Frooodle I saw that lol, You can assign this to @rafael-encina; I'll take the next one.

**Comment by rafael-encinas** [comment]
Thank you @thisisrenan !

**Comment by rafael-encinas** [comment]
> If you input a file into split pdf for example and hit process
> 
> The files remain in the input box
> 
> When you try add new files it instead appends them ontop Meaning for multiple operations you need to refresh
> 
> Appending is a feature users want so best solution is to wipe the input box after process complete
> 
> I see 2 people commented at same time... Not sure who to assign 😂

@Frooodle, I'm trying to find where the change needs to be located.

Is the "allFiles" array on line 10  from the [fileInput.js](https://github.com/Stirling-Tools/Stirling-PDF/blob/main/src/main/resources/static/js/fileInput.js) file where the files are being stored temporarily? Is this array the one that needs to be wiped after a successful job?

Thank you in advance!

**Comment by Frooodle** [comment]
I believe allFiles along with e.target.files but its been a while :')
