### ISSUE TITLE
[Feature Request]: Separate repos for docker and helm chart

### ISSUE THREAD

**Issue by sharifm-informatica** [Stirling-Tools/Stirling-PDF#2175]
### Feature Description

It makes it much easier to fork, track, modify and contribute to the docker/compose and to the helm chart. Many projects have separate repos for the helm chart and for the docker/compose. So to clarify 2 new repos:
1- Sterling-PDF docker
2- Sterling-PDF Helm chart

### Why is this feature valuable?

This also has the advantage of independent workflows, releases, testing, and prerelease cycles.

### Suggested Implementation

Move the relevant files and folders to new repo. Amend documentation to reference the new repo. Publish to container registries from the new repos. 

### Additional Information

I can help with this, if the idea is acceptable.

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

**Comment by Frooodle** [comment]
Agreed I am going to be doing this
For releases and such it makes most sense

**Comment by sharifm-informatica** [comment]
Need any help?

**Comment by Frooodle** [comment]
https://github.com/stirling-tools/Stirling-PDF-chart
