### ISSUE TITLE
[Bug]: PDF to XML = Error 504

### ISSUE THREAD

**Issue by IJH91IJH91** [Stirling-Tools/Stirling-PDF#2182]
### Installation Method

None

### The Problem

From your website, I tested various PDFs to XML and all returned ERROR 504.
And it didn't provide extra details.

### Version of Stirling-PDF

current version on the WebSite

### Relevant Log Output

```txt
Error 504
```

### Additional Information

Error 504

### Browsers Affected

Chrome

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by Frooodle** [comment]
https://github.com/Stirling-Tools/Stirling-PDF/issues/2183#issuecomment-2457191863
