### ISSUE TITLE
[Bug]: PDF to DOCX= Error 504

### ISSUE THREAD

**Issue by showbas91** [Stirling-Tools/Stirling-PDF#2183]
### Installation Method

Docker

### The Problem

From your website, and from local docker I tested various PDFs to DOCX and all returned ERROR 504.
And it didn't provide extra details.

### Version of Stirling-PDF

0.31.1

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by Frooodle** [comment]
504 is a timeout issue caused by nginx settings or similar proxies/server timeouts 

The website is intended as demo and as such is not set up for long processes 

For local there may be some configs you need to setup
