### ISSUE TITLE
[Feature Request]: Manual Redact

### ISSUE THREAD

**Issue by louispires** [Stirling-Tools/Stirling-PDF#2186]
### Feature Description

It would be beneficial to have a Manual Redact where one can draw boxes to be redacted.

There was mentioned that a Manual Redact would come at a later stage: https://github.com/Stirling-Tools/Stirling-PDF/issues/122

### Why is this feature valuable?

While Auto Redact works good in a structured environment, a Manual Redact feature would be helpful when attempting redact specific information or very large chunks at a time.

### Suggested Implementation

1. Simple black boxes to be drawn over the area to be redacted.
2. When highlighting words/text manually, only that word/text gets redacted  

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

**Comment by louispires** [comment]
#465 Is very similar to my request, however the name was not the same and I believe the additional feature of 2. Highlighting words and smartly redacting them is an addition to that Feature Request

**Comment by Frooodle** [comment]
I would prefer this ticket be closed and #2 be a additional request under that same feature
