### ISSUE TITLE
[Feature Request]: Multi-tool add blank page between pages as a option

### ISSUE THREAD

**Issue by Frooodle** [Stirling-Tools/Stirling-PDF#2194]
### Feature Description

: Multi-tool add blank page between pages as a option

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

**Comment by thisisrenan** [comment]
Hi @Frooodle, can I work on this?

**Comment by Frooodle** [comment]
Sure!

**Comment by linhexu** [comment]
I want to try this

**Comment by Frooodle** [comment]
> I want to try this 

Please stop spamming across all tickets especially ones you see PRs already open for or People working on
