### ISSUE TITLE
[Feature Request]: thumbnails for the split tool

### ISSUE THREAD

**Issue by EPN61400** [Stirling-Tools/Stirling-PDF#2196]
### Feature Description

Get thumbnails, like multi tool does, could help to choose number for split on.

### Why is this feature valuable?

It would be easier to find page number to split on.

### Suggested Implementation

Maybe, it should be possible to get the code from thumbnails multi tool…

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

**Comment by Frooodle** [comment]
Multi tool already supports splitting PDFs 
I would say If your goal is to view the pdf pages multi-tool should serve that purpose

**Comment by EPN61400** [comment]
I never thought about multi tool for splitting…
It works, but for a document with a lot of pages, we must click on all separations. We can't write range like split tool.

**Comment by Frooodle** [comment]
How would you implement it on split tool side for large page docs if you want a view etc?

**Comment by linhexu** [comment]
give me this task

**Comment by thisisrenan** [comment]
Hi @Frooodle, The idea of having a range for using cutting tools on the multi-tool is a good one. Is there already an issue requesting this feature?

**Comment by Frooodle** [comment]
There isn't but I am also not sure about this feature...
How would you expect it to be implemented?

**Comment by thisisrenan** [comment]
The idea is to allow the user to define ranges for using cutting tools, similar to how chapters in a book are organized by page ranges. For example, the user could set the cutting range from "1 to 10" for the first part and from "11 to 30" for the second, allowing the process to be segmented into specific steps. Kind of like this, I'm not sure if I explained it in the best way possible.

**Comment by Frooodle** [comment]
I think the multi-tool is getting to complex with feature at moment 

Might be best to add the UI element to split instead of multi tool... Unless you can think of a way of adding it neatly to multi tool

**Comment by EPN61400** [comment]
I've simply thought of little overviews with numbers. This would make it easier to identify the page numbers.

It doesn't need special action on it, just previews.

**Comment by EPN61400** [comment]
Thanks for the multi-tool improvements.
