### ISSUE TITLE
[Bug]: canvas has broken out of the layout.

### ISSUE THREAD

**Issue by Ludy87** [Stirling-Tools/Stirling-PDF#2209]
### Installation Method

None

### The Problem

![image](https://github.com/user-attachments/assets/d3f78ce1-128f-45ab-b349-f49f27a5678e)

Unfortunately my CSS knowledge fails here and must be fixed by someone else. 😄 

### Version of Stirling-PDF

0.32.x

### Browsers Affected

Firefox, Chrome

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by DimK10** [comment]
I'll check it.

**Comment by Ludy87** [comment]
@DimK10 it also affects `pdf-to-csv`

**Comment by DimK10** [comment]
I don't have the ability to check right now, do you mean the relevant page? If so, I'll make the necessary fixes
