### ISSUE TITLE
[Bug]: Seeing remoteCall not defined when using merge feature

### ISSUE THREAD

**Issue by vedhavyas** [Stirling-Tools/Stirling-PDF#2217]
### Installation Method

Docker

### The Problem

Tried to use merge feature today and started seeing `remoteCall not defined`

<img width="1839" alt="Screenshot 2024-11-12 at 6 07 49 PM" src="https://github.com/user-attachments/assets/cd9fb289-ba6e-4cfa-acce-f55116afcb8d">

### Version of Stirling-PDF

0.32.0

### Page Where the Problem Occurred

/merge-pdfs

### Docker Configuration

```txt
pdf:
    image: frooodle/s-pdf:latest
    container_name: sterling_pdf
    hostname: sterling_pdf
    restart: unless-stopped
    volumes:
      - /appdata/sterling-pdf/training_data:/usr/share/tessdata
      - /sterling-pdf/configs:/configs
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=true
      - LANGS=en_US
```

### Relevant Log Output

```txt
Nothing on the logs

This is what I found on the browser console

downloader.js:71 ReferenceError: remoteCall is not defined
    at HTMLFormElement.<anonymous> (downloader.js:40:7)
    at HTMLFormElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
(anonymous)	@	downloader.js:71
```
```


### Additional Information

_No response_

### Browsers Affected

_No response_

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by Frooodle** [comment]
Can you check if there is a cache issue I cant reproduce this with
https://stirlingpdf.io/merge-pdfs
Can you do f12 then right click refresh button in top left, and select hard refresh with cache clear?

**Comment by vedhavyas** [comment]
Looks like it. Still see the same after hard refresh but cannot reproduce this in incognito.

So must be cache issue.
Thanks!
