### ISSUE TITLE
[Feature Request] Split PDF custom file name

### ISSUE THREAD

**Issue by SBCV-apegram** [Stirling-Tools/Stirling-PDF#223]
Add a box to the Split PDF tool to allow for custom naming of the created files.

**Comment by Frooodle** [comment]
Can you go into more detail about what is intended from this?
Do you mean per split file or changing the general name of ALL files?

**Comment by SBCV-apegram** [comment]
I guess it could be both. Basically, I'd like the ability to set the base name of the child PDFs. But it could be cool to have it extract a line from the document to use as the differentiator.

Example: a massive mail-merge document. The pages follow a pattern, so a regex could be specified to match a line of text near the top of the page.

**Comment by Frooodle** [comment]
Auto rename feature is for this instead of built with split for now
