### ISSUE TITLE
[Feature Request] PDF Multitool - Extract pages

### ISSUE THREAD

**Issue by SBCV-apegram** [Stirling-Tools/Stirling-PDF#225]
Enable page extraction on the multitool.

**Comment by Frooodle** [comment]
Can you explain what you want this to do exactly?

**Comment by iampegram** [comment]
The ability to select multiple pages (holding Shift or Ctrl), then click a button to download those extracted pages.

**Comment by SBCV-apegram** [comment]
The ability to select multiple pages (holding Shift or Ctrl), then click a button to download those extracted pages.

**Comment by graphixillusion** [comment]
Yep this would be a great feature to have. I was thinking about it today and i came here to make a feature request until i found this one. Any progress on this?
