### ISSUE TITLE
[Bug]: pdf-to-csv

### ISSUE THREAD

**Issue by cajamag** [Stirling-Tools/Stirling-PDF#2255]
### Installation Method

None

### The Problem

"PDF-to-CSV is not working. After detecting the table, it exports a blank page."

### Version of Stirling-PDF

latest

### Last Working Version of Stirling-PDF

latest

### Page Where the Problem Occurred

https://stirlingpdf.io/pdf-to-csv

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by Frooodle** [comment]
Any docker logs?

**Comment by cajamag** [comment]
I do not have logs, it only uploads a PDF file that contains a csv or xlsx table and when it is converted it only downloads the file with row number 1

**Comment by admwallw** [comment]
We are facing same issue when converting from PDF to CSV. Only first row is extracted to CSV. Where can I find logs?

**Comment by omar-ahmed42** [comment]
I have actually noticed this bug as well but I also noticed that the behavior on the remote (https://stirlingpdf.io/pdf-to-csv) isn't the same as the behavior when run locally, I will explain it as follows provided 2 files, 1 exported from LibreCalc and another exported from Excel:

### On the website (remote):
- File `"tableFromLibreCalc.pdf"` (Exported as PDF from LibreCalc)
= Results in the entire data being printed in one line (column by column).

- File `"tableFromExcel.pdf"` (Exported as PDF from Excel)
= Results in the data being printed in the same line **BUT** only the first 4 values of the first column [1 header + 3 values].

### Locally:
- File `"tableFromLibreCalc.pdf"` (Exported as PDF from LibreCalc)
= Runs perfectly and extracts the table in the CSV file as expected.

- File `"tableFromExcel.pdf"` (Exported as PDF from Excel)
= Results in printing the first 4 values (1 header + 3 values) in the same line [The values are from the same column].

Note: I couldn't find any logged exceptions when run locally, so I believe the problem might have something to do with identifying the rows/columns in some cases.

Afterwards, I attempted to use Tabula-Java as mentioned in #1614 in the project on the same files and it surprisingly ran smoothly on both files.

### Test Files:
- PDF Exported from LibreCalc: [tableFromLibreCalc.pdf](https://github.com/user-attachments/files/17879669/tableFromLibreCalc.pdf)

- PDF Exported from Excel: [tableFromExcel.pdf](https://github.com/user-attachments/files/17879670/tableFromExcel.pdf)
