### ISSUE TITLE
[Bug]: Collapsible menus on reload (with state closed saved) don't re-expand correctly

### ISSUE THREAD

**Issue by Frooodle** [Stirling-Tools/Stirling-PDF#2265]
### Installation Method

Docker

### The Problem

Collapsible menus on reload (with state closed saved) don't re-expand correctly
![Animation2](https://github.com/user-attachments/assets/7bbdb72e-e5d7-4ffc-ab1a-9cfcf40945ae)

### Version of Stirling-PDF

0.33.1

### Browsers Affected

Chrome

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by MaratheHarshad** [comment]
I've reviewed this issue and observed the behavior on the live site as described. I've started working on resolving it and will share updates or a pull request soon.
