### ISSUE TITLE
[Bug]: merge-pdfs error with different folder source

### ISSUE THREAD

**Issue by cajamag** [Stirling-Tools/Stirling-PDF#2285]
### Installation Method

Local Installation

### The Problem

When you upload a PDF document from a folder, example downloads, and then add another document from a different folder, example documents, the system replaces the file and only leaves the last one that was uploaded.

### Version of Stirling-PDF

latest

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by omar-ahmed42** [comment]
Can I work on this issue?

**Comment by Frooodle** [comment]
Yes!
