### ISSUE TITLE
[Bug]: if SYSTEM_ROOTURIPATH is configured pdfWorker.js return 404

### ISSUE THREAD

**Issue by udelbo** [Stirling-Tools/Stirling-PDF#2353]
### Installation Method

Docker fat

### The Problem

if SYSTEM_ROOTURIPATH is configured pdfWorker.js return 404, this is not the only one probably.

### Version of Stirling-PDF

0.34.0

### Page Where the Problem Occurred

http://localhost:8080/StirlingPDF/compare

### Docker Configuration

```txt
services:
  stirling-pdf:
    image: frooodle/s-pdf:latest-fat
    ports:
      - '8080:8080'
    volumes:
      - ./StirlingPDF/trainingData:/usr/share/tessdata # Required for extra OCR languages
      - ./StirlingPDF/extraConfigs:/configs
      - ./StirlingPDF/customFiles:/customFiles/
      - ./StirlingPDF/logs:/logs/
      - ./StirlingPDF/pipeline:/pipeline/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=es_AR
      - UI_APP_NAME=Stirling PDF
      - UI_HOME_DESCRIPTION=Herramientas para trabajar con archivos PDF
      - UI_APP_NAVBAR_NAME=Stirling PDF
      - ALLOW_GOOGLE_VISIBILITY=false
      - SYSTEM_ROOTURIPATH=/StirlingPDF
```

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by udelbo** [comment]
if SYSTEM_ROOTURIPATH is configured same happens in this line on main page <link rel="preload" href="[/fonts/google-symbol.woff2](https://miserver.com/fonts/google-symbol.woff2)" as="font" type="font/woff2" crossorigin="anonymous">

**Comment by Frooodle** [comment]
Fixed both on my branch, will merge today or tomorrow for next release
