### ISSUE TITLE
[Bug]: Compress level

### ISSUE THREAD

**Issue by Zalk0** [Stirling-Tools/Stirling-PDF#2366]
### Installation Method

None

### The Problem

The compress level selection goes from 1 to 9 instead of 1 to 4 previously and the pdf doesn't seem to change size whatever the compress level I select.
![image](https://github.com/user-attachments/assets/783b4602-0278-40da-9125-57ac1973bb12)

### Version of Stirling-PDF

0.35.0

### Last Working Version of Stirling-PDF

0.33.1

### Page Where the Problem Occurred

https://stirlingpdf.io/compress-pdf

### Additional Information

I have only tested on the demo stirlingpdf.io and I'm pretty sure it was working correctly in 0.33.1 but now in 0.35.0 it's broken.
Also when dragging a file over the tab the page stays dark with the text "Drop files anywhere to upload" instead of correctly adding the file (I can still interact with the buttons however). I can open another issue for this if needed.

### Browsers Affected

Firefox, Chrome

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by Frooodle** [comment]
Drag and drop will be patched today already have a fix for that 
No need to make new issue

**Comment by Frooodle** [comment]
Can you send the docker logs of what it's doing for the compression? Will help figure out cause

**Comment by Frooodle** [comment]
Sorry just read you only tested on demo and hence can't grab logs

**Comment by Zalk0** [comment]
Sorry not at home at the moment but what I wanted to show is that when you choose the optimization level it should be from 1 to 4 as was previously and it's what written on the page. However now the dropdown menu shows from 1 to 9 and there isn't the text on the option 4 which was terrible for text images or something.
![image](https://github.com/user-attachments/assets/94335dbb-0cad-4238-b13a-69498d52fdd2)

**Comment by Frooodle** [comment]
Yes correct the 1-4 needs changing to say 1-9 now, the backend compression logic has changed

**Comment by Frooodle** [comment]
For it not working, i believe it should work but it might be your PDF cant be compressed due to its structure, would love to see docker logs to investigate that side

**Comment by Zalk0** [comment]
I'll try again later when I can, thanks for your work 👍
I liked the indication of the compression level being too much to be able to read text images. So if it's still relevant it would be cool to have it back.

**Comment by Zalk0** [comment]
I tested again with another pdf and the compression worked, I was probably confused by the change of scale and used it on a pdf that was already compressed to some degree.
