### ISSUE TITLE
[Feature Request]: Pdf to xlsx 

### ISSUE THREAD

**Issue by killmasta93** [Stirling-Tools/Stirling-PDF#2371]
### Feature Description

Hi Currently was wondering if in the future to convert pdf to xlsx?

### Why is this feature valuable?

Currently were using the ilovepdf to convert but with data very important

### Additional Information

i see that there are few features https://github.com/Stirling-Tools/Stirling-PDF/issues/902
https://github.com/Stirling-Tools/Stirling-PDF/issues/505
hopefully one day

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

**Comment by Frooodle** [comment]
We have pdf to CSV 
Should be a pretty good midway to use instead

**Comment by killmasta93** [comment]
Thanks for the reply, yeah i tried that option but was not reading the PDF files

**Comment by Frooodle** [comment]
Was that 0.34.0 / later
It got improved recently about a week ago

**Comment by killmasta93** [comment]
yeah i recently downloaded the new container :0 but same issue, as im currently download a PDF from the movements in my bank statement and try to convert to excel of the csv

**Comment by Frooodle** [comment]
Duplicate as you pointed out, closing for now
