### ISSUE TITLE
[Feature Request]: Get Info on PDF to show permissions

### ISSUE THREAD

**Issue by Frooodle** [Stirling-Tools/Stirling-PDF#2387]
### Feature Description

Get Info on PDF to show permissions such as editable etc

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

**Comment by omar-ahmed42** [comment]
I believe Get Info on PDF already shows permissions but only when the PDF is encrypted (as a sub-tab or sub-menu) as in:

![image](https://github.com/user-attachments/assets/3d39a086-c54d-4ba4-be87-a1ce1e606b0c)

Should it display PDF files' permissions unconditionally and separately from Encryption menu? or you meant to simply print the permissions as follows, canPrint -> Printing, Can Modify -> Modifiable or Editable, false -> Not Allowed, true -> Allowed, etc?

**Comment by Frooodle** [comment]
I think moving permissions outside of encryption would be best for what users expect and have it displayed as all allowed when encryption is false is probably better for users
