### ISSUE TITLE
[Bug]: auto-redact PDF Input field missing?

### ISSUE THREAD

**Issue by thiagoor-cpu** [Stirling-Tools/Stirling-PDF#2403]
### Installation Method

Docker

### The Problem

Hello, I noticed that the input field for the PDF is missing in auto-redact page, my installation and also the oficial page, Im wrong or is it really missing? https://stirlingpdf.io/auto-redact

### Version of Stirling-PDF

0.35.1

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by thiagoor-cpu** [comment]
Oh, looks like its already fixed in next version, sorry for the duplicated post, you can close it, thanks.

**Comment by Frooodle** [comment]
released now too!
