### ISSUE TITLE
[Feature Request]: How to Uninstall

### ISSUE THREAD

**Issue by TheSimArchitect** [Stirling-Tools/Stirling-PDF#2422]
### Feature Description

Hi! I would like to uninstall it but I can't find how.

### Why is this feature valuable?

We should be able to remove it from our computer as easily as we can install it.

### Suggested Implementation

An uninstaller or simple instructions on how to uninstall it would be desirable.

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

**Comment by Frooodle** [comment]
How have you currently installed Stirling pdf?

**Comment by TheSimArchitect** [comment]
Hi! Thanks for quickly replying!

I am sorry but I don't have enough technical knowledge. I just ran your exe, which runs a script and installs your web application as the destination for my localhost at port 8080. I want to undo it but I can't find how.

**Comment by TheSimArchitect** [comment]
I opened https://github.com/Stirling-Tools/Stirling-PDF/releases/tag/v0.36.0 and I downloaded "Stirling-PDF.exe". Ran it, opened the application via chrome after your script installed it as the main page for my local host. I'd not like that behavior. I thought it was just a regular application, not that it would take over my localhost.

**Comment by Frooodle** [comment]
Stirling pdf is a portable .exe which is a single file 
There is no installation or placement in program files etc 

As for taking over local host, yes Stirling pdf runs as a local server 
I wouldn't label this as taking over the main page (we don't change any settings or anything)
But it's true that it's only accessable via a browser

To uninstall just delete the .exe ! 
It also generate configs folder and things which you can also delete

**Comment by Frooodle** [comment]
It's the file you downloaded so most likely your download folder
