### ISSUE TITLE
[Feature request] default pdf metadata for generated pdfs

### ISSUE THREAD

**Issue by jufy111** [Stirling-Tools/Stirling-PDF#243]
Would it be possible to add a new settings (or environmental variable) to set the pdf metadata for all pdfs generated by S-pdf (i.e Author, Subject, Title Etc.). 

You could also set S-pdf as the default Creator/Producer.

**Comment by Frooodle** [comment]
Good ideas I was going to make change to correctly maintain metadata for the files edited

Adding custom metadata values for all jobs is a bit awkward api wise I'll have to think about it best way to do it

Also this kind of stuff would get annoying if the localstorage expires 
Might have to be part of the userID/accounts update I will be doing

Alternatively this could also be a config file setting

**Comment by jufy111** [comment]
I like the Idea of a config file, but docker environmental variables could also work. I'll leave it with you.
