### ISSUE TITLE
[Feature Request]: sign tool to support undo

### ISSUE THREAD

**Issue by Frooodle** [Stirling-Tools/Stirling-PDF#2448]
### Feature Description

sign tool to support undo 
Both for signature drawing
and for placements

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

**Comment by MaratheHarshad** [comment]
Hi @Frooodle ,

This is a great feature idea! To make it easier for contributors to tackle these tasks, would it be okay to create two separate issues for:

1. Undo functionality for signature drawing.
2. Undo functionality for signature placements.

This way, individual contributors can focus on one task at a time. Let me know if that works for you—I'd be happy to help with creating the issues if needed!

Also, I’ve started analyzing the requirements and plan to raise a PR for one of these soon. Let me know your thoughts—I'm happy to proceed accordingly!

**Comment by Frooodle** [comment]
Sounds good 
I am away from pc ATM please feel free to create the features yourself and I'll close this one

**Comment by MaratheHarshad** [comment]
Hi @Frooodle,

I’ve created two separate issues based on your feature request. Please take a moment to verify that the issues raised correctly reflect the intended functionality.

Let me know if there’s anything you’d like to adjust or if everything looks good to proceed.
