### ISSUE TITLE
[Bug]: cannot upload nor drag&drop files in any menu tools (except multi tool)

### ISSUE THREAD

**Issue by kriss6557** [Stirling-Tools/Stirling-PDF#2452]
### Installation Method

Docker

### The Problem

Hello,
Since  0.36.X and latest I cannot upload or drap&drop any file in any menu tools (ie tools/crop). I can only upload files in the multitool menu.
Thanks

### Version of Stirling-PDF

0.36.X, latest

### Docker Configuration

```txt
Same as provided on your site
```

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by Frooodle** [comment]
This might be a cache issue i cannot reproduce it on my side

**Comment by kriss6557** [comment]
Yes correct, it worked in a private window.
Sorry, I close it.
