### ISSUE TITLE
[Feature Request]: Before Extract PDF auto remove password

### ISSUE THREAD

**Issue by kerry0088** [Stirling-Tools/Stirling-PDF#2460]
### Feature Description

I want these two functions(remove password, extract pages) to be combined.
Here’s the situation:
When I have a protected PDF (not the password to open the file) and I want to extract a few pages,
![Q](https://github.com/user-attachments/assets/92f41aeb-6728-4ddf-b10f-eaebbfe7f643)
I currently need to first remove the password using "Remove Password" and then extract the pages using "Extract Pages."

### Why is this feature valuable?

This can let this PDF webpage more connivence.

### No Duplicate of the Feature

- [X] I have verified that there are no existing features requests similar to my request.

**Comment by Frooodle** [comment]
This was added in 0.36.2!
It's already live

**Comment by kerry0088** [comment]
> This was added in 0.36.2! It's already live

But I'm already 0.36.2, and error occur when I extract pdf.
![version](https://github.com/user-attachments/assets/72a045c4-bd9e-40cf-bdc3-a0b29e30e454)
![ermsg](https://github.com/user-attachments/assets/1cac8a80-f92d-46a9-bb33-0d04fbc60f40)

**Comment by Frooodle** [comment]
Can you try test it out in a new browser or something
See if it's a cache issue

**Comment by kerry0088** [comment]
> Can you try test it out in a new browser or something See if it's a cache issue

Sorry for replying so late. 
It still doesn't work in 'extract-page,'(in Private mode, in another PC, browser, Wi-Fi) but **I can use this function normally in _'multi-tool._'**
I'm happy that I can use it in 'Stirling PDF.' 
Thanks for your reply.
