### ISSUE TITLE
[Bug]: env TESSERACT_LANGS overrides env LANGS

### ISSUE THREAD

**Issue by janguenther-conventus** [Stirling-Tools/Stirling-PDF#2464]
### Installation Method

Docker fat

### The Problem

During the processing of the environment variable “TESSERACT_LANGS” in “/scripts/init.sh”, the variable “LANGS” is overwritten. The environment variable “LANGS” is also used to install fonts in “/scripts/installFonts.sh”. It is not possible to install a font using the environment variable “LANGS” while the environment variable “TESSERACT_LANGS” is set.

### Version of Stirling-PDF

0.36.2

### Docker Configuration

```txt
services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:0.36.2-fat
    environment:
      TESSERACT_LANGS: eng,deu
      LANGS: "GENERAL,en_EN,de_DE"
```

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by Frooodle** [comment]
You are welcome to raise a PR for this if you have the fix in mind!
