### ISSUE TITLE
[Bug]: 0.36.4 Image to pdf bug when Multiple pdf option selected

### ISSUE THREAD

**Issue by Richard38907** [Stirling-Tools/Stirling-PDF#2488]
### Installation Method

None

### The Problem

Error message when converting images to separated pdfs
![image](https://github.com/user-attachments/assets/c9b4562a-83c5-4cbd-ab81-1ff2b934b9df)

### Version of Stirling-PDF

0.36.4

### Last Working Version of Stirling-PDF

Tested working on 0.31

### No Duplicate of the Issue

- [X] I have verified that there are no existing issues raised related to my problem.

**Comment by Ludy87** [comment]
Hi @Richard38907 could you provide the file name?

**Comment by Richard38907** [comment]
It's not about filename, that message shows only for more than 5 files.
![Screenshot_20241219-081639_Cromite.png](https://github.com/user-attachments/assets/f20ce378-edb3-4dc9-a422-974c81b160ee)




I encounter another error for 4 files or less

![Screenshot_20241219-081545_Cromite.png](https://github.com/user-attachments/assets/1f3ed3d7-a9a4-4450-924e-d27c74b47ea1)

**Comment by Ludy87** [comment]
Thanks, the last bug was fixed yesterday and should be gone in the next release.

**Comment by reecebrowne** [comment]
Closed by https://github.com/Stirling-Tools/Stirling-PDF/pull/2493

**Comment by Richard38907** [comment]
Updated to 0.36.5 but the bug seems to be present. It doesn't create the PDFs after the conversion. It asks me to save the files but nothing happens after🫤.

**Comment by Richard38907** [comment]
I didn't find the portable version. So I installed the Stirling windows installer.exe for that version. It's not a cache issue I think.

**Comment by Richard38907** [comment]
Oops, I forget to remove the old one, sorry. IT'S WORKING!

You can close this now.
