### ISSUE TITLE
[Feature Request]: Type into Fillable PDF

### ISSUE THREAD

**Issue by damomato** [Stirling-Tools/Stirling-PDF#265]
Great work on this. Would it be possible to implement a way to type into the fillable text boxes and select check boxes? I occasionally need to fill out PDFs so I use Acrobat for this. I know that you can use the Sign functionality to add text, but it would be much faster and cleaner to just select the text box and type it in. I do like the way Acrobat has Fill & Sign together so you can type in the text boxes and then add signatures etc.

Also, being able to save a draft which can be later resumed would be amazing.

**Comment by thor9898** [comment]
Great project, but this is a big miss.
Looking forward to this feature.

**Comment by Frooodle** [comment]
I seen a few people request this, I believe the "view-pdf" should have this functionality already, could you check?

**Comment by xavier-GitHub76** [comment]
I confirm (how can I miss it). Thanks for work done 👍

**Comment by damomato** [comment]
Just tried it too, I didn't realise those tools were there thanks for that!

Would it be possible to make some additions such as a date picker, symbols such as tick, cross, circles, lines, etc. And maybe even a way to add a signature, similar to how you can do it in Adobe.

Or would that be better as a different feature request?

**Comment by Frooodle** [comment]
Certainly a different feature request 
And also I believe someone has already raised this somewhere :)
