### ISSUE TITLE
BUG: PDF to HTML function doesn't work

### ISSUE THREAD

**Issue by arladmin** [Stirling-Tools/Stirling-PDF#284]
In the app UI, whenever i click on "Convert > PDF to HTML", i land on the page for "HTML to PDF".

**Comment by Frooodle** [comment]
Will resolve later tonight! Thanks for raising

**Comment by Frooodle** [comment]
Can you try pull latest version and see if that fixed it

**Comment by arladmin** [comment]
> Can you try pull latest version and see if that fixed it

Thanks! It's working correctly now.
