### ISSUE TITLE
The preview of the PDF converted from Excel is strange

### ISSUE THREAD

**Issue by tkymmm** [Stirling-Tools/Stirling-PDF#287]
When I load the PDF converted from Excel using the Excel application or this application with "Add Image" or "Sign" and display the preview, it seems that the top and bottom and left and right are reversed.
And, In dark mode, all white areas are black.
No problem with "Multi Tool".
![download](https://github.com/Frooodle/Stirling-PDF/assets/136296842/acbaea8d-1dae-4472-97bc-5a9587e6dbd0)
![download (2)](https://github.com/Frooodle/Stirling-PDF/assets/136296842/4763e0d7-dfa8-4c56-b4b3-d3bf8684545b)

**Comment by JerronAB** [comment]
I'd like to add that I've experienced the same bug, but from multiple PDFs regardless of origin. 
I found out that dragging and dropping a PDF document onto the browser would create this problem, whereas selecting the "choose file" button and opening explorer would work perfectly. 
Hope this helps with replicating and resolving the issue!

**Comment by tkymmm** [comment]
thank you
I will try changing the addition method when I have a similar problem.

**Comment by Frooodle** [comment]
Is this issue still happening?

**Comment by Frooodle** [comment]
Closing ticket for now as old

**Comment by tkymmm** [comment]
This doesn't happen in the latest version (0.28.3), Thank you.
