### ISSUE TITLE
Watermark is mirrored

### ISSUE THREAD

**Issue by kwaun** [Stirling-Tools/Stirling-PDF#290]
I tried to set a watermark on a pdf but it places the watermark mirrored. BTW it doesn't matter the rotation, text or image.

[test_watermark.pdf](https://github.com/Frooodle/Stirling-PDF/files/12197159/test_watermark.pdf)

Default parameters. The default watermark is "Stirling-PDF".

frooodle/s-pdf:0.11.2 Docker image

**Comment by Frooodle** [comment]
This is a known bug that applies to certain PDFs based on their initial rotation values among other things
I Have not found a fix yet. its not all PDFs... Are you able to view the Producer using the change-metadata function is SPDF
To view where the PDF was made to help me debug?

**Comment by kwaun** [comment]
The Producer is "Skia/PDF m117 Google Docs Renderer". The test PDF was generated by Google Docs. 
You're right, I just tried using LibreOffice Writer and the watermark is perfect!

**Comment by Frooodle** [comment]
Should be resolved now
