### ISSUE TITLE
[Feature Request] Add EPUB to PDF conversion

### ISSUE THREAD

**Issue by lukasgabriel** [Stirling-Tools/Stirling-PDF#292]
Add EPUB to the supported file formats for PDF conversion.

**Comment by TheOneValen** [comment]
And vice versa. I Would like to be able to read pdfs on my kindle. So PDF to ePub and/or similar would be great.

**Comment by applesoff** [comment]
to expand on this, it would be great to be able to convert cbz/cbr as well to pdf and vice versa

**Comment by Frooodle** [comment]
These formats added via settings.yml !
![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/77850077/acb6bdaf-5979-4f26-b436-631a0e6a2593)

**Comment by applesoff** [comment]
Is there a docker environmental variable to set?

**Comment by applesoff** [comment]
It looks like the only file formats supported are .epub, .mobi, .azw3, .fb2, .txt, or .docx. Will cbz/cbr be added?

**Comment by Frooodle** [comment]
Sorry forgot to mention in update this variable changed it's name

If you check the settings file you should see the new naming

**Comment by Frooodle** [comment]
Sorry installBookFormats has been removed, feature is no longer their in Stirling-PDF with sadly no replacement currently

**Comment by elkinjosetm** [comment]
Oh ok, thanks!
