### ISSUE TITLE
PDF to Word convert each line 

### ISSUE THREAD

**Issue by vitorcruzfaculdade** [Stirling-Tools/Stirling-PDF#293]
When convert PDF to Word, the result file shows a document with each line converted separately.
Would be nice to have the doc file with all lines in a single text box or, just being followed by each line with no text box whatsover.

To reproduce this condition just convert a PDF to Word using Stirling, then, do the same with ILovePDF and compare the results.

Version 0.11.2

**Comment by Frooodle** [comment]
Pdf to Word uses LibreOffice as backend 
I'll try to see if I can find nicer way but it's hard to balance with space and functions

**Comment by Frooodle** [comment]
Closed for now as its LibreOffice issue, we will investigate other options always but not as part of this ticket
