### ISSUE TITLE
[feature request] Support for local pdf generation from Print Friendly

### ISSUE THREAD

**Issue by Daryes** [Stirling-Tools/Stirling-PDF#295]
Hello,
Would it be possible to support a post query from the "Print Friendly & PDF" browser plugin to generate locally the PDF version of a web page ?
This is a plugin for internet browsers, which give the possibility to review and remove part of a web page, which is useful for ads and the likes, before printing it as a pdf file.

The result is very useful for archiving, but suffer from a major problem : the review and edition is locally done in the browser, but the data is sent to print friendly to send back the pdf file.
While a local print only is available , it is using the browser integrated tools which has a lesser result (lack of compression, margins moving at random, ...)

It seems to me this would be possible, as the browser plugin sends the full page in its final state as html in a POST query. 
Combined with using a local dns record to redirect the plugin to Stirling.

**Comment by Frooodle** [comment]
No browser plugin support sorry
