### ISSUE TITLE
[Feature request] Improve performance of 'Compare' Feature

### ISSUE THREAD

**Issue by Joly0** [Stirling-Tools/Stirling-PDF#298]
Hey, i am trying to compare 2 100MB pdf's and when i do so, Stirling-PDF becomes unresponsive and my browser takes up a huge amount of my pc's memory.
This is especially weird, as i have it installed in a docker container on my server and it should take up all my memory imo.
But nontheless the memory issues, my browser becomes completly unresponsive and notices me, that Stirling-PDF tab is the reason for that

**Comment by Frooodle** [comment]
Compare is client side not server as its pure JS
So it would be client side that takes the hit

As for it crashing, the type of text comparison it does it quite heavy so yeah it probably isnt good for extremely large ones
Ill add a warning for this

**Comment by Joly0** [comment]
Hm, so there is no chance to get this working for larger files?
Had to switch to https://tools.pdf24.org/en/compare-pdf for that task (it seems like it doesnt rely on the client side), but otherwise i love Stirling-PDF and would really like to use that feature aswell :)
But no problem if its not doable. Still great job on this project, highly appreciate your work :D

**Comment by Frooodle** [comment]
I'll see what i can do :P

**Comment by Frooodle** [comment]
Can implement 
https://github.com/kpdecker/jsdiff
