### ISSUE TITLE
Error flattening merged pdfs

### ISSUE THREAD

**Issue by edkedk99** [Stirling-Tools/Stirling-PDF#299]
I have some pdf with some form fields in them. When I flatten them using Stirling PDF it works fine. But if I merge them first and then flatten, the merged file is not flattened.

Is this a bug or expected beharior? The correct procedure is to flatten first and then merge or Stirling PDF is supposed to flatten the pdf regardless of being merged first?

**Comment by Frooodle** [comment]
It should flatten any pdf regardless of anything at all

I'll take a look and see what's going on

**Comment by DimK10** [comment]
I'll try to reproduce the bug.

**Comment by DimK10** [comment]
I can't seem to be able to reproduce the bug in 0.22.8. I have merged two pdf files, one of which has a form, and then flattened. The result pdf seems to be working as expected - the pdf is flattened. The only issue i encountered was that the result pdf could not be opened by my acrobat reader, it showed an error, but when i opened it with chrome, the pdf was as expected. Am i missing something? 

These are the initial pdf files i used:
[sample_pdf_with_form_new.pdf](https://github.com/Stirling-Tools/Stirling-PDF/files/14910845/sample_pdf_with_form_new.pdf)
[test-pdf.pdf](https://github.com/Stirling-Tools/Stirling-PDF/files/14910846/test-pdf.pdf)

The pdf after the merge:
[test-pdf_merged.pdf](https://github.com/Stirling-Tools/Stirling-PDF/files/14910855/test-pdf_merged.pdf)

The flattened one:
[test-pdf_merged_flattened.pdf](https://github.com/Stirling-Tools/Stirling-PDF/files/14910857/test-pdf_merged_flattened.pdf)

**Comment by edkedk99** [comment]
I tested with my own files and I confirm the problem doesn't happen anymore in 0.22.8 version. I could open using evince reader in linux.

I will close this issue
