### ISSUE TITLE
Wrong label for input in HTML to PDF

### ISSUE THREAD

**Issue by deraw** [Stirling-Tools/Stirling-PDF#315]
The input has the label "Select PDF(s)" but it should be "Select HTML or ZIP file(s)":
<img src="https://github.com/Frooodle/Stirling-PDF/assets/10298932/f115b09c-ff0e-4726-8866-3136870c248d" alt="" width="500"/>

**Comment by deraw** [comment]
There is the same issue for cert files in the Cert Sign page

**Comment by Frooodle** [comment]
Resolved while back i think?

**Comment by deraw** [comment]
> Resolved while back i think?

Yes indeed!
