### ISSUE TITLE
[Feature request] Upload PDF via URL

### ISSUE THREAD

**Issue by Royal2000H** [Stirling-Tools/Stirling-PDF#331]
Hi this is a very simple feature request.
For anywhere that you can upload PDF from local computer, would be beneficial to be able to also just provide a direct URL to a PDF available online.

**Comment by kdhrubo** [comment]
Need to ensure that it's a trustworthy URL

**Comment by maninthemiddle01** [comment]
This could also benefit people with low internet bandwidth, for example to load only text or very small PDFs :)
