### ISSUE TITLE
[Feature request] Add support for custom templates files

### ISSUE THREAD

**Issue by hugosxm** [Stirling-Tools/Stirling-PDF#355]
Hi, just updated the image on my k8s cluster and saw all the effort, the app was really good, now it is cleary awesome !!! I was on 0.3.3 i think...

I tried the custom static files customization and it works, but is there a way to customize the template ? Like a want to add a link to the footer for exemple.

On gitea i can add custom templates files to override pages of the app, i think to would be cool to be able to do the same with striling pdf :)

Thanks !

**Comment by Frooodle** [comment]
No currently 
I will work on this enhancement sometime :)

**Comment by hugosxm** [comment]
Wonderfull ! Keep the good work mate !

**Comment by manuelkamp** [comment]
+1

**Comment by fmr-disy** [comment]
Really looking forward to this feature... :)

**Comment by danmfdez** [comment]
Waiting for it 👍

**Comment by Frooodle** [comment]
I have some good news for you all for next release :)
