### ISSUE TITLE
add-image not reliable

### ISSUE THREAD

**Issue by shawshankkumar** [Stirling-Tools/Stirling-PDF#363]
the documentation says that we need to pass an image and the pdf file and based on the location image will be places. I noticed that in some pages the image is being zoomed and the swagger docs are not up to the date. will try to fix this but might need help from someone who knows this code base

**Comment by Frooodle** [comment]
Yes sorry the add image api has been not maintained after it got a UI replacement.

I can try resolve later but I'm quick busy at moment so if you can would be greatly appreciated if you can try resolve!

**Comment by Frooodle** [comment]
Code is 
https://github.com/Frooodle/Stirling-PDF/blob/a0ac2bc02a37fdcb5717fc493a9998f0ba1d680f/src/main/java/stirling/software/SPDF/controller/api/misc/OverlayImageController.java#L28

And 
https://github.com/Frooodle/Stirling-PDF/blob/a0ac2bc02a37fdcb5717fc493a9998f0ba1d680f/src/main/java/stirling/software/SPDF/utils/PdfUtils.java#L334

**Comment by shawshankkumar** [comment]
Hey thanks!

I'll surely give it a try!!!

**Comment by Frooodle** [comment]
Stamp controller has x y override which should result in similar functionality.
