### ISSUE TITLE
Angle threshold in extract-images-scans not working

### ISSUE THREAD

**Issue by Samurai1201** [Stirling-Tools/Stirling-PDF#368]
The angle threshold in the extract-images-scans appears to not be working. In my tests i tried the same pdf with different thresholds and it was rotated for ever setting. Before the update it was working.
Background: im trying to digitize my old photos and want to disable the rotation function, so i previously set the threshold to 180 which worked perfectly.

**Comment by Frooodle** [comment]
Is this still a issue? closing ticket for now will reopen if still ongoing
