### ISSUE TITLE
[Feature request] - Text color selection (Watermark)

### ISSUE THREAD

**Issue by pierrejo** [Stirling-Tools/Stirling-PDF#369]
For adding text *(watermark)* on some documents, the color doesn't stand out and I would have preferred to choose black text, for example. It would be interesting to be able to choose the **text color** for better visibility.

*I'd like to thank the developers for this great tool, which I use every day!*

**Comment by saikumarjetti** [comment]
Can i work on this task.

**Comment by Frooodle** [comment]
Yes!
