### ISSUE TITLE
[Feature request] - Extract tables from PDF

### ISSUE THREAD

**Issue by XSoueiX** [Stirling-Tools/Stirling-PDF#372]
For some months i being using and loving this project, the only thing that still missing to me is be able to extract tables from pdf. One suggestion is to use something like tabula-java (the engine of tabula) to extract all tables from a pdf and then convert to a csv.

I would like to thank the developers, this project is awesome.

Sorry for my grammar, english is not my first language and all i know about is self-taught.

**Comment by Artem-ka-create** [comment]
Hi , i would like to solve this issue , can you assign it ?
