### ISSUE TITLE
Question about basic setup

### ISSUE THREAD

**Issue by thomas-mc-work** [Stirling-Tools/Stirling-PDF#374]
Hello,

I'm trying to build and run a basic docker image locally. Everything works fine in the build process. But the final sites doesn't find all it's assets:

![image](https://github.com/Frooodle/Stirling-PDF/assets/6542498/36e56683-319d-4305-a417-e03ea419bf54)

Theses are my steps:

```
git clone git@github.com:Frooodle/Stirling-PDF.git .
chmod +x gradlew
./gradlew build
docker build -f DockerfileBase -t frooodle/stirling-pdf-base:beta4 .
docker build -t frooodle/stirling-pdf-base:beta4 .
docker run --rm -p 8080:8080 -v $PWD/../data frooodle/stirling-pdf:local
```

Also, is there any reason to have the Dockerfile split into two files (`DockerfileBase` and `Dockerfile`)? I can only see one reference to the `DockerfileBase`.

**Comment by slikie** [comment]
do you have the app path set up?

**Comment by Frooodle** [comment]
Don't build or touch docker base no need 

Only build and run the docker file


The base is to download all the OS and file changes one in a big cached image 
That way when I update my jar image people don't need to redownload huge files

**Comment by thomas-mc-work** [comment]
But isn't your [default image](https://hub.docker.com/layers/frooodle/s-pdf/0.14.2/images/sha256-a0798e46b332172968ebbbf3c1c5a8925526877c73442ac1436e97c70ed5adc4?context=explore) based on the [Dockerfile](https://github.com/Frooodle/Stirling-PDF/blob/main/Dockerfile)? And in the Dockerfile the base image is referenced:

https://github.com/Frooodle/Stirling-PDF/blob/af5bbd88388ee10a220248be7914b978855e8128/Dockerfile#L2

My goal is to improve the docker image build process, based on [our conversation in a pull request](https://github.com/Frooodle/Stirling-PDF/pull/300).

**Comment by Frooodle** [comment]
But you must build the Dockerfile which will grab that base image and everything else etc

**Comment by thomas-mc-work** [comment]
Just to get it right:

1. I need to build the `DockerfileBase`
2. Build the `Dockerfile`, which references the image of the `DockerfileBase`

Is that right?

**Comment by Frooodle** [comment]
"I need to build the DockerfileBase"
Only if you made changes to the DockerfileBase, otherwise no you wuold just pull existing image

"Build the Dockerfile, which references the image of the DockerfileBase"
Yes

**Comment by thomas-mc-work** [comment]
> Only if you made changes to the DockerfileBase, otherwise no you wuold just pull existing image

That's what I'm planning. So can you help me fix the problem mentioned above?

**Comment by thomas-mc-work** [comment]
Hello @Frooodle,
I'm still willing to help here. I just need to know how to properly build the official docker image.

**Comment by Frooodle** [comment]
@thomas-mc-work  Sorry missed these comments i didnt knowy ou were still facing a issue
Build the jar
```
export DOCKER_ENABLE_SECURITY=false
./gradlew clean build
```
Build the base
``docker build -f DockerfileBase -t frooodle/stirling-pdf-base:version8 .``

build the main 
``docker build --build-arg VERSION_TAG=alpha -t frooodle/s-pdf:latest -f ./Dockerfile .``

**Comment by thomas-mc-work** [comment]
It seems like the situation has changed in the meantime: The file `DockerfileBase` has vanished. So the commands end up like that:

    docker build --build-arg VERSION_TAG=alpha -t frooodle/s-pdf:latest .
    docker run --rm -p 8080:8080 frooodle/s-pdf

Thanks for the answers!
