### ISSUE TITLE
Watermark Can Be Deleted, Add option to convert to image afterwards

### ISSUE THREAD

**Issue by lawfulsoftware** [Stirling-Tools/Stirling-PDF#381]
The resulting watermark can be deleted in Foxit PDF Editor by selecting and deleting each object. Running the watermarked PDF through the Flatten process did not prevent deletion.

**Comment by Frooodle** [comment]
This option exists for a few other features, seems reasonable to add it as a extra checkbox for image conversion

**Comment by Frooodle** [comment]
This option exists for a few other features, seems reasonable to add it as a extra checkbox for image conversion 

And yeah flattern is only to remove interactive elements like textboxes

**Comment by Frooodle** [comment]
For new devs taking this, you can refer image conversion from
https://github.com/Stirling-Tools/Stirling-PDF/blob/main/src/main/java/stirling/software/SPDF/controller/api/security/RedactController.java#L81

**Comment by N-Smith-00** [comment]
Hi, I'd like to work on this if nobody else has yet

**Comment by Isaac-Whiz** [comment]
I would like to take on this issue, however am requesting for more delight because it seems am not getting this issue right. [@lawfulsoftware](https://github.com/lawfulsoftware) are you suggesting that the conversion process should not allow deletion of a watermark automatically so that it requires consent of the user to get it deleted? Thank you.

**Comment by shivamsince0502** [comment]
Hii @lawfulsoftware, Is the issue resolve, if now i would like to take the issue and solve it.

**Comment by Frooodle** [comment]
Still existing

**Comment by shivamsince0502** [comment]
@lawfulsoftware I would like work on the issue i just some vague idea it will be better if you give a brief about it

**Comment by Frooodle** [comment]
in watermark feature, add a checkbox to concert the PDFs content into a image so it cant be editted

For new devs taking this, you can refer image conversion from
https://github.com/Stirling-Tools/Stirling-PDF/blob/main/src/main/java/stirling/software/SPDF/controller/api/security/RedactController.java#L81

**Comment by shivamsince0502** [comment]
@lawfulsoftware is there any group where i can join and discuss about the issues i am done with the local setup its working

**Comment by Frooodle** [comment]
Discord would be best

**Comment by mylk13** [comment]
Hi, I saw the issue has been assigned to the same person for quite some time and has not been done. I am assuming it is open for contribution.
I've created a pull request for this and I am happy to be assigned to this issue.
