### ISSUE TITLE
PDF Mulltitool cannot delete pages from secured PDFs

### ISSUE THREAD

**Issue by rcjcarr** [Stirling-Tools/Stirling-PDF#383]
When deleting pages from a secured PDF document using the PDF Multitool, Stirlinig PDF returns blank pages after execution/download.

**Comment by rcjcarr** [comment]
Which Stirling-PDF tool can do this (remove security) ?

**Comment by Frooodle** [comment]
Remove password 

In the security section

**Comment by rcjcarr** [comment]
The 'Remove Password' feature is asking for a password, which I don't have. Just for some context, my PDF financial statements are 'secured' but I'm not quite sure if that means encrypted or otherwise just locked. I can use Windows PDF Manager to add/remove/re-order/combine pages on such 'secured' documents. After manipulation by PDF Manager I end up with an 'unsecured' document, which is fine. My guess is that these 'secured' PDFs are not encrypted but just somehow protected from easy tampering. I was just wondering if this functionality could be added to Stirling-PDF. Otherwise, I will need to fallback on PDF Manager to organize my financial statements (consolidate them by year usually).

**Comment by rcjcarr** [comment]
Thanks for your comments. I'm not about to pass financial documents to a web-base service, so will keep using PDF Manager for now as it runs locally. Hopefully this functionality can be added to Stirling-PDF at some point. Love your app by the way; nice work.

**Comment by rcjcarr** [comment]
Ok thanks for that. PDF Manager is inexpensive at $12.79 CAD (Microsoft App Store) so will keep using that for now. I'll keep the Cisdem solution on file. This latter seems more polished but costs $49.99 USD.

**Comment by Frooodle** [comment]
One of the easier changes to do :)
It should appear in the alpha tag for now until a release is made

**Comment by Frooodle** [comment]
> Ok thanks for that. PDF Manager is inexpensive at $12.79 CAD (Microsoft App Store) so will keep using that for now. I'll keep the Cisdem solution on file. This latter seems more polished but costs $49.99 USD.

Remember Stirling-PDF accepts donations! haha :)

**Comment by rcjcarr** [comment]
Wonderful; alpha tag version can now remove passwords! Well done.

**Comment by rcjcarr** [comment]
The only thing that I would add is automatic password removal when using the PDF-Multitool on secured PDFs. Otherwise this is a two-step process (1. Remove Password and 2. any function of PDF-multitool).

**Comment by Frooodle** [comment]
> @Frooodle You work very quickly. Impressive!
> 
> Let me know if you need help with anything else.  I have a script to import custom fonts.  Do you want me to submit a PR?

Depends how the script would function etc

**Comment by Frooodle** [comment]
> The only thing that I would add is automatic password removal when using the PDF-Multitool on secured PDFs. Otherwise this is a two-step process (1. Remove Password and 2. any function of PDF-multitool).

Agreed, makes sense
I'll have it as a planned feature

**Comment by Frooodle** [comment]
I like it, environment controlled and customisable 

I'm not sure about the 2 different modes as it might lead to over complications if its different types of config but if its just volume mapped vs not then yeah sounds good 
Make a PR and add documentation to readme!

**Comment by Frooodle** [comment]
Handling owner and user password is weird because generally only user password is used within encryption layer
Owner password is just extra setting not actually stopping anything unless software supports it 

So focused on user
Owner password support should be seperate feature not part of this one

**Comment by Frooodle** [comment]
Also due to legal reasons I don't want password cracking as part of this application

**Comment by Frooodle** [comment]
It's less legal and more corporate friendly  reason and moral.

I want a application corporations and people don't feel bad to use

**Comment by rcjcarr** [comment]
I can appreciate the last comment. It's just a shame that most software won't allow combining secured PDFs into one big file, _i.e_., won't allow users from merging **their own** yearly financial statements in one big file.

**Comment by Frooodle** [comment]
> I can appreciate the last comment. It's just a shame that most software won't allow combining secured PDFs into one big file, _i.e_., won't allow users from merging **their own** yearly financial statements in one big file.

I will add support for multi tool to support non passworded but still encrypted PDFs in future, its why i am keeping this ticket open

**Comment by rcjcarr** [comment]
ok sounds good.

**Comment by Frooodle** [comment]
I just checked and multi tool is able to change pages from a secured PDF
Can you please open the pdf in question with the stirling-pdf
get-info-on-pdf
function

And screenshot the encryption section? the pdf i tested on has
![image](https://github.com/Frooodle/Stirling-PDF/assets/77850077/8f691972-c905-47d1-a9e6-6fcb33873219)
