### ISSUE TITLE
Feature Requests: Multipage Layout

### ISSUE THREAD

**Issue by lawfulsoftware** [Stirling-Tools/Stirling-PDF#385]
An option to add borders around each page would be helpful.

An option to set the output size would be great. For example, legal, 11x17, or 13x19 would make the output more useable, especially at the higher pages per sheet values.

An option to enable or disable debugging error messages:

<img width="672" alt="image" src="https://github.com/Frooodle/Stirling-PDF/assets/96336813/a8eb0727-f7a0-48dd-b1df-5e51b21ff43c">

Also, once this error is dismissed, clicking on Submit without adding a file causes the page to become unusable as the button permanently changes to "Processing..." until the page is reloaded.

**Comment by Frooodle** [comment]
Can you make these seperate tickets sorry, hard to track each one 

For
An option to set the output size would be great. For example, legal, 11x17, or 13x19 would make the output more useable, especially at the higher pages per sheet values.
Is this output size of the final document?

**Comment by Frooodle** [comment]
``An option to add borders around each page would be helpful.`` addded in 0.14.4
