### ISSUE TITLE
Feature request: add serif and sans serif fonts to "Sign" module

### ISSUE THREAD

**Issue by econo202** [Stirling-Tools/Stirling-PDF#391]
Currently the "Sign" module has few fonts to choose from, but lacks any standard serif and sans serif ones.

It would be great if e.g. Arial and Times New Roman (or any other equivalent fonts) were added to the list of available ones.

**Comment by Frooodle** [comment]
https://fonts.google.com/specimen/Arimo
https://fonts.google.com/specimen/Tinos

Seem to be arial and times new roman equivalents which i can use

Do you have a preference on which i should add between them?

**Comment by econo202** [comment]
Both Arimo and Tinos look great.

**Comment by econo202** [comment]
Any news on this issue?

**Comment by Frooodle** [comment]
> Both Arimo and Tinos look great.

I'd rather add one or the other, can you choose between them

**Comment by econo202** [comment]
If it's necessary to choose one, I'd get Arimo.

Would it be possible to also add Tinos as the serif font in future?

**Comment by Frooodle** [comment]
Added both for next release
