### ISSUE TITLE
Split pages and Remove Pages maintains to much metadata of previous pages etc

### ISSUE THREAD

**Issue by lawfulsoftware** [Stirling-Tools/Stirling-PDF#401]
Related to #400 

Input file size: 545 KB (11 pages)
Output file size: 519 KB (2 pages)

Same issue whether done through the UI or via API.  It does not seem to matter which pages are removed.  A second test which removed all pages with images resulted in a two page file that was even larger at 521 KB.

Additionally, the Swagger UI does not work for this endpoint.  The pagesToDelete value is incorrectly set to "query" so it is added to the request URL as a query parameter.  This results in a 405 error saying that GET is not allowed even though the curl request method is POST.

**Comment by Frooodle** [comment]
I believe a lot of this metadata is embedded fronts etc not sure what can be done, closing this ticket for now
