### ISSUE TITLE
converting pdf to word problem

### ISSUE THREAD

**Issue by ShlomiD83** [Stirling-Tools/Stirling-PDF#420]
Hi,
If I convert a PDF that's written in Hebrew the letters in the DOCX output file are backwards.
Is that a knows issue?
When using ILovePDF it converts it correctly.

Please advise.

**Comment by sahaj24** [comment]
Some conversion tools have options or settings specifically related to text direction and encoding. Ensure that the settings for language and text direction are correctly selected.

**Comment by ShlomiD83** [comment]
> Some conversion tools have options or settings specifically related to text direction and encoding. Ensure that the settings for language and text direction are correctly selected.

where?

**Comment by Frooodle** [comment]
Hey @@ShlomiD83 can you give/make a example pdf I can test this on? 
We use libre office in backend so it's not our code but normally this is a font issue 
I can try investigate for you

**Comment by ShlomiD83** [comment]
> Hey @@ShlomiD83 can you give/make a example pdf I can test this on? We use libre office in backend so it's not our code but normally this is a font issue I can try investigate for you

I not able to recreate the problem, will try again.
it only happens if I try to convert a pdf that was saved in MS word back to DocX, but I don't think that was my issue before.

**Comment by ShlomiD83** [comment]
@Frooodle 
[טופס בקשה לשינוי הרכב מסלולי השקעה בפוליסות לשכירים ולעצמאים - ביטוח חיים פנסיוני.pdf](https://github.com/Stirling-Tools/Stirling-PDF/files/13800816/-.pdf)
You can try with this file, I've converted it to Docx and the writing is backwards.

**Comment by Frooodle** [comment]
This might be a issue unfixable to do with libreOffice, but it could also be a font issue.. need to investigate

**Comment by Frooodle** [comment]
Is this still a issue? we also support multi font types now to be installed along side docker  etc
closing ticket for now

**Comment by ShlomiD83** [comment]
> Is this still a issue? we also support multi font types now to be installed along side docker etc closing ticket for now

I don't know, I've stopped using this app a few months ago.
