### ISSUE TITLE
Security issue, merge signed documents results in a new pdf witch is signed

### ISSUE THREAD

**Issue by ikerib** [Stirling-Tools/Stirling-PDF#435]
Hi,
we are using this project a lot in our city council, thanks!

We see a problem: If we take two different pdf which are digitally signed and merge them, the result is a new document with the two signatures. Which is not correct, it should be a new document without signatures.

Thank you!

**Comment by kintaro1981** [comment]
I work for an Italian municipality and this is going to stop us to is it. 🙁

**Comment by Frooodle** [comment]
Should this be a flag like on/off for this or should it always remove the signatures?
Sorry for getting to this so late

**Comment by ikerib** [comment]
The resulting pdf can’t be signed. Someone can add pages to a signed document…

**Comment by Frooodle** [comment]
Removed a visual signature is not always possible as the visual isnt always linked.

Would i be acceptable to remove digital but keep visual in this usecase?

**Comment by Frooodle** [comment]
Also as a spinoff from this but probably good to have a method to remove all signatures regardless #1138

**Comment by ikerib** [comment]
in our case, we think that both elements should be deleted.

This is the problem:
- Person A creates a pdf and signs it => Document A (And it has its purpose, another procedure).
- Person B creates a pdf and signs it => Document B (And it has its purpose, another procedure).

Now, we have a procedure, in which we attach those two pdf files with sterling, the result should be without any signature, because this third document has not been signed neither by person A nor by person B as a whole (they have only signed their part) and this can bring legal responsibilities.
