### ISSUE TITLE
Compliancy checks in get-info-on-pdf are not working

### ISSUE THREAD

**Issue by ps73** [Stirling-Tools/Stirling-PDF#443]
I've checked it for this demo file which is a compliant PDF/A-1b document:
[example_065.pdf](https://github.com/Frooodle/Stirling-PDF/files/13175080/example_065.pdf)

[This validator pdfen.com](https://www.pdfen.com/pdf-a-validator) shows that this file is PDF/A compliant:
<img width="380" alt="image" src="https://github.com/Frooodle/Stirling-PDF/assets/17291660/d64ac7fa-4380-45da-91ad-5bce6def81a9">

But Stirling-PDF shows that this file is not compliant:
<img width="380" alt="image" src="https://github.com/Frooodle/Stirling-PDF/assets/17291660/8d05ac96-52f9-4039-aa93-dbd3fc8e49d2">

**Comment by Frooodle** [comment]
Was this fixed in end?

**Comment by Frooodle** [comment]
No response so closing
