### ISSUE TITLE
Swagger endpoint doesn't work with https

### ISSUE THREAD

**Issue by Shrinkvine** [Stirling-Tools/Stirling-PDF#451]
I am using nginx to proxy this application. My url is https://mydomain.com/swagger-ui/index.html, but when using swagger, it uses  http://mydomain.com/swagger-ui/index.html  (uses http when it should be https), causing no requests to work through swagger.

**Comment by Frooodle** [comment]
Can not reproduce with https://pdf.adminforge.de/ as example
