### ISSUE TITLE
Overlay 2 PDF

### ISSUE THREAD

**Issue by ipod86** [Stirling-Tools/Stirling-PDF#462]
Hello, 

I often use the function to put 2 PDFs on top of each other with other tools.  

For example, place 2 PDFs with 30 pages on top of each other so that a PDF with 30 pages comes out where they are combined.  

It would also be practical if you could, for example, take a PDF with 100 pages and then place 4 PDFs with 25 pages on top of it in a defined order.

**Comment by Frooodle** [comment]
Done for next release, in alpha now

**Comment by Frooodle** [comment]
Tried to have it accommodate all the weird ways
Accepts 3 different ways
'SequentialOverlay' for sequential application, 'InterleavedOverlay' for round-robin application, 'FixedRepeatOverlay' for fixed repetition based on provided counts
Say you have 4 overlay files each 3 pages
SequentialOverlay is file1-123  then file2-123 etc
InterleavedOverlay is file1-1 file2-1 file3-1 file4-1 file1-2 etc
FixedRepeatOverlay is your 25 25 25 25 one where if you give it 25 30 it will run 25 times through file1 and 30 times through file2

**Comment by ipod86** [comment]
With my poor English, I don't understand the different modes at the moment, but I'll test it diligently when it's available.  When will the realese appear?

**Comment by Frooodle** [comment]
released in latest 0.17.0!

**Comment by ipod86** [comment]
It doesn't quite work out yet.  I use 0.17.2.  

Only the first page of the second PDF is taken and not, for example, page 2 for page 2 in the overlay.  

I always test it with this PDF.  As a result, if it works, you should get A1, B2 and B3 in the PDF.

[123.pdf](https://github.com/Frooodle/Stirling-PDF/files/13732879/123.pdf)
[abc.pdf](https://github.com/Frooodle/Stirling-PDF/files/13732882/abc.pdf)
Wrong result 
[123_overlayed.pdf](https://github.com/Frooodle/Stirling-PDF/files/13732886/123_overlayed.pdf)
