### ISSUE TITLE
Remove-Pages throws index out of bounds if a single page is spezified, but not when a range is spezified

### ISSUE THREAD

**Issue by Christianthelongone** [Stirling-Tools/Stirling-PDF#473]
If you specify a single page that should be deleted but is outside the PDF, an error message is displayed. However, if you specify a range that is outside the PDF, no error message is displayed.

**Comment by Christianthelongone** [comment]
to clearify:
PDF has 2 pages.
pageNumbers = 3 -> throws an error
pageNumbers = 3-4 (or 3-3) no error is thrown

In my opinion, no error should be thown and the PDF should be processed

**Comment by Frooodle** [comment]
Should be fixed in latest versions
