### ISSUE TITLE
in  word to pdf ,a problem with directory structure,

### ISSUE THREAD

**Issue by charlesjosn** [Stirling-Tools/Stirling-PDF#482]
When using directories such as "一,   1.1,   1.2,   1.3" and "二, 2.1,   2.2，2,3" in a Word document，
![a](https://github.com/Frooodle/Stirling-PDF/assets/43372069/f0934e6f-1b95-462f-9fa1-2a9459c546dc)
use word to pdf ，it become：“一，一.1，一.2，一.3”and “二，二.1，二.2，二.3”
![b](https://github.com/Frooodle/Stirling-PDF/assets/43372069/af6dd835-c6ec-429c-b4bf-a9c4249ebfc4)

**Comment by Frooodle** [comment]
Issue with libreoffice, might be font related but not sure. Not issue with base stirling pdf
