### ISSUE TITLE
uncompress 

### ISSUE THREAD

**Issue by 3052** [Stirling-Tools/Stirling-PDF#486]
Is it possible to uncompress PDF? similar to:

~~~sh
# uncompress
qpdf --stream-data=uncompress a.pdf b.pdf
# compress
qpdf b.pdf c.pdf
~~~

https://github.com/qpdf/qpdf/releases

**Comment by Frooodle** [comment]
No not Currently 
What's the usecase for this?

**Comment by 3052** [comment]
I had some text I wanted to remove - originally I was looking into cropping it or redacting, but it seems "permanent" crop is actually quite difficult. however if you can uncompress the PDF, in my case at least I was able to just literally edit it like a text document then compress again
