### ISSUE TITLE
"Back to Main Page" text is covering content.

### ISSUE THREAD

**Issue by SteadyStatus21** [Stirling-Tools/Stirling-PDF#489]
![image](https://github.com/Frooodle/Stirling-PDF/assets/73841304/4ddd2f92-5a52-48de-9aef-a2fac62c6bbb)

I noticed this today, when opening a PDF, not sure what happened...

**Comment by SteadyStatus21** [comment]
> Is this resolved?

Hey! Haven't had a chance to pull latest docker image. Get out of work at 5:30, I'll let you know then!

**Comment by SteadyStatus21** [comment]
> > Is this resolved?
> 
> Hey! Haven't had a chance to pull latest docker image. Get out of work at 5:30, I'll let you know then!

Yes, the issue is resolved for me now.

**Comment by sNiXx** [comment]
Running the latest app version 0.17.2, I can still see this same issue:
![image](https://github.com/Frooodle/Stirling-PDF/assets/3066873/dd920517-4dc2-433f-ba65-b3d1091b7a85)

Also, I was wondering about the logo next to the page numbers. It seems a bit misplaced and - like the house icon mentioned above - links to the main page:
![image](https://github.com/Frooodle/Stirling-PDF/assets/3066873/91662f52-c4bb-4d70-9d4f-ed106f7496df)

**Comment by sNiXx** [comment]
@Frooodle Should I open another issue for this? This issue is still there for me in the latest app version 0.19.1.

**Comment by Frooodle** [comment]
Re opened

**Comment by Frooodle** [comment]
> @Frooodle Should I open another issue for this? This issue is still there for me in the latest app version 0.19.1.

Just to confirm if on chrome can you press f12 right click refresh button and do hard refresh and clear cache
Just to confirm it's using latest files

**Comment by sNiXx** [comment]
Yes, I have just repeated those steps on LibreWolf and Brave and the result is the same.

I guess the text is shown because it is defined (twice) here:
```
<a id="backToHome" class="toolbarButton hiddenLargeView" title="Back to Main Page" tabindex="30" data-l10n-id="back_to_home" href="/">Back to Main Page
<span data-l10n-id="back_to_home_label">Back to Main Page</span>
</a>
```
Maybe something like this would make more sense?
```
<button id="backToHome" class="toolbarButton hiddenLargeView" title="Back to Main Page" tabindex="30" data-l10n-id="back_to_home" onclick="location.href='/'">
<span data-l10n-id="back_to_home_label">Back to Main Page</span>
</button>
```
Btw, this can also be seen when accessing the page from a mobile device or decreasing window size, so secondaryBackToHome is also shown:
![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/3066873/31d47eb6-0501-4f46-b726-2d1ebb4882a6)

**Comment by ydkmlt84** [comment]
![Screenshot_20230225_125307](https://github.com/Stirling-Tools/Stirling-PDF/assets/2887742/511db72b-8ae2-42ba-b419-dd9693a79c1e)
If I delete the words after the ::before tag, in the edge console, it goes away.

**Comment by ydkmlt84** [comment]
> ![Screenshot 2024-02-10 133513](https://private-user-images.githubusercontent.com/2887742/303858311-0f789e9c-a4f1-4e99-810a-84de9bbce9fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1OTA4NTYsIm5iZiI6MTcwNzU5MDU1NiwicGF0aCI6Ii8yODg3NzQyLzMwMzg1ODMxMS0wZjc4OWU5Yy1hNGYxLTRlOTktODEwYS04NGRlOWJiY2U5ZmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTBUMTg0MjM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjdmOTcyNmU2NTNlYjNjNjVjOTljYWUyMGYxOWE4NDVkZTM3NmY1MDJjZGZhYTg5MmQzMGU0ODZmNzEyOTA4OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7GTrw8Eg5-EiUsGnUkRgaKnkhllZiOXYKzLDLjwK_A4)
> 
> If I delete the words after the ::before tag, in the edge console, it goes away.

It appears that I am using a different version than the latest one. I was using a template from Portainer. I am going to comment on their repo. Just wanted you to know it looks to be fixed when looking at this repo. `frooodle/s-pdf:0.18.1`

**Comment by urjeetpatel** [comment]
Is that "Back to Main Page" button even needed?
A user can always click the Stirling Pdf logo to get back to the home page.

It looks like since this is a link instead of a button in the code, it is being styled differently.

**Comment by Frooodle** [comment]
> Is that "Back to Main Page" button even needed?
> A user can always click the Stirling Pdf logo to get back to the home page.
> 
> It looks like since this is a link instead of a button in the code, it is being styled differently.

No it can be removed if anyone wishes to raise pr
