### ISSUE TITLE
Add support for single operation PDF->Images->PDF

### ISSUE THREAD

**Issue by pjamar** [Stirling-Tools/Stirling-PDF#492]
This is an operation that is useful when signing PDFs digitally, with a signature as an image or not, so they're more difficult to edit. In these cases you do not want the other party signing a different or tweaked document.

So, for clarity, the app would:
 1. Accept a PDF as input
 2. Accept parameters to the PDF->Image conversion (image type, color, dpi)
 3. When executed it will convert the PDF to images and back to a PDF.
 4. Send this new PDF to the user (as a download).

Thanks!

**Comment by Frooodle** [comment]
How about one of these

Copy proof pdf creater
Image only pdf creater 
Non editable pdf creater

Maybe simplest would be 
Make unelectable pdf?

**Comment by pjamar** [comment]
I meant the "non-editable" one  :)

**Comment by hendrix04** [comment]
This is exactly what I am looking for :D

I tried to set it up via a pipeline, but it wouldn't work. I don't think it necessarily needs a name if it could be a default pipeline option.

Otherwise, I would call it "Force Flatten", "Static", or something like that.

**Comment by Frooodle** [comment]
Fyi Next release the flattern option will be enhanced for this 

Codes done just waiting for release

**Comment by hendrix04** [comment]
Awesome! Thanks!!
