### ISSUE TITLE
Markdown to PDF

### ISSUE THREAD

**Issue by bonelifer** [Stirling-Tools/Stirling-PDF#507]
Tried converting a Markdown file to PDF. Didn't handle the tables at all.  I used md-to-pdf locally as well, using it's WeasyPrint engine. It rendered the PDF complete with tables properly formatted instead of being plaintext.

https://md-to-pdf.fly.dev

Here's the MD and two PDF's.
[Bluetooth.md](https://github.com/Frooodle/Stirling-PDF/files/13623654/Bluetooth.md)
[Stirling-weasyprint.pdf](https://github.com/Frooodle/Stirling-PDF/files/13623655/Stirling-weasyprint.pdf)
[md-to-pdf-weasyprint.pdf](https://github.com/Frooodle/Stirling-PDF/files/13623656/md-to-pdf-weasyprint.pdf)

**Comment by bonelifer** [comment]
It would also be nice to have the option to use css with it and store that in settings.

**Comment by sbplat** [comment]
Fixed in #694
