### ISSUE TITLE
Allow to run the container as non root

### ISSUE THREAD

**Issue by quentinus95** [Stirling-Tools/Stirling-PDF#508]
Following #157, I would like to know if it could be possible to allow using the `user` Docker directive, instead of only the environment variables.

Current configuration requires running the container as root, and then trust that it will switch to the specified UID/GID. This presents a security risk.

Could it be possible to allow the container to run as a non root? It was possible before version 0.13.

To test it, you can simply use the command:

> docker run -it --user 2000 frooodle/s-pdf:0.15.1

**Comment by Frooodle** [comment]
I believe this is supported now, or at least via

```
   PUID=1000 \
    PGID=1000 \
    UMASK=022
    ```

**Comment by quentinus95** [comment]
@Frooodle I'm sorry but the current solution you provide does not allow running the container in rootless.
I created the following issue to provide more explanations: #1516. Let me know if you need more details :pray:
