### ISSUE TITLE
[Feature request]  Add an image as background with control its opacity

### ISSUE THREAD

**Issue by jellibianas** [Stirling-Tools/Stirling-PDF#519]
the idea is to add the stamp functionality to the Stirling-PDF solution by putting an image in the background of a PDF document with the option to control the opacity.
<img width="227" alt="stamp" src="https://github.com/Frooodle/Stirling-PDF/assets/12160890/6dd86454-860e-40a1-857a-bd9b7d88d25e">

**Comment by souviksenapati** [comment]
Hey, @Frooodle @sbplat I have made the python code to add stamp in a pdf and also adjust its opacity, can you help me with how I can add that to the project

**Comment by Frooodle** [comment]
If possible id prefer a java PDFBox version of this to avoid going to CLI when possible for the external python call.

However to add this with python you can play the file in /scripts
and I can add UI after :)

**Comment by sbplat** [comment]
Hi @souviksenapati! You can join our [Discord server](https://discord.gg/ZAfjPsrfsx) for help and to discuss further.

**Comment by souviksenapati** [comment]
Hey, @Frooodle @sbplat I have uploaded my program in the script and also provided demo screenshot of the output can you please review that!
