### ISSUE TITLE
Image to PDF Page Size Issue

### ISSUE THREAD

**Issue by lawfulsoftware** [Stirling-Tools/Stirling-PDF#523]
Since the watermark can be deleted even if flattened, I am converting the watermarked PDF to an image and then back to PDF.  The problem is that I cannot control the page size.  The source document is 8.5x11 (Letter).

Fill Page stretches the source document into A4.
Maintain Aspect Ratios crops part of the page and adds white bars at the top in order to fit the source document into A4.
Fit Page to Image maintains the aspect ratio of a letter page however the output is 35.42 inches by 45.82 inches.  I receive the same result if I drag the PNG files into Foxit.  The PNG files were created using StirlingPDF to Image using the default of 300 dpi.

For all three options, it would be ideal to be able to specify the dimensions of the PDF output.  The usual choices will be either Letter or A4 however other sizes, and even custom sizes, might be desirable for some use cases.

As a further feature request, it would be nice to specify global defaults since, in North America, metric paper sizes, although much better, are very hard to find and are very rarely used.

I am running the alpha Docker container with the following digest: sha256:5327c72ff21727812e3841ab3592fc999022d7c2307b00be4dc767234bed55b0

**Comment by sbplat** [comment]
V2 will have the option to customize the page size of the PDF.

**Comment by sbplat** [comment]
No problem! V2 is currently under development and has a decently long way to go. You can view the development in the `v2`/`v2-wip` branch and in the project [roadmap](https://github.com/orgs/Stirling-Tools/projects/2).

**Comment by Frooodle** [comment]
We ahve other issue tickets raised regarding inconsistent page sizing across tools, this will be taken up in those

**Comment by kelvinchin12070811** [comment]
I know this is potentialy a spam but the v2 dev progress seems like about a few months without activities now. I know that the team is working very hard on v1 as there're many commits and project cards moving on it. But is there any plan to make this into v1 instead as this is indeed a very useful feature?

**Comment by smm9509** [comment]
now I'm using V2 and I'm not seeing the "Fit Page to Image" option.
