### ISSUE TITLE
Feature Request:  When using Multi-Tool to have page number displayed when hovering over a page

### ISSUE THREAD

**Issue by tkotz8105** [Stirling-Tools/Stirling-PDF#527]
In the Multi-Tool window when a PDF is loaded, when hovering over a page, five icons are displayed for "move left", "move right", "rotate left", "rotate right" and "delete page".  I would like to have added the page number to be displayed as well.

**Comment by souviksenapati** [comment]
Hey @Frooodle if the feature still not been added can you assign this to me i will be happy to work on this

**Comment by souviksenapati** [comment]
@Frooodle  can you help me, which is the source file for adding the  feature so that I don't need to go through all the files

**Comment by Frooodle** [comment]
https://github.com/Frooodle/Stirling-PDF/blob/main/src/main/resources/templates/multi-tool.html

https://github.com/Frooodle/Stirling-PDF/tree/main/src/main/resources/static/js/multitool

**Comment by mannam11** [comment]
@Frooodle can you please review the pull request..?
