### ISSUE TITLE
Feature(ci): Build image on pr for testing

### ISSUE THREAD

**Issue by nawramm** [Stirling-Tools/Stirling-PDF#534]
## Description:  
Currently, the CI process does not include building a Docker image when a pull request is opened. This feature request aims to enhance the CI pipeline by automatically building a Docker image associated with the pull request.  

## Proposed Solution:
Create a workflow that builds a Docker image based on the pull request code. This will allow contributors and maintainers to test changes in an environment that closely mirrors the production setup.  

## Benefits:  
- Improved testing coverage: Docker image builds can catch issues specific to the image version early in the development process.
- Streamlined testing for contributors: Contributors can easily verify their changes by testing the container before merging.

## Additional Information:  
I am willing to contribute to the implementation of this feature and can allocate time later this week to work on it. If there are specific requirements or suggestions for the implementation, please provide them, and I'll do my best to assist.

**Comment by Frooodle** [comment]
I have been meaning to setup something which will build all 3 docker containers and start them with a basic docker compose  healthcheck like

healthcheck: 
        test: ["CMD-SHELL", "/bin/bash set -o pipefail; curl --insecure --silent -m 2 http://localhost:8080/ | grep 'Stirling-PDF' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s
        
        
 And run it twice, once with AUTH once without...
 
 But never got around to it.. i 100% see the benefit of this and would appreciate the help!

**Comment by nawramm** [comment]
While the basic health checks would help when it comes to things like #531, what comes to mind is PRs which introduce new features or extend existing ones. Pushing an image to a registry can provide maintainers and contributors with a convenient way to test the feature.

It could be perhaps pushed on a need basis, determined by specific a label to the PR . This way, image upload would be selectively triggered for PRs that may require additional testing.

**Comment by Frooodle** [comment]
I think this serves two purposes 
We can have one to test the PRs and not to push

And another to push for manual testing
And have it controlled by flags?

**Comment by Frooodle** [comment]
But I wouldn't want to overload github actions and ideally Devs can test locally

**Comment by Frooodle** [comment]
I'd rather provide a script for Devs to use which will build everything locally or something
