### ISSUE TITLE
Feature request: Sync Scroll or cursor sync during comparison

### ISSUE THREAD

**Issue by mxav1111** [Stirling-Tools/Stirling-PDF#562]
Can we have sync up scrolling when two files can be compared in two windows are open side by side? One window is the output generated (text file) from ocr and second is the  original pdf window.
Alternatively (better) , can we have cursor or a marker in pdf keeps moving as we navigate inside text file on one side for changes when both windows are open side by side.

This could be of huge convenience; as once the text file is generated from ocr , we need to correct the output characters where scan couldn't identify the correct characters.

Also if possible,  add support of indian languages. 

Thanks for your help.

**Comment by Frooodle** [comment]
Do you mean this for a certain feature to have this

Or the standalone side by side comparison as a feature in itself? 

Also all languages are added and translated by users themselves 
If you wish to add the translations yourself there is documentation on how to add your language to the app, then if you merge it in others can benefit too!

**Comment by Frooodle** [comment]
https://github.com/Frooodle/Stirling-PDF/blob/main/HowToAddNewLanguage.md

**Comment by mxav1111** [comment]
> Do you mean this for a certain feature to have this
> 
> Or the standalone side by side comparison as a feature in itself?
> 
> Also all languages are added and translated by users themselves If you wish to add the translations yourself there is documentation on how to add your language to the app, then if you merge it in others can benefit too!

Thank you for quick response.  I will check on language part but probably out of my bounds.

Yes it works would be nice if it could be like a standalone (visually side by side windows) , with  freezing, unfreezing, adjustable scroll for example during unfreeze mode scrolling independently to navigate first file say on  page 4 and second file page 6 ,  then freeze so scroll both in sync.
