### ISSUE TITLE
Error when convert PDF to HTML

### ISSUE THREAD

**Issue by paulocoutinhox** [Stirling-Tools/Stirling-PDF#580]
Hi,

Im getting this error on my PDF:

<img width="1544" alt="image" src="https://github.com/Frooodle/Stirling-PDF/assets/395096/6d752fc4-378a-40d7-85b6-65f2acfe0c51">

**Comment by Frooodle** [comment]
504 normally means nginx issue
Please follow other 504 tickets for nginx config help
