### ISSUE TITLE
502 error while converting PDF to Image

### ISSUE THREAD

**Issue by eXqusic92** [Stirling-Tools/Stirling-PDF#595]
502 error
![image](https://github.com/Frooodle/Stirling-PDF/assets/77026622/a08fe2ea-64cf-41df-9e0b-d9d33e706c3c)

**Comment by eXqusic92** [comment]
Forgot to mention: deployed with Docker and reverse proxied with Apache

**Comment by Frooodle** [comment]
It most likely is caused by your Apache reverse proxy missing certain settings... But I am unable to help sorry

**Comment by shubham19091995** [comment]
> 502 error ![image](https://private-user-images.githubusercontent.com/77026622/293184011-a08fe2ea-64cf-41df-9e0b-d9d33e706c3c.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3OTE4NzEsIm5iZiI6MTcwMzc5MTU3MSwicGF0aCI6Ii83NzAyNjYyMi8yOTMxODQwMTEtYTA4ZmUyZWEtNjRjZi00MWRmLTllMGItZDlkMzNlNzA2YzNjLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOFQxOTI2MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZWFiYmE5ZDE3NjQwNzIxYzRkN2YzMmYxNGE1N2U2YzYyZWI1ZjllN2JlNTg5ODk4ZTNkMjA2YmIwZGRjY2JiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BqMBBxRtzW2OkDdM555N1qje9P5FBRLGsDmQyE8MMms)

Still this issue exists ??? I am not able to replicate this , I am able to convert it .

**Comment by Maycon1993** [comment]
Nossa,legal ter uma comunidade que possa nos auxiliar..

**Comment by eXqusic92** [comment]
Yes, issue still exists.Maybe someone who encountered same problem can help. Here is what I found in Apache logs
```
[Thu Dec 28 11:57:06.778133 2023] [proxy_http:error] [pid 1980388] (20014)Internal error (specific information not available): [client 172.225.37.43:24341] AH01102: error reading status line from remote server 127.0.0.1:8080, referer: https://spdf.mydomain.com/pdf-to-img
[Thu Dec 28 11:57:06.842029 2023] [proxy:error] [pid 1980388] [client 172.225.37.43:24341] AH00898: Error reading from remote server returned by /api/v1/convert/pdf/img, referer: https://spdf.mydomain.com/pdf-to-img
[Thu Dec 28 17:20:37.388104 2023] [proxy_http:error] [pid 2017226] (20014)Internal error (specific information not available): [client 207.154.221.254:51392] AH01102: error reading status line from remote server 127.0.0.1:8080, referer: https://spdf.mydomain.com/pdf-to-img
[Thu Dec 28 17:20:37.442388 2023] [proxy:error] [pid 2017226] [client 207.154.221.254:51392] AH00898: Error reading from remote server returned by /api/v1/convert/pdf/img, referer: https://spdf.mydomain.com/pdf-to-img
```

**Comment by eXqusic92** [comment]
And here is my apache conf:
```
<VirtualHost *:80>

    ServerName spdf.mydomain.com
    ErrorLog ${APACHE_LOG_DIR}/spdf.error.log
    CustomLog ${APACHE_LOG_DIR}/spdf.access.log combined
    ProxyPass / http://127.0.0.1:8080/
    ProxyPassReverse / http://127.0.0.1:8080/
    ProxyRequests Off

RewriteEngine on
RewriteCond %{SERVER_NAME} =spdf.mydomain.com
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>
```

**Comment by Frooodle** [comment]
Can you try the config from the first two answers here

https://stackoverflow.com/questions/169453/bad-gateway-502-error-with-apache-mod-proxy-and-tomcat
