### ISSUE TITLE
Size of the image

### ISSUE THREAD

**Issue by KBDCALLS** [Stirling-Tools/Stirling-PDF#622]
According to the documentation, the Docker image should have approx. 700 MB. However, 1.8 GB ends up on the hard drive, almost three times as much.  How does this discrepancy come about?  It seems to be the case that a current Debian Sid comes with all the necessary software, or is there something missing?

**Comment by Frooodle** [comment]
I believe this is the compressed vs uncompressed amount.
The size stated in the docs is not manually inputted but instead direct from docker API. They must use the compressed size
