### ISSUE TITLE
Investigate PDFbox not handling google docs (text and placements are mirrored)

### ISSUE THREAD

**Issue by Frooodle** [Stirling-Tools/Stirling-PDF#628]

**Comment by mannam11** [comment]
@Frooodle can I get some more description of this issue or screenshot would be very helpful

**Comment by Frooodle** [comment]
For
[google docs FIle.pdf](https://github.com/Stirling-Tools/Stirling-PDF/files/13804875/google.docs.FIle.pdf)

when watermarked it turns to 
[google docs FIle_watermarked.pdf](https://github.com/Stirling-Tools/Stirling-PDF/files/13804876/google.docs.FIle_watermarked.pdf)

Where text is mirrored and incorrect. I can only repeat this for documents with author as google docs
![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/77850077/ba198600-a6eb-47b8-94fc-b458e378ec19)


The same incorrect sizing and positioning happens for others like split-pdf-by-sections

**Comment by Frooodle** [comment]
I believe the Y axis is scaled into the negative for Google docs

**Comment by Frooodle** [comment]
Fix found via 
https://stackoverflow.com/questions/46924286/text-is-reverse-in-generated-pdf

PDF matrix was different
