### ISSUE TITLE
Using "Horizontal Divisions" in "Split PDF into Sections" generates only last row

### ISSUE THREAD

**Issue by chwid** [Stirling-Tools/Stirling-PDF#652]
If you use the "Split PDF into Sections" Tool by "Horizontal Divisions" you only get the last row.
The output of the other rows are only blank PDFs.

**Comment by Frooodle** [comment]
I believe this is caused by [Google ](https://github.com/Stirling-Tools/Stirling-PDF/issues/628)

**Comment by chwid** [comment]
The PDF was created by exporting as a PDF from MS Word

**Comment by chwid** [comment]
Another one was created by prawn. Same issue.
