### ISSUE TITLE
Sign error

### ISSUE THREAD

**Issue by rizlas** [Stirling-Tools/Stirling-PDF#654]
Hi,
trying signing feature with a random pdf I encountered this error in web console. This happens after clicking "Download PDF", this error pops up and sign disappear.

Test with:
 - Firefox and chrome
 - Any type of sign (image, free draw, text)

If you want I can provide the PDF used.

Note: it is working with another (smaller) pdf.

```
Uncaught (in promise) Error: Expected instance of e, but got instance of undefined
    e https://whateverdomain.tld/js/thirdParty/pdf-lib.min.js:15
    lookup https://whateverdomain.tld/js/thirdParty/pdf-lib.min.js:15
    lookup https://whateverdomain.tld/js/thirdParty/pdf-lib.min.js:15
    Pages https://whateverdomain.tld/js/thirdParty/pdf-lib.min.js:15
    computePages https://whateverdomain.tld/js/thirdParty/pdf-lib.min.js:15
    access https://whateverdomain.tld/js/thirdParty/pdf-lib.min.js:15
    getPages https://whateverdomain.tld/js/thirdParty/pdf-lib.min.js:15
    getPage https://whateverdomain.tld/js/thirdParty/pdf-lib.min.js:15
    getOverlayedPdfDocument https://whateverdomain.tld/js/draggable-utils.js:231
    async* https://whateverdomain.tld/sign:1207
    EventListener.handleEvent* https://whateverdomain.tld/sign:1206
pdf-lib.min.js:15:187156
    <anonima> https://whateverdomain.tld/sign:1214
    AsyncFunctionThrow self-hosted:856
    (Asinc.: async)
    <anonima> https://whateverdomain.tld/sign:1206

```

**Comment by Frooodle** [comment]
I Cant reproduce this using PDFs on my side 
Are you just signing the drawing sign feature or text or image?
And can you test same on 
https://pdf.adminforge.de/sign

**Comment by Frooodle** [comment]
if you get same results can you please send PDF it would be very helpful!

**Comment by rizlas** [comment]
Same result
Running: 0.18.1

Here is the pdf
[AGRICOLUS_Brochure.pdf](https://github.com/Stirling-Tools/Stirling-PDF/files/13833444/AGRICOLUS_Brochure.pdf)

**Comment by dogthor1st** [comment]
It works if you first repair the PDF using the repair tool: https://pdf.adminforge.de/repair

**Comment by rizlas** [comment]
Confirm. Thank you

**Comment by Splitpeach** [comment]
I too had this issue and it also worked for me repairing the pdf first. But why is that necessary? Why was it "broken" in the first place and why can't Stirling automatically resolve this automatically when uploaded / downloaded?
