### ISSUE TITLE
Issue with merge-pdfs while using sort by name and date

### ISSUE THREAD

**Issue by mannam11** [Stirling-Tools/Stirling-PDF#660]
Whenever I add the files, if I click on sort by name or date it is duplicating the file instead of sorting.

https://github.com/Stirling-Tools/Stirling-PDF/assets/101550345/4e9d8ae8-4f1c-4ccc-8e9e-6a5073c1de08

**Comment by mannam11** [comment]
@Frooodle here what exactly is the intension behind sort by date functionality.

**Comment by Frooodle** [comment]
> @Frooodle here what exactly is the intension behind sort by date functionality. 

That it would order the existing selected files by their date
