### ISSUE TITLE
[Feature request] Verify PDF certificate signature

### ISSUE THREAD

**Issue by maxi322** [Stirling-Tools/Stirling-PDF#667]
The tool lets you create signatures with certificates but there is currently no way to verify them.

An elegant solution would be to include such a functionality within the reader.

**Comment by sbplat** [comment]
If you're referring to checking if the certificate is trusted or not, then it wouldn't be possible since some certificates are self signed. Everything else should definitely be achievable though.

**Comment by maxi322** [comment]
True, but an option would be to include an optional custom trust store file like a NSS certificate database.
When this is not included it could use the mozilla one for example and only verify official certificates.

**Comment by lucifer-woo** [comment]
This seems similar to https://github.com/JakubMelka/PDF4QT/issues/161

Maybe OCSP based revocation checking instead of trusting would be a better option.

**Comment by lucifer-woo** [comment]
I found this tool called [mupdf](https://mupdf.com) and it has the [abilites to do so.](https://mupdf.readthedocs.io/en/latest/mutool-run-js-api.html#signature-methods)
