### ISSUE TITLE
Github Package no longer available since switched to org

### ISSUE THREAD

**Issue by JigSawFr** [Stirling-Tools/Stirling-PDF#669]
Hi there,
It seems that Github Package is no more available since your switch to a Github org.
https://github.com/orgs/Stirling-Tools/packages?repo_name=Stirling-PDF
Pulled docker tag from here but no longer available.
Permissions problems?
Thank you

**Comment by Frooodle** [comment]
Thanks will investigate

**Comment by Frooodle** [comment]
Seems it is suddenly publishing it as a internal image not external
Will try resolve

**Comment by Frooodle** [comment]
Resolved!
