### ISSUE TITLE
[Bug]Merge multiple PDFs

### ISSUE THREAD

**Issue by Duka10** [Stirling-Tools/Stirling-PDF#671]
This bug is related with merge muliptle PDFs.
Its only present with drag and drop, not when using Choose file button.

![chrome_h3yCqcYJKX](https://github.com/Stirling-Tools/Stirling-PDF/assets/93546291/806a9332-0a23-46a0-a676-684a3d456987)

![chrome_WplP244JXq](https://github.com/Stirling-Tools/Stirling-PDF/assets/93546291/ffddc953-c029-4489-9ff1-1ac65b872765)

This is only related with preview, merge is done correctly without duplicate anything.

Im using version 0.19, hosted on docker.

**Comment by sbplat** [comment]
Related to #660
