### ISSUE TITLE
Port based reverse Proxy / Base Domain Config

### ISSUE THREAD

**Issue by JanThiel** [Stirling-Tools/Stirling-PDF#674]
Hey there,

we try to run Stirling as Docker behind a port based reverse proxy.
Like `https://my.domain.com:28080`. The app itself runs on `http://localhost:8080`.

With login enabled this does not seem to work as calling the app always redirects to `https://my.domain.com/login`. The expected behaviour should be redirecting to `https://my.domain.com:28080/login`.
Is there any way I missed to configure something like a `SYSTEM_ROOTURI`? The only thing that is close but not just it is the `SYSTEM_ROOTURIPATH` ENV var.

Appreciate any help :-)

Thanks and best regards,

Jan

**Comment by chenjuefei** [comment]
Modify Nginx reverse proxy configuration:

location / {
    proxy_pass http://localhost:8080;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host:28080; #Here's the key point: configure it this way to avoid losing the port.
}

**Comment by JanThiel** [comment]
Hey @chenjuefei,

thank you very much for your feedback and proposed solution.

We run our local Docker containers on a Synology NAS with Portainer. Customizability of the actual web server and reverse proxy configs is limited in this setup. I do not even know if Synology run nginx or Apache under the hood.

I added the Host header anyway to the response header config - not knowing what they make of it - and it did not change the behavior of the app. It still forwards to the login page without the port. Noteworthy: It forwards without any host. Not even the one it uses locally.

Using `http://<IP>:8080` works fine and as expected, btw. Port remains set even with the redirects.

I opened this ticket as this is one of the first apps we came along (Docker or native web server) that does not offer an ENV var / config to solve this kind of issue where the public host is different from the internal host.

**Comment by Sschhsd** [comment]
Same here 👍

**Comment by PrzemekSkw** [comment]
> 
> [image](https://github.com/Stirling-Tools/Stirling-PDF/assets/53404198/41b15452-0390-4f7e-9f9b-0bf55b8b00a3)

Hi, I have the same with Nginx Proxy Manager and set Stirling as subfolder.
Regards.

**Comment by mcgradymvp** [comment]
> ```
> location /pdf {
>     proxy_pass http://***.***.*.***:8080;
>     proxy_set_header X-Real-IP $remote_addr;
>     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>     proxy_set_header Host $host; #Here's the key point: configure it this way to avoid losing the port.
> }
> ```
> 
> Hello, follow your example of a subfolder reverse proxy and I have the page with this look, can you recommend any adjustments to make this PDF editor work? Thank you! I hid my local IP *
> 
> [image](https://github.com/Stirling-Tools/Stirling-PDF/assets/53404198/41b15452-0390-4f7e-9f9b-0bf55b8b00a3)

My experience is you need an additional `/` behind `/pdf`
```
location /pdf/ {
# YOUR OTHER CONFIGS
}
```

**Comment by indigodelta** [comment]
Me too.  Using /pdf or /pdf/ is the same behaviour.  Other apps (e.g. radarr) seem to have a URL base path defined in their configs or use 100% relative references.

**Comment by nunuxx** [comment]
having the same issue here on a synology nas! @JanThiel @caio1007 @indigodelta  not sure if you were able to find a solution guys?

**Comment by JanThiel** [comment]
@nunuxx Setup Stirling on a custom hostname on port 80 or 443 or without login does "work".

**Comment by nunuxx** [comment]
ohh how to deploy it "without login" sir? do i just lead the username and
password blank in the deployment script?

**Comment by JanThiel** [comment]
@nunuxx It's all in the docs:

https://stirlingtools.com/docs/Advanced%20Configuration/How%20to%20add%20configurations/

SECURITY_ENABLELOGIN

**Comment by nunuxx** [comment]
thank you so much @JanThiel i confirm that setting SECURITY_ENABLELOGIN to FALSE then makes the custom hostname over port 443 work on a synology nas!
