### ISSUE TITLE
[Feature request] Add the full version as an executable file for windows

### ISSUE THREAD

**Issue by ProvaTeams** [Stirling-Tools/Stirling-PDF#677]
At the moment the only 2 .exe file provided in the release section are the Ultra-Lite version, which are missing useful features like at least PDF to Office formats.
Would it be possible to have a full version (or at least the Lite version) as an .exe file?

**Comment by Frooodle** [comment]
Sadly not, the other versions require external dependencies like python and libre office
Although possible to install and setup it requires more setup at which point most would just run in docker or with from jar
