### ISSUE TITLE
Pdf Multi Tool

### ISSUE THREAD

**Issue by smstacy** [Stirling-Tools/Stirling-PDF#680]
I can seem to be able to download PDF's from the pdf multi tool. I've tried docker version and windows version and  I can't seem to download the files after manipulate them.

2PdfContainer.js:213  Uncaught (in promise) TypeError: this.pagesContainer.childNodes[i].querySelector is not a function
    at PdfContainer.exportPdf (PdfContainer.js:213:59)

![Screenshot 2024-01-09 143827](https://github.com/Stirling-Tools/Stirling-PDF/assets/44792991/f9e972a1-f497-4434-8db2-38f41d7319ee)

**Comment by jojugaad** [comment]
same here, no matter which file.

**Comment by Frooodle** [comment]
I have a solution and should be merged in few hours

**Comment by Frooodle** [comment]
Okay release is being generated now

**Comment by Frooodle** [comment]
Please try now and let me know!

**Comment by PreviST** [comment]
Hello, that solves the problem for me thanks

**Comment by jojugaad** [comment]
for me, as well! Thank you for the quick fixing. Much appreciated!

**Comment by smstacy** [comment]
Works great.  Ditto!

**Comment by trnghiale** [comment]
I tried to docker version but it not work, the windows version work fine though. Any thought?
