### ISSUE TITLE
NginxProxyManager and S-PDF Login authentication

### ISSUE THREAD

**Issue by Cyber-Ard** [Stirling-Tools/Stirling-PDF#689]
Stirling-PDF is working 100% fine behind NginxProxyManager without login authentication. As soon as I add login auth and I log in correctly, I get redirected to NPM.

My Docker Compose file looks like this:

>  stirling-pdf:
>     image: frooodle/s-pdf:latest
>     container_name: spdf
>     deploy:
>       resources:
>         limits:
>           memory: 4G
>     ports:
>       - '8080:8080'
>     volumes:
>       - ./spdf:/configs
>       - ./spdf/customFiles:/customFiles/
>     environment:
>       APP_LOCALE: en_GB
>       UI_APPNAME: Stirling-PDF
>       UI_APPNAMENAVBAR: Stirling-PDF
>       SYSTEM_MAXFILESIZE: "100"
>       SYSTEM_ROOTURIPATH: /spdf
>       APP_ROOT_PATH: /spdf
>       DOCKER_ENABLE_SECURITY: true
>       SECURITY_ENABLELOGIN: true
>     restart: always

In NPM I have the following set

> Location: /npm/
> Forward IP: localhost/
> Forward Port: 81
>
> Location: /api/
> Forward IP: localhost/api/
> Forward Port: 81
>
> Location: /spdf/
> Forward IP: ip/spdf/
> Forward Port: 8080
> 
> Location: /spdf/api/
> Forward IP: ip/spdf/api/
> Forward Port: 8080

The /npm/ and /api/ are required for me to access NPM behind it's own reverse proxy and to enable authentication. However it listens on a different port so I wouldn't think it would intefere with /spdf/api on 8080. (I'm not even sure if /spdf/api/ is relevant or necessary, I'm making assumptions based on the logs below)

My nginx access logs show the following:

> [10/Jan/2024:16:12:32 +0200] - 302 302 - POST https my.domain.com "/spdf/login" [Client my.ip.address] [Length 0] [Gzip -] [Sent-to localhost] "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0" "https://my.domain.com/spdf/login"
> [10/Jan/2024:16:12:32 +0200] - 302 302 - GET https my.domain.com "/spdf/" [Client my.ip.address] [Length 0] [Gzip -] [Sent-to localhost] "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0" "-"
> [10/Jan/2024:16:12:32 +0200] - 200 200 - GET https my.domain.com "/change-creds" [Client my.ip.address] [Length 740] [Gzip -] [Sent-to localhost] "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0" "-"
> [10/Jan/2024:16:12:32 +0200] - 200 200 - GET https my.domain.com "/css/main.css?v=2.10.4" [Client my.ip.address] [Length 305815] [Gzip -] [Sent-to localhost] "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0" "https://my.domain.com/change-creds"
> [10/Jan/2024:16:12:32 +0200] - 200 200 - GET https my.domain.com "/js/main.bundle.js?v=2.10.4" [Client my.ip.address] [Length 619489] [Gzip -] [Sent-to localhost] "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0" "https://my.domain.com/change-creds"
> [10/Jan/2024:16:12:32 +0200] - 200 200 - GET https my.domain.com "/images/favicons/apple-touch-icon.png" [Client my.ip.address] [Length 16709] [Gzip -] [Sent-to localhost] "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0" "https://my.domain.com/change-creds"
> [10/Jan/2024:16:12:32 +0200] - 200 200 - GET https my.domain.com "/assets/source-sans-pro-v14-latin-ext_latin-regular.woff2" [Client my.ip.address] [Length 25656] [Gzip -] [Sent-to localhost] "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0" "https://my.domain.com/css/main.css?v=2.10.4"
> [10/Jan/2024:16:12:32 +0200] - 200 200 - GET https my.domain.com "/api/" [Client my.ip.address] [Length 61] [Gzip -] [Sent-to localhost] "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0" "https://my.domain.com/change-creds"
> [10/Jan/2024:16:12:32 +0200] - 401 401 - GET https my.domain.com "/api/tokens" [Client my.ip.address] [Length 46] [Gzip -] [Sent-to localhost] "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0" "https://my.domain.com/change-creds"
> [10/Jan/2024:16:12:32 +0200] - 200 200 - GET https my.domain.com "/login" [Client my.ip.address] [Length 765] [Gzip -] [Sent-to localhost] "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0" "https://my.domain.com/change-creds"
> [10/Jan/2024:16:12:33 +0200] - 200 200 - GET https my.domain.com "/js/login.bundle.js?v=2.10.4" [Client my.ip.address] [Length 214821] [Gzip -] [Sent-to localhost] "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0" "https://my.domain.com/login"
> [10/Jan/2024:16:12:33 +0200] - 200 200 - GET https my.domain.com "/images/logo-text-vertical-grey.png" [Client my.ip.address] [Length 14281] [Gzip -] [Sent-to localhost] "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0" "https://my.domain.com/login"
> [10/Jan/2024:16:12:33 +0200] - 200 200 - GET https my.domain.com "/assets/source-sans-pro-v14-latin-ext_latin-700.woff2" [Client my.ip.address] [Length 25348] [Gzip -] [Sent-to localhost] "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0" "https://my.domain.com/css/main.css?v=2.10.4"
> [10/Jan/2024:16:12:33 +0200] - 200 200 - GET https my.domain.com "/images/favicons/favicon.ico" [Client my.ip.address] [Length 15086] [Gzip -] [Sent-to localhost] "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0" "https://my.domain.com/login"
> [10/Jan/2024:16:12:41 +0200] - 200 200 - GET https my.domain.com "/api/" [Client my.ip.address] [Length 61] [Gzip -] [Sent-to localhost] "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0" "https://my.domain.com/nginx/proxy"
> [10/Jan/2024:16:12:41 +0200] - 200 200 - GET https my.domain.com "/api/users/me?expand=permissions" [Client my.ip.address] [Length 519] [Gzip -] [Sent-to localhost] "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0" "https://my.domain.com/nginx/proxy"

So to my untrained eye it looks like when I login to https://my.domain.com/spdf/login it goes to https://my.domain.com/change-creds instead of https://my.domain.com/spdf/change-creds etc

**Comment by sbplat** [comment]
#457 may be of interest.

**Comment by Cyber-Ard** [comment]
Thanks @sbplat. I have looked at that issue already but SPDF behind NPM actually works 100% for me, haven't had any issues until I decided to enable authentication. My issue seems similar to that mentioned by Porjo in #14 where it seems to be ignoring the SYSTEM_ROOTURIPATH but only when using authentication.

PS: I made a booboo and opened another issue when trying to reference Porjo above and I have no idea how to delete it. Sorry for messing up the thread,

**Comment by Sschhsd** [comment]
Hi guys,

i have the same issue. The port is lost in the authentication process: 
1. when i open stirling.example.com:8443, i get redirected to stirling.example.com/login without the necessary port
2. after the login, i get redirected again to stirling.example.com without the necessary port

Same for the logout.
