### ISSUE TITLE
Automatic language detection

### ISSUE THREAD

**Issue by 463** [Stirling-Tools/Stirling-PDF#691]
It would be fine to implement an [automatic language detection](https://codewatchers.com/en/blog/how-to-detect-the-browser-language-automatically) depending on the browser language. Otherwise a referencing link (or bookmark) must be made language depended with e.&nbsp;g. a "?lang=en_US" extension in the URL to adjust the language directly by selection. Especially if the number of languages will become longer, the initial language change becomes painful.

**Comment by sbplat** [comment]
If anyone wants to work on this, you can use [navigator.languages](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/languages) to get a list of the user's preferred languages and take the first valid one (that we have as a translation). To get the list of available languages that we have as a translation, you can do a query selector (see `src/main/resources/static/js/languageSelection.js`). Make sure that
1. The language exists.
2. There's a fallback language (en-GB) if none of them are valid.

Also, don't forget to change all occurrences of the current default language implementation (languageSelection.js, login.html, etc.).

**Comment by sbplat** [comment]
Added in #748
