### ISSUE TITLE
Enlarging max-http-header-size

### ISSUE THREAD

**Issue by helgisid** [Stirling-Tools/Stirling-PDF#695]
Is there any way to set custom max-http-header-size value? Maybe I can set it using setting.yml somehow? 

![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/153656596/304e8bba-a1d9-4f70-b2a9-bcbd982c2ae9)

**Comment by Frooodle** [comment]
Out of curiosity what size are you loading?

**Comment by helgisid** [comment]
> Out of curiosity what size are you loading?

Keycloak returns cookie up to 6 mb, I can't make it smaller

**Comment by Frooodle** [comment]
yeah just add this in settings.yml
```yaml
server:
  max-http-header-size: 10MB 
  ```

**Comment by helgisid** [comment]
> yeah just add this in settings.yml
> 
> ```yaml
> server:
>   max-http-header-size: 10MB 
> ```

I can make another .yml file with these lines and it will be merged with the main one, right?

**Comment by Frooodle** [comment]
No please add to same configs/settings.yml

**Comment by helgisid** [comment]
> ```yaml
> max-http-header-size: 10MB 
> ```

I work in k8s and get Read-only file system exception, how can I overcome this?

> volumeMounts:
>         - name: settings
>            mountPath: /configs/settings.yml
>            subPath: settings.yml

**Comment by helgisid** [comment]
still get "Request header is too large" error...
any other thoughts about what could be wrong?

**Comment by Frooodle** [comment]
After restart of app?

**Comment by helgisid** [comment]
> After restart of app?

yes, after redeploying the chart I use the app in

**Comment by helgisid** [comment]
This code works properly: 
```
server:
    max-http-request-header-size: 12KB
```

**Comment by Frooodle** [comment]
> This code works properly: 
> ```
> server:
>     max-http-request-header-size: 12KB
> ```

Interesting why does that work if you said header can be 6mb?

**Comment by helgisid** [comment]
> > This code works properly:
> > ```
> > server:
> >     max-http-request-header-size: 12KB
> > ```
> 
> Interesting why does that work if you said header can be 6mb?

the value is not the case, but the syntax
also cookies are 6KB, not MB, my fault hahah
