### ISSUE TITLE
[Feature request] Insert blank pages option

### ISSUE THREAD

**Issue by H-B-Schmidt** [Stirling-Tools/Stirling-PDF#700]
An option to add one or multiple blank pages at any location of a document will be appreciated.

**Comment by sbplat** [comment]
What would be the size of the blank page if each page had a different size?

**Comment by H-B-Schmidt** [comment]
> What would be the size of the blank page if each page had a different size?

The size of the previous page and if none the next page?

**Comment by ZeGuigui** [comment]
Or you could have a list of predefined page sizes (A3, A4, letter, legal...). But picking the size of the previous/next page would be perfect for our use case

**Comment by Frooodle** [comment]
Blank page addition is supported in our PDF multi tool!

**Comment by Frooodle** [comment]
page size support has not yet been added

**Comment by ZeGuigui** [comment]
Damned, I tested multi function tool and did not find the blank page option! Will check again :+1:
