### ISSUE TITLE
Missing fileToPDF.fileTypesList in every translation

### ISSUE THREAD

**Issue by ProvaTeams** [Stirling-Tools/Stirling-PDF#710]
The placeholder for _fileToPDF.fileTypesList_ is missing in every translation files (included the template _messages_en-GB.properties_ one). This could be placed in each _.properties_ file or it could be placed directly in _file-to-pdf.html_.
There is also a messages.properties file which, however, never seems to be called in which the only reference is just _fileToPDF.fileTypesList_

**Comment by Frooodle** [comment]
Seems the defaulting functionality must have changed, I will add this direct to html since it doesn't need translation, thanks for pointing this out
