### ISSUE TITLE
Missing translation in "BookToPDF" and "PDFToBook"

### ISSUE THREAD

**Issue by riwich** [Stirling-Tools/Stirling-PDF#712]
If I set other than the defaultLocale, for example "**de-DE**", the menu entries for "**BookToPDF**" and "**PDFToBook**" are not translated. The missing translation entry is displayed. This can be seen in the screenshots.
![spdf1](https://github.com/Stirling-Tools/Stirling-PDF/assets/57076243/79119d81-1d19-4103-8d39-c48fb6891c98)
![spdf2](https://github.com/Stirling-Tools/Stirling-PDF/assets/57076243/491bf0c7-a171-459c-912c-45bbd3dd2943)

**Comment by Frooodle** [comment]
This is because that feature has not been translated yet 
All translations are sourced from the community

**Comment by Frooodle** [comment]
However normally I add a default English title but I must have forgotten
Will address this

**Comment by riwich** [comment]
Thank you very much Anthony, 
Fantastic service!
