### ISSUE TITLE
rmd file support

### ISSUE THREAD

**Issue by NeilJared** [Stirling-Tools/Stirling-PDF#720]
Would love to have R Studio markdown format support, not only markdown format. (we have rm file support, just add rmd too). 

https://rmarkdown.rstudio.com/authoring_quick_tour.html

**Comment by sbplat** [comment]
What would be the use case for this? AFAIK, RStudio can convert R Markdown to PDF.

**Comment by sbplat** [comment]
Not sure if there are any other ways to accomplish this, but it seems like the only way to convert this is going from RMD->MD->HTML->PDF. But the RMD->MD steps would require `Rscript` and that requires R/RStudio. I guess we could have this in the full version, but I have no idea what the size of the dependencies for this are.

**Comment by Frooodle** [comment]
Closing this feature as not planned due to RStudio requirement
