### ISSUE TITLE
StirlingPDF Produces broken PDFs

### ISSUE THREAD

**Issue by TheOneValen** [Stirling-Tools/Stirling-PDF#729]
Hi!

I use the StirlingPDF api for my scanner workflow. I use different endpoints in my flow (tiff2pdf, ocr, merge, remove blanks... etc.).

Sometimes StirlingPDF produces output that crashes (500 error) when used as input in another step.

The "broken" PDF is also able to break other applications, mostly with OOM errors.

This affects the newest version (0.20.0) but also earlier versions are affected. This affects different steps. For reproducing I attached [BROKEN.pdf](https://github.com/Stirling-Tools/Stirling-PDF/files/14008798/BROKEN.pdf)

You can reproduce it when using this PDF in the webinterface, too:

Use "Remove Blank Pages". Set Threshold to 15 and White Percent to 95. This crashes my StirlingPDF 0.20.0 every time.

**Comment by sbplat** [comment]
Just to make sure, did you install all the necessary dependencies?

**Comment by sbplat** [comment]
Thanks for explaining how to reproduce it!
