### ISSUE TITLE
detect-blank-pages.py crashes with white values below 99.8%

### ISSUE THREAD

**Issue by zell-mbc** [Stirling-Tools/Stirling-PDF#735]
Hi there, thanks for this great tool. I am running into a few issues however.
Since I started using it I experienced frequent crashes with some of the options

Today's example is the RemoveBlankPages option which launches detect-blank-pages.py by the look of it.
I upload my pdf with default values and thinks will work, I get a new pdf but the blank pages are still in there. So I change the white percentage to 90% which will make the script crash with `java.io.IOException: Command process failed with exit code 1`
Upon testing I notice that the only two values which will work are 99.9 and 99.8 
every value lower than 99.8% will make the process crash.

I then tried the option which allows me to specify the pages to remove which worked fine.
I will report on the other crashes as I run into them.

My environment is Docker-Compose on Debian in case it matters. Happy to provide whatever additional info might be necessary. 

Thanks

**Comment by sbplat** [comment]
#730 fixed this bug (hasn't been released yet though). If you need it urgently, I suggest building and running the master branch.

**Comment by zell-mbc** [comment]
Cool! Thanks for the heads up
