### ISSUE TITLE
Selected files using drag & drop cannot be removed from merge PDF tool

### ISSUE THREAD

**Issue by michelheusschen** [Stirling-Tools/Stirling-PDF#738]
To reproduce:
1. Go to `/merge-pdfs`
2. Drag & drop a file
3. Remove the file using the red 'x' button
4. Drag & drop a file with a different filename

Both files will be selected including the file that was removed

**Comment by sbplat** [comment]
Which version are you on?

**Comment by michelheusschen** [comment]
> Which version are you on?

Tested on version 0.20.0 and using the main branch, both have the same behavior

**Comment by michelheusschen** [comment]
This issue was not fixed with my PR, still able to reproduce on version 0.20.1

**Comment by Frooodle** [comment]
Issue still happens in latest 0.23.1

**Comment by t71rs** [comment]
I would be happy to work on this.
