### ISSUE TITLE
[Feature Request] Unlock PDF's

### ISSUE THREAD

**Issue by aindriu80** [Stirling-Tools/Stirling-PDF#739]
Hi,

I had a PDF file (which did not have a password) that I was unable to copy text from- when I tried to 'Sanitize' the PDF I got an error

`contains an encryption dictionary, please remove it with setAllSecurityToBeRemoved() or set a protection policy with protect()`

The solution was to go to SmallPDF online and just export the uploaded PDF document. I didn't have to select anything - just tried an export and I could copy text from it.

The request is for Stirling-PDF to improve the Sanitize option to unlock PDF and leave it in a natural state.

**Comment by Frooodle** [comment]
Another solution is to go to decrypt/remove password and just hit enter without password provided

**Comment by aindriu80** [comment]
My issue is not password-related.  I could not copy the text from the PDF - so I brought it to Stirling PDF and tried 'Sanitize' however I came across an error outlined above.  Please see message above.

**Comment by Frooodle** [comment]
I agree its not password related
the remove pasword is also called "decrypt"
as it removes decryption 
Your issue is with the PDF being encrypted
It should be resolved by decypting it by going to decrypt/remove password and just hit enter without password provided

**Comment by Frooodle** [comment]
Please check if the solution works

**Comment by undaunt** [comment]
This seems to have worked for me, but the file is now 2MB smaller. Does this action modify the PDF in any way besides running decrypt? IE: between PDF format types, etc.?

**Comment by zophyreus** [comment]
Hi all,
I had a similar case, PDF with copy/paste restriction.
Feature "Remove password (Decrypt)" worked perfectly.
In my case the pdf size went from 942 KB to 946 KB
Greetings, zophyreus

**Comment by Frooodle** [comment]
Closed as supported
