### ISSUE TITLE
Auto Split not working

### ISSUE THREAD

**Issue by FelixBaumgarten** [Stirling-Tools/Stirling-PDF#743]
Hi there,
i am new to Stirling, but really appreciate all that work!
Now I primarily need it to split my daily post mail inbox into separate files.
But when I 'feed' it with a scanned document including the divider pages, it downloads just the exact same file without any splitting. Am I doing something wrong or do I have to install anything else in order to read the QR-Code correctly?

Thank you very much!
Felix

**Comment by Frooodle** [comment]
Can reproduce, must be some update..

**Comment by Frooodle** [comment]
Ahh found reason, QR code is 
old
https://github.com/Frooodle/Stirling-PDF
but we check for new updated one
https://github.com/Stirling-Tools/Stirling-PDF

**Comment by Frooodle** [comment]
Will fix next update
