### ISSUE TITLE
Cannot move small signature

### ISSUE THREAD

**Issue by Royal2000H** [Stirling-Tools/Stirling-PDF#744]
I tried using the Sign tool.
I drew a signature and added it to the page, moved it to the approximate location.
I made the signature smaller to fit in the proper form field.
Now that it is small, I went to more accurately move it into the field. The interface only allows me to resize at this point.

It seems that once the signature drawing is smaller than a certain size, I cannot move it, only resize it. So then I'd need to make it large again, move it, small again. This can be difficult to get right.

I ended up just using the "View PDF" tool and drawing there instead (but that's not ideal either, the thickness can also get so thin there).

**Comment by sbplat** [comment]
I wouldn't necessarily consider this a bug, as it's just not the best interface design. In my opinion, the solution to this would be to allow using arrow keys to move it around.

**Comment by Bostrolicious** [comment]
Arrow key support would be welcome, but not being able to resize and move a signature in the Sign tool with a mouse will be clunky, in my opinion. It would be nice if the resizing borders were either smaller, or perhaps a percentage of the size of the signature. Alternatively, a movement handle above the signature could be added.
