### ISSUE TITLE
view-pdf not working when SYSTEM_ROOTURIPATH configured

### ISSUE THREAD

**Issue by chain710** [Stirling-Tools/Stirling-PDF#746]
frooodle/s-pdf:0.20.0

root cause: pdf.worker.js Not Found when SYSTEM_ROOTURIPATH configured

env
```
      - DOCKER_ENABLE_SECURITY=false
      - SECURITY_ENABLE_LOGIN=false
      - SYSTEM_ROOTURIPATH=/spdf
```

Go to view pdf page: http://host:port/spdf/view-pdf

F12(clear cache also) show `pdfjs/pdf.worker.js 404`

**Comment by Compukid** [comment]
Sorry, if this isn't the correct post to add this. Pleas let me know if I should create a new issue or not. The View PDF isn't working as in the page comes up, but is blank, and when I click on the **`open file`** button nothing happens. I also hit F12 to inspect and found the following. Is this the same issue? or a different one?

![SterlingPDF-viewerror](https://github.com/Stirling-Tools/Stirling-PDF/assets/7535046/5c9675b9-7d04-4c5b-bc41-5cf4ae81f3dd)


Thank you
