### ISSUE TITLE
Documents generated through the stamp tool are named FILENAME_watermarked.pdf

### ISSUE THREAD

**Issue by provelo-ict** [Stirling-Tools/Stirling-PDF#757]
Not a big deal, but maybe they could be named FILENAME_stamped.pdf to differentiate with the watermark tool ?

Also, it would be nice to be able to customize that last part? 
Or maybe to use the locale the user has chosen to adapt it?

**Comment by Frooodle** [comment]
This is a bug and will be fixed next update thanks!

**Comment by Frooodle** [comment]
As for locale.. no plan for now but good idea

**Comment by mannam11** [comment]
@sbplat is it still a issue. Can you assign this to me.

**Comment by sbplat** [comment]
Sure

**Comment by mannam11** [comment]
@sbplat @Frooodle I have created a PR for to fix this. Can you please review it.

**Comment by Frooodle** [comment]
Fixed in upcoming release
