### ISSUE TITLE
remove-pages unhandled exception with space in page list

### ISSUE THREAD

**Issue by lilotter45** [Stirling-Tools/Stirling-PDF#761]
## Description

The page remover fails with an error similar to `Internal Server Error:For input string: " <number>"` when a space is included in the comma-separated list of page numbers to be removed. This appears to affect both single page numbers and page ranges.

### Version

- Version 0.20.1

 ### To reproduce

1. Choose a pdf with a sufficient number of pages, 10 in this example
2. Enter a list of pages to be deleted, include a white-space before one of the numbers, e.g. `1,2-3, 5`
3. Click **Delete Pages**

### Expected behavior

There is a couple of options:

1. I think the better way to handle this is to simply `trim` each item in the comma-separated list before attempting to do the string conversion. Alternatively, all whitespace could be removed from the input string before processing.
2. At the very least the exception should be handled and a message displayed to the user that they must remove white-space from their list. I don't think most non-technical users will correctly guess the issue with the current information provided.

**Comment by mannam11** [comment]
@sbplat Can you assign this to me

**Comment by sbplat** [comment]
Sure, I've assigned it to you.

**Comment by mannam11** [comment]
@sbplat I have created a PR for this issue. can you please review it.
