### ISSUE TITLE
Compress PDF

### ISSUE THREAD

**Issue by Thyrfing89** [Stirling-Tools/Stirling-PDF#762]
I have a document that is 66 pages, i used Microsoft Lens to take picture of every page and made an PDF.

Size for 47 mb and i found out this is to big for sending as an email attatchment.

I tried to use the Auto mode in compress PDF with expected 24 MB size. Result was a PDF with only blank, white pages, size 15 mb.

Not sure if this is an issue or wrong use of this fantastic tool, but wanted to help, and i ended up to use Bluebeam.

**Comment by Frooodle** [comment]
Might be possible impact of v0.20.0 release, will investigate, thanks!

**Comment by Frooodle** [comment]
I cant reproduce this error with my PDFs, are you able to send the PDF that caused this?

**Comment by Thyrfing89** [comment]
Hello again, 

I created a new pdf with 66 Photos.

This i wanted create to a size around 24, it got around 19, But all pdf Pages is just write.

This is in a docker

Link: https://we.tl/t-x04QyRKXGR?utm_campaign=TRN_TDL_05&utm_source=sendgrid&utm_medium=email&trk=TRN_TDL_05

**Comment by Frooodle** [comment]
is this using the auto mode or mannual? in manual i run '4' and get it to like 4-5MB
which gets the white for you?

**Comment by Thyrfing89** [comment]
Automode and wrote 24 but also tried to write 24MB

**Comment by Thyrfing89** [comment]
Manual mode 4 works, then everything looks normal.

**Comment by trebestie** [comment]
I confirm this issue.
Manual mode 4 works, but setting the size of the output file, any numbers or measurement unit do not matter, produces a pdf of the desired size with only white pages.
Version 0.20/0.21 through Docker on Ubuntu

**Comment by Frooodle** [comment]
Is this still issue?

**Comment by trebestie** [comment]
I'm getting weird results.
With some pdf it works well, with some else not
Scrolling the log it looks like  the bug shows up when pdfwrite need more than one attempt to guess the right size.

**Comment by Frooodle** [comment]
I think its been resolved now? At least i cant get it to produce white pages now
