### ISSUE TITLE
Arabic Language Translation

### ISSUE THREAD

**Issue by Hakeem-92** [Stirling-Tools/Stirling-PDF#777]
Greetings, 

Thank you very much for your nice project , I would like to Modify the **Arabic language** translation.

Thanks in advance.
Hakeem

**Comment by Frooodle** [comment]
Then please do

https://github.com/Stirling-Tools/Stirling-PDF/blob/main/src%2Fmain%2Fresources%2Fmessages_ar_AR.properties

**Comment by AbdelatifAitBara** [comment]
Hi @Frooodle.

I started working on it, and I'll do a PR once I'm done.
Sincerely.
