### ISSUE TITLE
Stamp PDF: Distances to the page margin are not identical

### ISSUE THREAD

**Issue by akn01** [Stirling-Tools/Stirling-PDF#784]
In "Stamp PDF" the positioning is not exact. For example, if the stamp is to be in the top right-hand corner (with a narrow margin), the distance between the text and the top and right-hand margins is not identical.
![Unbenannt-1](https://github.com/Stirling-Tools/Stirling-PDF/assets/31011447/6ef8cdbf-b92d-4185-97f9-e99a81bcf96a)

**Comment by sbplat** [comment]
It looks like the positioning is the same ratio as the page, so if one of the dimensions is a lot larger than the other, the difference will be a lot more extreme.
