### ISSUE TITLE
Wrong description for "Split PDF"

### ISSUE THREAD

**Issue by schroeer** [Stirling-Tools/Stirling-PDF#792]
The page Split PDF states 

> The numbers you select are the page number you wish to do a split on
> 
> As such selecting 1,3,7-8 would split a 10 page document into 6 separate PDFS with:
> 
> Document #1: Page 1
> 
> Document #2: Page 2 and 3
> 
> Document #3: Page 4, 5 and 6
> 
> Document #4: Page 7
> 
> Document #5: Page 8
> 
> Document #6: Page 9 and 10

That's not correct. You really get 5 documents containing pages 1, 2-3, 4-7, 8, 9-10.

I think that a better description of the split mechanism is that the document is split after each given page number. In the example case, it is split after pages 1,3,7,8.

[Suitable test document](https://github.com/Stirling-Tools/Stirling-PDF/files/14221358/PDF.10.pages.pdf)

**Comment by jimdouk** [comment]
Hello!
I would like to ask if this issue is still in program or have been solved

**Comment by Frooodle** [comment]
I believe the doc on the page is slightly incorrect still
