### ISSUE TITLE
Update readme screenshots to reflect the new logo change

### ISSUE THREAD

**Issue by sbplat** [Stirling-Tools/Stirling-PDF#805]

**Comment by bagenigilbert** [comment]
Hi there!

I'm interested in taking on this issue and updating the readme screenshots to reflect the new logo change. I'll start working on it right away. Let me know if there are any specific guidelines or requirements I should follow.

Thanks!

**Comment by Frooodle** [comment]
Go ahead!

**Comment by bagenigilbert** [comment]
hello sorry misunderstood the quiz, i'm not proficient in java

**Comment by jimdouk** [comment]
Hello!
I would like to ask if this issue is still in program or have been solved.
