### ISSUE TITLE
French translation needs an update

### ISSUE THREAD

**Issue by Aliarev** [Stirling-Tools/Stirling-PDF#812]
Hi.

The french language has missing translations. I have updated the file and I'd like to make a pull request for it.
I join it here (with txt extension) if someone else wants to do it himself.
[messages_fr_FR.properties.txt](https://github.com/Stirling-Tools/Stirling-PDF/files/14284744/messages_fr_FR.properties.txt)

Thanks.

**Comment by Frooodle** [comment]
Please raise PR! 
And thanks!

**Comment by Aliarev** [comment]
I'm unfamiliar with Github, I have to assigned to this issue so I can push a branch to make my pull request, right ?

**Comment by sbplat** [comment]
You don't need to be assigned to create a fork or submit a PR, but it's recommended to avoid duplicating work (for example, multiple people working on the same issue).

You can create a fork of this repo, modify the fork with your changes, and then create a PR with your changes. There should be a PR tutorial somewhere in the contributing guidelines.
