### ISSUE TITLE
[Feature Request|Bug] Enforcing Username Uniqueness and Character Restrictions for Account Management

### ISSUE THREAD

**Issue by Ludy87** [Stirling-Tools/Stirling-PDF#827]
Usernames should be unique; currently, admin and Admin are two separate accounts.
Usernames should not contain spaces or percentage signs - a user with spaces cannot be deleted, and further special characters need to be checked.

**Comment by Frooodle** [comment]
good call

**Comment by mannam11** [comment]
Hi @Ludy87 , can you please let me know like from where we can create users so that i can investigate further on this.
I am not able to figure out how i can create users or login.

**Comment by Ludy87** [comment]
The `enableLogin`(`SECURITY_ENABLELOGIN`) flag must be set to `true`. You can then log in with the username/password you provided in Docker or with the default credentials. Add users via the gear => Account settings or http://127.0.0.1:8080/addUsers

**Comment by mannam11** [comment]
if you don't mind can you share the path to that particular piece of code for enableLogin(SECURITY_ENABLELOGIN).

**Comment by mannam11** [comment]
@Frooodle can you please assign this to me.

**Comment by mannam11** [comment]
@Ludy87 can we do like username should contain only alphabet characters and numbers and should not contain spaces any where with in the username.

**Comment by Ludy87** [comment]
This is how the issues should be understood.

**Comment by mannam11** [comment]
I am not using the docker version. I am running  it in my local

**Comment by Ludy87** [comment]
Then say that straight away.

Go to `configs` folder and edit the `settings.yml`

under `security` you enter `enableLogin: true`

You can then log in with the standard user and create new users accordingly.

**Comment by mannam11** [comment]
security:
  enableLogin: true # set to 'true' to enable login
  csrfDisabled: true
  loginAttemptCount: 5 # lock user account after 5 tries
  loginResetTimeMinutes : 120 # lock account for 2 hours after x attempts
  
  I have found the file where i need to make changes. Thank you @Ludy87 for the help
