### ISSUE TITLE
Swagger API is not available.

### ISSUE THREAD

**Issue by alkaphreak** [Stirling-Tools/Stirling-PDF#832]
I can't access to Swagger API documentation on the given link : https://app.swaggerhub.com/apis-docs/Stirling-Tools/Stirling-PDF/

There is 404 errors.

**Comment by Frooodle** [comment]
https://app.swaggerhub.com/apis-docs/Frooodle/Stirling-PDF/0.20.0

**Comment by alkaphreak** [comment]
Thanks a lot.
