### ISSUE TITLE
Issue with Remove page modules.

### ISSUE THREAD

**Issue by NinjaAway** [Stirling-Tools/Stirling-PDF#842]
Hello ! 
In the version 0.21.0, the 'Remove' module seems to start counting at page 0.

If you want to delete the second page for example, you need to give it the number 1.

Tried with the rollback of 0.18.1, working fine. Didn't try on other versions.

Is it a normal "feature" ? 

Thank's.

**Comment by Frooodle** [comment]
Not expected
Will debug to fix 
Thanks for raising this
