### ISSUE TITLE
Bug Invalid username or password

### ISSUE THREAD

**Issue by caio1007** [Stirling-Tools/Stirling-PDF#844]
Hi, I installed stirling-pdf via docker, I'm using the latest version on my x86 mini pc with dietpi.
I have a bug that when changing the password or adding a user gives an error at the login, I have already tested without the variables ` - SECURITY_INITIALLOGIN_USERNAME=mylogin
      - SECURITY_INITIALLOGIN_PASSWORD=mypassword` and the same error happens when changing the password at the first login: admin, password: stirling.

`version: '3.3'
services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    ports:
      - '8080:8080'
    volumes:
      - /mnt/myuserdata/Pdf/tessdata:/usr/share/tesseract-ocr/5/tessdata #Required for extra OCR languages
      - /mnt/myuserdata/Pdf:/configs
      - /mnt/myuserdata/Pdf/customFiles:/customFiles
      - /mnt/myuserdata/Pdf/logs:/logs
    environment:
      - DOCKER_ENABLE_SECURITY=true
      - SECURITY_ENABLE_LOGIN=true
      - SYSTEM_GOOGLE_VISIBILITY=false
      - SECURITY_INITIALLOGIN_USERNAME=mylogin
      - SECURITY_INITIALLOGIN_PASSWORD=mypassword`

**Comment by haldi4803** [comment]
same problem here:
02:40:49.951 [http-nio-8080-exec-1] ERROR s.s.S.c.s.CustomAuthenticationFailureHandler - Failed login attempt from IP: 172.23.0.1

**Comment by Frooodle** [comment]
Appreciate the investigation
This would be the dB file inside configs I presume

**Comment by Draky50110** [comment]
Just tried a new install, without env with login/pass, juste enabling.

Launched, logged with admin/stirling and rebooted container and nothing is possible now : no more admin/sterling and new ident/pass is not working.

**Comment by Frooodle** [comment]
So if there are issues relating the dB files in configs directory should fix but I will also investigate what's causing this for a later release

**Comment by thiagodtorres** [comment]
I have same problem.

**Comment by haldi4803** [comment]
Correction: it's not only file system permission related.

Setting security to true and login to true I can enter admin/Stirling. Change the password and name. But then it's broken.

2024-02-24 07:28:34.136418+01:00Navigate to http://localhost:8080
2024-02-24 07:28:48.672935+01:0006:28:48.672 [http-nio-8080-exec-1] INFO  o.a.c.c.C.[Tomcat].[localhost].[/] - Initializing Spring DispatcherServlet 'dispatcherServlet'
2024-02-24 07:28:48.673161+01:0006:28:48.673 [http-nio-8080-exec-1] INFO  o.s.web.servlet.DispatcherServlet - Initializing Servlet 'dispatcherServlet'
2024-02-24 07:28:48.674623+01:0006:28:48.674 [http-nio-8080-exec-1] INFO  o.s.web.servlet.DispatcherServlet - Completed initialization in 1 ms
2024-02-24 07:29:26.621299+01:0006:29:26.621 [http-nio-8080-exec-1] ERROR s.s.S.c.s.CustomAuthenticationFailureHandler - Failed login attempt from IP: 192.168.1.1
2024-02-24 07:29:40.304690+01:0006:29:40.304 [http-nio-8080-exec-1] ERROR s.s.S.c.s.CustomAuthenticationFailureHandler - Failed login attempt from IP: 192.168.1.1

**Comment by Frooodle** [comment]
from what i can see it seems that change user and password onyl changes password for some reason.

And that changing username on its own works fine
but that changing both within same operation is having some issues

**Comment by Frooodle** [comment]
Does everyone confirm the same findings?

**Comment by Frooodle** [comment]
It seems that changing username changes the user session and causes issues, I think i will just avoid this logic of changing both at same time, users will be prompted for password change, username changes can be done separately

**Comment by Frooodle** [comment]
@lawfulsoftware can you open this as a new issue for initial username restrictions and handling
