### ISSUE TITLE
Authorization Error with API Key on Version 0.21.0

### ISSUE THREAD

**Issue by thiagodtorres** [Stirling-Tools/Stirling-PDF#846]
Hello,

I've encountered an authorization issue after updating to version 0.21.0 of your software. Despite using the correct API key, I am receiving a 401 Unauthorized error when attempting to use the `/api/v1/convert/pdf/img` endpoint.

Here is the error message I'm receiving:
{"timestamp":"2024-02-22T16:36:51.417+00:00","status":401,"error":"Unauthorized","message":"Unauthorized","path":"/api/v1/convert/pdf/img"}

**Comment by sbplat** [comment]
Does it work with other endpoints?

**Comment by thiagodtorres** [comment]
Yes.
If downgrade version work fine.

**Comment by Ludy87** [comment]
@thiagodtorres 
Where do you get the API KEY from?

**Comment by Frooodle** [comment]
> @thiagodtorres Where do you get the API KEY from?

account settings under the settings cog top right

**Comment by Ludy87** [comment]
I where the apikey is 😅 but there is also one in the Settings.yaml, hence my question.

**Comment by Frooodle** [comment]
ignore settings.yml thats not a api key

**Comment by thiagodtorres** [comment]
<img width="774" alt="Captura de Tela 2024-02-25 às 17 41 40" src="https://github.com/Stirling-Tools/Stirling-PDF/assets/146589148/ca69c2dd-6256-4440-8938-b156df9f83fa">

If upgrade version, dont work :(

**Comment by Ludy87** [comment]
OK I can reproduce it.
A malfunction in the code triggers an exception (web interface) and the API interface is disrupted in the command line.
I don't know if that's "the problem", but it reacts the same way.

**Comment by arladmin** [comment]
Is there no workaround/fix for this, as of now?

**Comment by Frooodle** [comment]
Sorry forgot to investigate this one
Can look into it tomorrow!

**Comment by arladmin** [comment]
> Sorry forgot to investigate this one
> Can look into it tomorrow! 

@Frooodle Looking forward to a hot-fix for this, because until then, the 'pdf to img' is unusable  🫤

**Comment by Frooodle** [comment]
I cant reproduce this..... @Ludy87 @arladmin  Can you explain what you did to set it up?
![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/77850077/a6ee812e-6724-4a25-9cad-ab662cb1647e)
![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/77850077/bd1a2b7a-7b4e-4c8b-87cb-8f303bb6f399)

I am getting my key authenticated without issue

**Comment by Frooodle** [comment]
Can you confirm you still see this issue on latest release

**Comment by Ludy87** [comment]
> Können Sie bestätigen, dass dieses Problem in der neuesten Version immer noch auftritt?

The problem is still there.
Reproduction:
You have to create an exception on the WebUI, how is up to you, then the query with the API says "Invalid API Key."

**Comment by arladmin** [comment]
@Frooodle 
> Can you confirm you still see this issue on latest release

The latest release is working for me, so far.

**Comment by thiagodtorres** [comment]
The latest release is working for me, so far.
