### ISSUE TITLE
can't pull docker image on mounted filesystems

### ISSUE THREAD

**Issue by hacketaler** [Stirling-Tools/Stirling-PDF#849]
Hello,

please also check:
https://forum.openmediavault.org/index.php?thread/51529-problem-with-docker-client-on-nfs-mounted-filesystem/

I am experiencing persistent issues with Docker on systems where the Docker data directory is located on an NFS-mounted filesystem (netbooted Raspi 4b from a OpenMediaVault NAS)

I'm not able to pull frooodle/s-pdf:latest:
`failed to register layer: lsetxattr security.capability /usr/libexec/gstreamer-1.0/gst-ptp-helper: operation not supported`

I'm able to pull the image on an Raspi with USB-boot (both Rasp OS and Ubuntu)
I'm able to pull other images on the netbooted Raspi

Efforts to resolve this included:

- Migrating NFS Version: Moving from NFSv3 to NFSv4.2 to leverage better support for extended attributes, yet the problem persisted.
- Changing Storage Drivers: changed from vfs to fuse-overlayfs, which did not resolve the issue. (I'm getting errors using overlay2)

Given these challenges with NFS, I moved Docker's storage (data-root) to a CIFS mount as a test. However, I encountered similar symlink-related errors:

`failed to register layer: symlink ../1c2838626712591e06e028c1166d6d6f973f33677e49323cd4b58f314830bb16/diff /z_volumesCIFS/dockertest05/fuse-overlayfs/l/H5MC2XABMHL2F3IDR3PRZZTLOT: operation not supported
`

Any advice how to pull your image would be greatly appreciated. ;)

Thank you for your assistance!

Update:
after hours of tests, this is the only working solution so far: mounting an image-file with xfs-filesystem
(like here: https://www.redhat.com/sysadmin/rootless-podman-nfs)

**Comment by Frooodle** [comment]
as suggest solution is "mounting an image-file with xfs-filesystem"
closing issue unless other can also not solve
