### ISSUE TITLE
offline deployment with login

### ISSUE THREAD

**Issue by github-cli** [Stirling-Tools/Stirling-PDF#862]
is there any way to keep my install offline and still enable authentication? can i put the tar file somewhere?

**Comment by sbplat** [comment]
Could you clarify what you mean by keeping your installation offline? Authentication works with localhost, if that's what you mean.

**Comment by github-cli** [comment]
Yes, my install has no direct connection to the outside world. It is on a network with no default route and only acces to the reverse proxy.
Best practice container security 

if I want authentication, it needs to load a file from the internet which it cannot in my case and then simply doesn’t have authentication

**Comment by Frooodle** [comment]
created a dockerfile-fat which people can use!
You can build the new docker file locally, will also upload to dockerhub for next release
