### ISSUE TITLE
PDF to image problem

### ISSUE THREAD

**Issue by heihei999** [Stirling-Tools/Stirling-PDF#872]
When using PDF to image, it can be used normally for the first time, but if you use it again, it will become a file like the one shown in the figure without file extension, only displaying "download". Adding the extension manually is also not open
![Snipaste_2024-03-06_13-44-22](https://github.com/Stirling-Tools/Stirling-PDF/assets/64182111/456d0a93-5a1a-46c8-a102-38916280de1e)

**Comment by pakchoily** [comment]
yes,v0.23.1(docker) with the same problem.

**Comment by Frooodle** [comment]
if you open the file in a text editor whats inside? it should show a error?

**Comment by pakchoily** [comment]
> if you open the file in a text editor whats inside? it should show a error?

It can be solved by adding a '. zip' suffix to the 'download' file, and the content inside is correct.

**Comment by Frooodle** [comment]
Cant reproduce
