### ISSUE TITLE
new chmod in entrypoint.sh now breaks running as non root

### ISSUE THREAD

**Issue by halkeye** [Stirling-Tools/Stirling-PDF#896]
The new "non root" support actually requires you to run as root, then switch over to non root at runtime, but that means the container is still running as root.

1) Can you update the chmods to not fail to startup if they don't run? just like || true them or something
2) Why is all the tessdata stuff in entrypoint done at startup instead of inside the dockerfile? are people supposed to be mounting tessdata?

**Comment by Frooodle** [comment]
1) sure will set this done

2) ``/usr/share/tessdata`` yes in all docs we reference
``- /location/of/trainingData:/usr/share/tessdata #Required for extra OCR languages`` 
required for adding other language files

**Comment by Frooodle** [comment]
try now

**Comment by halkeye** [comment]
Oh cool, that looks good.

I opted to just skip the init script for my use case
