### ISSUE TITLE
Delete pages

### ISSUE THREAD

**Issue by PreviST** [Stirling-Tools/Stirling-PDF#908]
Hello,
When we use the "PDF Page Remover" and enter "1" in "page to delete" it delete the second page. 
When enter "0" it delete the first page.

is this normal behavior or a bug?

Thanks

**Comment by Frooodle** [comment]
What version are you on

**Comment by PreviST** [comment]
0.21.0

**Comment by PreviST** [comment]
Sorry I will update to latest version and test it
