### ISSUE TITLE
Issue regarding Chinese fonts

### ISSUE THREAD

**Issue by jaychoubaby** [Stirling-Tools/Stirling-PDF#915]
I converted it to PDF using Word, but the font is missing after conversion and the display is not normal.

![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/26641387/329a0990-5f5a-43f8-87ba-30811867c75f)

**Comment by Frooodle** [comment]
Can you give a example PDF file i can test this with to resolve?

**Comment by jaychoubaby** [comment]
[test.docx](https://github.com/Stirling-Tools/Stirling-PDF/files/14609439/test.docx)

This is a Chinese document, converting it to PDF will not display the characters.

> Can you give a example PDF file i can test this with to resolve?

**Comment by Le1a** [comment]
I also encountered the same problem. It seems that the technology used has weak support for Chinese. I hope it can be fixed as soon as possible. Thank you so much.

**Comment by RasaElabram** [comment]
I have same issue with Thai language as well.

**Comment by gepcel** [comment]
I assume you are using docker. Under the directory `/usr/share/fonts/opentype/noto/` there should be some fonts. Copy some of your own fonts (Chinese fonts maybe) into that will work. You might need to delete `noto` and remake the directory first.

**Comment by jaychoubaby** [comment]
> I assume you are using docker. Under the directory `/usr/share/fonts/opentype/noto/` there should be some fonts. Copy some of your own fonts (Chinese fonts maybe) into that will work. As of [issue 974](https://github.com/Stirling-Tools/Stirling-PDF/issues/974) you might need to delete `noto` and remake the directory first.

The method has been tested and proven effective. Thank you very much.

**Comment by Le1a** [comment]
> > I assume you are using docker. Under the directory `/usr/share/fonts/opentype/noto/` there should be some fonts. Copy some of your own fonts (Chinese fonts maybe) into that will work. As of [issue 974](https://github.com/Stirling-Tools/Stirling-PDF/issues/974) you might need to delete `noto` and remake the directory first.
> 
> The method has been tested and proven effective. Thank you very much.

May I ask where you found the Chinese font files in the Word document?

**Comment by Frooodle** [comment]
> > I assume you are using docker. Under the directory `/usr/share/fonts/opentype/noto/` there should be some fonts. Copy some of your own fonts (Chinese fonts maybe) into that will work. As of [issue 974](https://github.com/Stirling-Tools/Stirling-PDF/issues/974) you might need to delete `noto` and remake the directory first.
> 
> The method has been tested and proven effective. Thank you very much.

Can you share some example fonts? Would love to add this directly to stirling pdf to support

**Comment by jaychoubaby** [comment]
> > > I assume you are using docker. Under the directory `/usr/share/fonts/opentype/noto/` there should be some fonts. Copy some of your own fonts (Chinese fonts maybe) into that will work. As of [issue 974](https://github.com/Stirling-Tools/Stirling-PDF/issues/974) you might need to delete `noto` and remake the directory first.
> 
> > 
> 
> > The method has been tested and proven effective. Thank you very much.
> 
> 
> 
> Can you share some example fonts? Would love to add this directly to stirling pdf to support

Of course, I'll pack it for you tomorrow.

**Comment by gepcel** [comment]
> May I ask where you found the Chinese font files in the Word document?

Since it's a word document, most likely created through Windows system. You can just copy those fonts being used from your system(`C:\Windows\Fonts`) into sterling-pdf docker, only for your own use.

> 
> Can you share some example fonts? Would love to add this directly to stirling pdf to support

Maybe to check if [this](https://source.typekit.com/source-han-serif/) or [this](https://packages.debian.org/sid/all/xfonts-wqy) fits.

**Comment by Frooodle** [comment]
Does anyone have a example PDF file i can test with?

**Comment by Frooodle** [comment]
I have released a update as well while i wait for test file
If you can try with that

**Comment by jaychoubaby** [comment]
> > > > 我假设你正在使用 docker。该目录下`/usr/share/fonts/opentype/noto/`应该有一些字体。复制一些你自己的字体（也许是中文字体）进去就可以了。从[问题 974](https://github.com/Stirling-Tools/Stirling-PDF/issues/974)开始，您可能需要`noto`先删除并重新创建目录。
> > 
> > 
> > > 
> > 
> > 
> > > 该方法已经过测试并证明是有效的。非常感谢。
> > 
> > 
> > 你能分享一些示例字体吗？很想将其直接添加到斯特林 pdf 中以支持
> 
> 当然，我明天就给你打包。

https://drive.google.com/file/d/1aicHFA-3l32evIN79nmiadZBQNRdEZJz/view?usp=sharing

**Comment by jaychoubaby** [comment]
> Does anyone have a example PDF file i can test with?

[阿里开发手册 word版阿里开发手册 word版.docx](https://github.com/Stirling-Tools/Stirling-PDF/files/14830980/word.word.docx)

**Comment by Frooodle** [comment]
> > Does anyone have a example PDF file i can test with?
> 
> [阿里开发手册 word版阿里开发手册 word版.docx](https://github.com/Stirling-Tools/Stirling-PDF/files/14830980/word.word.docx)

Seems to work now? :)

**Comment by Frooodle** [comment]
I have added chinese now, but will be adding this via some env parameter in future as i cant install all fonts at start due to size issues

**Comment by gepcel** [comment]
> I have added chinese now, but will be adding this via some env parameter in future as i cant install all fonts at start due to size issues

`adding this via some env parameter` is a good idea.

**Comment by Frooodle** [comment]
https://github.com/Stirling-Tools/Stirling-PDF/blob/main/exampleYmlFiles/docker-compose-latest.yml#L24

Added a LANGS parameter, this will need to be specified going forward

for example
LANGS: "zh_CN,zh_TW"
