### ISSUE TITLE
Huge RAM usage even when idle

### ISSUE THREAD

**Issue by CompositeBlues** [Stirling-Tools/Stirling-PDF#920]
Hello. I've noticed large RAM usage, always hovering about 500mb. Is this normal? Note that this is when the container is idle, with no operations being performed and no one logged in. I have other containers that are somewhat similar to Stirling in terms of processing and operations and they consume about 1/10 this RAM when idle. If this isn't normal I'd be happy to share my compose file.

Thanks

**Comment by sbplat** [comment]
Java is more on the RAM heavy side so it uses up more memory. The 500 MB is probably due to the heap, but you can set a maximum size to limit it.

**Comment by Frooodle** [comment]
I can do some thread limiting and heap and garage collection changes to reduce
I'll have a play around with it later and run it if system is less than X ram size

**Comment by CompositeBlues** [comment]
> I can do some thread limiting and heap and garage collection changes to reduce
> I'll have a play around with it later and run it if system is less than X ram size 

Thanks. I remember reading on Reddit that you bitterly regret using Java as the base - is this why?

**Comment by Frooodle** [comment]
One of the reasons yes
Quite bloated 
Still a good language though 😂

**Comment by damomato** [comment]
Anybthoughts on rewriting it? I just stop and start it when I want to use it because it always seems so bloated on my server

**Comment by Frooodle** [comment]
V2 is planned with rework we have a few branches for that
But V1 will be supported for long time till that works done
Not a easy thing to rewrite it all

**Comment by Frooodle** [comment]
The non login version version uses a lot less ram fyi

**Comment by CompositeBlues** [comment]
> The non login version version uses a lot less ram fyi

Interesting. Like how much less?

I know the obvious answer is 'try it and find out' but I won't be able to for a few days. Thanks

**Comment by damomato** [comment]
> The non login version version uses a lot less ram fyi

That's good to know thanks. And completely understand how difficult it would be rewrite. Unfortunately I don't have the skills to help

**Comment by gaston-arg** [comment]
Also noticing a huge RAM usage here, hosted on a Raspberry Pi 4. 
Same goes for CPU usage I think, with a "php defunct" service running from time to time, which I'm not sure what it means:

%CPU     PID USER     COMMAND
29.3 3145416 pi       [php] <defunct>
10.4 3124620 root     java -Dfile.encoding=UTF-8 -jar /app.jar

But it's mostly Java I think that's taking more resources.
