### ISSUE TITLE
Signing documents doesn't do anything

### ISSUE THREAD

**Issue by Softbox44** [Stirling-Tools/Stirling-PDF#921]
When choosing a document, nothing happens. A document can be selected but after that nothing happens.
![image](https://github.com/Stirling-Tools/Stirling-PDF/assets/163422442/34165f44-3522-44d6-9199-36cd4c97d422)

**Comment by Ludy87** [comment]
How about some more information (log, version, etc.)

**Comment by Frooodle** [comment]
Probably client side so f12 logs!

I have seen this happen with users running misconfigured nginx etc

**Comment by sbplat** [comment]
Is this a one-time issue? Are you able to consistently reproduce this behaviour?

**Comment by Softbox44** [comment]
Ok - the issue happens every single time I try to "sign" a PDF. I now noticed that the upload just takes extremely long. For example a 500kb PDF takes 30secs before it appears in Stirling PDF. Something is not right I think.

**Comment by Frooodle** [comment]
Got any logs to show in the f12 console yet?

**Comment by wolfhauk** [comment]
I have been trying to use the "Sign" feature for the very first time and can confirm that it shows the same behavior - on clicking the "Download PDF" button the signatures (I used a jpg, a bmp and one self drawn signature) disappear and no download starts.
I use the Stirling PDF solution in a docker container on Unraid from the Froodle repository.
What (and how) can I supply what you guys need to have a closer look?

**Comment by Frooodle** [comment]
Is this issue ongoing? closing for now, will reopen if any replies
