### ISSUE TITLE
Encoding bug during markdown to pdf conversion

### ISSUE THREAD

**Issue by NicolasFR** [Stirling-Tools/Stirling-PDF#926]
Hello,
Since version 21.0, I encounter encoding bugs when converting md to pdf.

Here's an example: 
This is a test with accents: é è à ç ù

Result :
[test-1.pdf](https://github.com/Stirling-Tools/Stirling-PDF/files/14627137/test-1.pdf)

**Comment by NicolasFR** [comment]
Hello,

I've looked into the matter a bit, and I think it's weasyprint that doesn't "detect" encoding.
When the `-e utf-8` argument is passed to weasyprint, accented letters (é ù for example) are correctly displayed.
But I don't understand why it worked before.

**Comment by Frooodle** [comment]
So from 20 to 21 we changed to use a different OS in docker
Changing the app version that was installed

**Comment by Frooodle** [comment]
So could be the latest weasyprint has some bug

**Comment by Frooodle** [comment]
Might be worth posting on
https://github.com/Kozea/WeasyPrint/

**Comment by NicolasFR** [comment]
I have created this issue https://github.com/Kozea/WeasyPrint/issues/2113

**Comment by NicolasFR** [comment]
Hi, there,

I noticed that the HTML file provided as input to weasyprint does not contain any meta fields (charset for example) and the default encoding is latin9.  

Would it be possible to force the use of utf-8 by passing the -e utf-8 argument to weasyprint? I can make a pull request

**Comment by Frooodle** [comment]
Happy for you to setup additional arrangements etc for weasy as params etc

**Comment by Frooodle** [comment]
Happy for you to setup additional arrangements etc for weasy as params etc 

Go ahead and raise seems a good change to be utf8
