### ISSUE TITLE
Can't split the pdf files from scanner

### ISSUE THREAD

**Issue by xiaobaiwcc** [Stirling-Tools/Stirling-PDF#928]
Hello,
I use the latest version 0.22.3. When I want to split the pdf which is scaned by scanner, I get the result pdf file whith nothing.

Here's an example:
origin pdf:
[SKM_C360i24031816590.pdf](https://github.com/Stirling-Tools/Stirling-PDF/files/14633566/SKM_C360i24031816590.pdf)

Result :
[SKM_C360i24031816590.zip](https://github.com/Stirling-Tools/Stirling-PDF/files/14633568/SKM_C360i24031816590.zip)

**Comment by Frooodle** [comment]
What inputs?

**Comment by xiaobaiwcc** [comment]
![2024-03-19_13-03-28](https://github.com/Stirling-Tools/Stirling-PDF/assets/33642888/687e9a09-97ad-4411-945c-6b166f471a7e)

**Comment by Frooodle** [comment]
Is this issue still ongoing? closing for now, will reopen if still happening
