### ISSUE TITLE
Menu size issue with some monitor resolutions

### ISSUE THREAD

**Issue by loviuz** [Stirling-Tools/Stirling-PDF#929]
Hi,

with the last update that adds the menu **Pipeline** we have noticed that language menu goes out of screen with screen width 1366 pixel:

![immagine](https://github.com/Stirling-Tools/Stirling-PDF/assets/1647128/368b6b0f-1022-41ca-95e6-177a2e9c52ed)

**Comment by Frooodle** [comment]
Thanks for raising this will try adapt

**Comment by jimdouk** [comment]
Hallo! 
I would like to help in this issue.

**Comment by Frooodle** [comment]
Please do!
