### ISSUE TITLE
Search Results Displayed on Previous Page Instead of Current Page in Edge Browser

### ISSUE THREAD

**Issue by getbot887** [Stirling-Tools/Stirling-PDF#937]
When searching for specific keywords, such as "PDF," the search results are displayed on the previous page instead of the current one. This requires the user to scroll up manually. For instance, searching for "PDF" causes the search interface to default to page 51, while the pertinent "PDF" content is actually on page 50. The browser being used is Edge.

This issue arises if the search results resemble a table format. However, if the search results consist solely of text pages, this problem does not occur.

**Comment by Frooodle** [comment]
Is this issue still ongoing? closing for now, will reopen if still happening
