### ISSUE TITLE
Save all converted files locally

### ISSUE THREAD

**Issue by harleckinz** [Stirling-Tools/Stirling-PDF#940]
Hi!

I would like to save all converted files on the server. So my basic concept behind that whenever I convert any file then I would like to have a copy if I don't save the file or save on an another computer and would like to download again.

There is any solution to solve that?

Have a nice day!

**Comment by Frooodle** [comment]
Not currently
Our initial design was all about 0 logs and files being left over
While we could integrate this with some config flag it's not something currently in spdf
