### ISSUE TITLE
PR #825 breaks view-pdf for non-root hosting

### ISSUE THREAD

**Issue by mdecker** [Stirling-Tools/Stirling-PDF#943]
PR #825 (unintentionally?) changed the path of `viewer.css` to an absolute path. This breaks the view-pdf functionality for setups that don't host in root.
The problematic change is in the `view-pdf.html` template, line 38 (https://github.com/Stirling-Tools/Stirling-PDF/pull/825/commits/898ddae72922fe87e0c678f62f28f315633747cf#diff-27c9b90465cae0be7c6a77866fce4391d846359471aee8dc0f67d7115fc3e5bfR38, https://github.com/Stirling-Tools/Stirling-PDF/blob/main/src/main/resources/templates/view-pdf.html#L38)

**Comment by Frooodle** [comment]
Fixed, release coming
