### ISSUE TITLE
Multiline text stamp ends on error

### ISSUE THREAD

**Issue by finwe** [Stirling-Tools/Stirling-PDF#944]
When trying to call the stamp endpoint with a newline in the stamp text, the API ends on HTTP 500
with error:

    java.lang.IllegalArgumentException: No glyph for U+000A (\n) in font NotoSans-Regular

This is a basic instance run from Docker.

If multiline stamps are not intentionally supported, this should be handled and it would be nice to be able to have them.

**Comment by sbplat** [comment]
We have to handle this like `WatermarkController` by handling `\n` ourselves.
