### ISSUE TITLE
Some functions of subdirectory deployment cannot be used

### ISSUE THREAD

**Issue by likaia** [Stirling-Tools/Stirling-PDF#971]
I want to use the multi-tool function, but when I click the import button, the console reports an error: addPdfs is not defined

My website after deployment：https://www.kaisir.cn/pdf-tool/multi-tool

* view-pdf is also blank when opened （https://www.kaisir.cn/pdf-tool/view-pdf）
* ocr-pdf page display is abnormal

<img width="1910" alt="image" src="https://github.com/Stirling-Tools/Stirling-PDF/assets/35120858/ff1f97d0-33fd-4105-a1fc-a4bc803febc2">

<img width="1915" alt="image" src="https://github.com/Stirling-Tools/Stirling-PDF/assets/35120858/31c169dc-5c5f-4c01-adfd-70e6ca11b5b9">

<img width="1920" alt="image" src="https://github.com/Stirling-Tools/Stirling-PDF/assets/35120858/0ec8ae0f-0d59-46c7-8d2c-1a0f5e63f221">

**Comment by sbplat** [comment]
Is this a clean install or have some things been modified?

**Comment by likaia** [comment]
For a new installation, I just changed the value of SYSTEM_ROOTURIPATH to /pdf-tool and enabled https.

Then, a subdirectory of /pdf-tool was added to nginx and pointed to the intranet machine through a proxy.

**Comment by likaia** [comment]
> Is this a clean install or have some things been modified?

This is my nginx configuration.。
<img width="1378" alt="image" src="https://github.com/Stirling-Tools/Stirling-PDF/assets/35120858/c45ccb8a-0bf8-46f2-b0eb-541803bd673c">

**Comment by sbplat** [comment]
I took a look at your deployment and it seems like the HTML is corrupted/incorrectly parsed. It appears that part of the head got placed in the `LA_COLLECT` script tag, rendering `image-highlighter` undefined and causing that error.

**Comment by likaia** [comment]
> I took a look at your deployment and it seems like the HTML is corrupted/incorrectly parsed. It appears that part of the head got placed in the `LA_COLLECT` script tag, rendering `image-highlighter` undefined and causing that error.

Thank you. It has been solved. It's really this problem.
