### ISSUE TITLE
Feature Request: Static API Key via ENV Vars

### ISSUE THREAD

**Issue by geoffatsource** [Stirling-Tools/Stirling-PDF#973]
Using the DigitalOcean app, I'd like to be able to specify an API key that doesn't change. See the related issue below which was closed 

https://github.com/Stirling-Tools/Stirling-PDF/issues/959

**Comment by matthisholleville** [comment]
Hi @Frooodle ! We are very interested in this enhancement. Do you have any plans for when it will be implemented?

**Comment by Frooodle** [comment]
Will be added in next release today/tomorrow!
