### ISSUE TITLE
Bug - Docker - Fonts not copied properly

### ISSUE THREAD

**Issue by lawfulsoftware** [Stirling-Tools/Stirling-PDF#974]
https://github.com/Stirling-Tools/Stirling-PDF/blob/31ec3852829505ebba9f5b387cb3e3eaf8a005a9/Dockerfile#L7
https://github.com/Stirling-Tools/Stirling-PDF/blob/31ec3852829505ebba9f5b387cb3e3eaf8a005a9/Dockerfile#L8

These two lines are supposed to copy fonts from `src/main/resources/static/fonts` to `/usr/share/fonts/opentype/noto/`

The contents of the `/usr/share/fonts/opentype/` in the Docker container is a single file called `noto`

I see the following issues:

1. The `src/main/resources/static/fonts` directory contains the sub-directory `static` however the copy command is not recursive.
2. The copy target is not specified to be a directory; a `/` should be appended to the end.
3. The directory should be created prior to copying using `RUN mkdir -p`
4. The `src/main/resources/static/fonts/` directory does not actually contain any `.otf` files.  The files in that directory are all either `.ttf.` or `.woff2`
5. If the intention is to copy all of the files from the directory, the copy command could be consolidated to `COPY src/main/resources/static/fonts/* /usr/share/fonts/opentype/noto/`

**Comment by Frooodle** [comment]
completly missed this issue ticket, You should have raised a PR! thanks for this

**Comment by Frooodle** [comment]
Missed this issue fixing now to add the /
