### ISSUE TITLE
How to Make Changes in Frontend Code/Layout Stirling PDF

### ISSUE THREAD

**Issue by mkamranmazhar** [Stirling-Tools/Stirling-PDF#981]
Thank you for this amazing PDF open-source project!

I've successfully running Stirling PDF Docker on my server.

I'm looking to make some changes to its frontend layout. However, I'm encountering difficulty understanding where the frontend files are located within the Docker container.

someone please guide me on how to locate the frontend files within the Docker container or provide insights into where these files might be stored?

Thank you!

**Comment by sbplat** [comment]
HTML files can be found in
```
src/main/resources/templates/
```
and everything else is in
```
src/main/resources/static/
```

**Comment by mkamranmazhar** [comment]
I don't have options for 'src/main/resources/templates/' directory.

Please check attached Images.

![Screenshot 2024-03-27 110903](https://github.com/Stirling-Tools/Stirling-PDF/assets/106512746/950973ef-d1b3-4750-9fc9-133699da62b2)

![Screenshot 2024-03-27 110954](https://github.com/Stirling-Tools/Stirling-PDF/assets/106512746/2daf446b-213d-4d27-acde-aed6f8601c84)

**Comment by mkamranmazhar** [comment]
> HTML files can be found in
> 
> ```
> src/main/resources/templates/
> ```
> 
> and everything else is in
> 
> ```
> src/main/resources/static/
> ```

Please also update.

Thank you!

**Comment by Frooodle** [comment]
Source files are not available via the docker itself 
Sadly this all runs with java so all files are compiled inside the .jar file itself 

The files discussed are the source files used found within docker
