### ISSUE TITLE
URL To PDF Not Working Stirling PDF

### ISSUE THREAD

**Issue by mkamranmazhar** [Stirling-Tools/Stirling-PDF#982]
Hello,

URL To PDF Convert Not Working Stirling PDF

Please check attached images.

![Screenshot 2024-03-27 030421](https://github.com/Stirling-Tools/Stirling-PDF/assets/106512746/75b1d975-59ea-4532-96f9-e49499985d90)

Please check response image.

![Screenshot 2024-03-27 030532](https://github.com/Stirling-Tools/Stirling-PDF/assets/106512746/5d69bf1b-63a8-4785-a68e-a8dbf51c28ac)

Server Details:
OS: CentOS 7
aaPanel

**Comment by mkamranmazhar** [comment]
Error: 500 Internal Server Error

Cannot run program "wkhtmltopdf": error=2, No such file or directory for path: /api/v1/convert/url/pdf

**Comment by sbplat** [comment]
Is this docker?

**Comment by mkamranmazhar** [comment]
yes docker.

here is my docker-compose.yaml

`version: '3.3'

services:

  stirling-pdf:
    image: frooodle/s-pdf:latest
    container_name: s-pdf
    ports:
      - '8200:8080'
    volumes:
      - ./spdf/trainingData:/usr/share/tesseract-ocr/4.00/tessdata #Required for extra OCR languages
      - ./spdf/extraConfigs:/configs
    environment:
      APP_LOCALE: es-ES
      APP_HOME_NAME: Stirling PDF AskSEOTools
      APP_HOME_DESCRIPTION: Un único sitio, alojado localmente, para todas sus necesidades de PDF.
      APP_NAVBAR_NAME: Stirling PDF
      APP_ROOT_PATH: /
      ALLOW_GOOGLE_VISIBILITY: true
      INSTALL_BOOK_AND_ADVANCED_HTML_OPS: true`

**Comment by mkamranmazhar** [comment]
> Is this docker?

Please update.

**Comment by sbplat** [comment]
We switched from `wkhtmltopdf` to `calibre` in #797 and it looks like we forgot to update this.

**Comment by Frooodle** [comment]
Meant to keep both, with calibre being a more advanced version, will re-add weasyprint and use this

**Comment by Frooodle** [comment]
Should be resolved in later versions
