### ISSUE TITLE
How to solve the  issue？ pdftoword!

### ISSUE THREAD

**Issue by xingzhej** [Stirling-Tools/Stirling-PDF#995]
No matter how many pages, the conversion is 1 page。

**Comment by Frooodle** [comment]
Known issue we are investigating
Sorry for this!

**Comment by xingzhej** [comment]
The 0.20.2 is ok!

**Comment by xingzhej** [comment]
> Known issue we are investigating Sorry for this!

The 0.20.2 is ok!

**Comment by Frooodle** [comment]
Try now please!

**Comment by xingzhej** [comment]
> Try now please!

thankyou,That`s OK!
